### ISSUE TITLE
[bug]: CIFS migration of 02x embassy asks for "password used to encrypt" unencrypted drive

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1001]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

![Screen Shot 2021-12-27 at 1 07 33 PM](https://user-images.githubusercontent.com/45926711/147507445-b306882e-a6e0-450d-8377-aee08d02677d.png)

### Expected Behavior

Shouldn't ask for password - drive is not encrypted.

### Steps to Reproduce

CIFS recovery of 0.2.x Embassy that was running of an SSD - *not* an SD card.

SSD contents copied into a directory on a Mac (cannot share the drive as Macs can't read ext4 and workarounds don't work).

Directory shared on network.

0.3.0 finds it, attempts to recover from it but throws the above error.

**Comment by BitcoinMechanic** [comment]
To be clear: this is coming from a normal, shared folder on my mac's internal drive. Currently there is no way to share an ext4 volume plugged into a mac that I can find. Have attempted macfuse/osxfuse etc.

**Comment by chrisguida** [comment]
Did you try your embassy master password? We should probably change the messaging here

**Comment by BitcoinMechanic** [comment]
Yes

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by chrisguida** [comment]
You used the same embassy password you used to create the backup? And it didn't work? Were there any errors in the console or network tabs?

**Comment by BitcoinMechanic** [comment]
This is the process that anyone will have to go through that has built Embassy from source and used either mine or T0mmysmith's guides - and hence had their 0.2.x boxes running off SSDs instead of SD cards.

**Comment by BitcoinMechanic** [comment]
This now works.
