### ISSUE TITLE
Linux kernal not updating

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1012]
Reported by an 0.3 beta tester.  I have never seen this, but will attempt to reproduce.  

Suggested fix is to add a second upgrade command after `apt-get upgrade -y`

`apt-get --with-new-pkgs upgrade-y`

**Comment by dr-bonez** [comment]
need to investigate which kernel version we are using and whether that is desired.

**Comment by klicha** [comment]
After `apt-get upgrade -y` kernel will remain in version 5.11.0-1007

`
Dec 30 12:17:33 ubuntu initialization.sh[7819]: The following packages have been kept back:
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   linux-headers-raspi linux-image-raspi linux-raspi ubuntu-advantage-tools
Dec 30 12:17:33 ubuntu initialization.sh[7819]: The following packages will be upgraded:
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   accountsservice alsa-ucm-conf apparmor apport apt apt-utils base-passwd
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   bind9-dnsutils bind9-host bind9-libs busybox-initramfs busybox-static
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   ca-certificates cloud-init cpio curl distro-info-data flash-kernel fwupd
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   fwupd-signed gcc-11-base isc-dhcp-client isc-dhcp-common landscape-common
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libaccountsservice0 libapparmor1 libapt-pkg6.0 libasound2 libasound2-data
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libcurl3-gnutls libcurl4 libdrm-common libdrm2 libfwupd2 libfwupdplugin1
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libgcc-s1 libgcrypt20 libglib2.0-0 libglib2.0-bin libglib2.0-data
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libhogweed6 libicu67 liblz4-1 libnetplan0 libnettle8 libnss-systemd libnss3
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libntfs-3g883 libpam-modules libpam-modules-bin libpam-runtime
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libpam-systemd libpam0g libperl5.32 libpolkit-agent-1-0
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libpolkit-gobject-1-0 libprocps8 libpython3.9 libpython3.9-minimal
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libpython3.9-stdlib libssh-4 libssl1.1 libstdc++6 libsystemd0 libudev1
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   libudisks2-0 libuv1 libx11-6 libx11-data libxml2 linux-base linux-firmware
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   login lz4 manpages netplan.io networkd-dispatcher ntfs-3g openssh-client
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   openssh-server openssh-sftp-server openssl passwd perl perl-base
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   perl-modules-5.32 policykit-1 procps python-apt-common python3-apport
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   python3-apt python3-distupgrade python3-distutils python3-gdbm
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   python3-lib2to3 python3-problem-report python3-software-properties
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   python3-update-manager python3.9 python3.9-minimal snapd
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   software-properties-common sosreport squashfs-tools systemd systemd-sysv
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   tzdata ubuntu-release-upgrader-core udev udisks2 ufw update-manager-core
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   update-notifier-common usrmerge vim vim-common vim-runtime vim-tiny
Dec 30 12:17:33 ubuntu initialization.sh[7819]:   wireless-regdb xxd
Dec 30 12:17:33 ubuntu initialization.sh[7819]: 120 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
`

After `apt-get --with-new-pkgs upgrade-y` as second command kernel will upgrade to version 5.11.0-1023

`
Dec 30 12:28:30 ubuntu initialization.sh[44168]: The following NEW packages will be installed:
Dec 30 12:28:30 ubuntu initialization.sh[44168]:   distro-info linux-headers-5.11.0-1023-raspi linux-image-5.11.0-1023-raspi
Dec 30 12:28:30 ubuntu initialization.sh[44168]:   linux-modules-5.11.0-1023-raspi linux-raspi-headers-5.11.0-1023
Dec 30 12:28:30 ubuntu initialization.sh[44168]: The following packages will be upgraded:
Dec 30 12:28:30 ubuntu initialization.sh[44168]:   linux-headers-raspi linux-image-raspi linux-raspi ubuntu-advantage-tools
Dec 30 12:28:30 ubuntu initialization.sh[44168]: 4 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
`

`
root@embassy-a6d860c5:~# uname -a
Linux embassy-a6d860c5 5.11.0-1023-raspi #25-Ubuntu SMP PREEMPT Fri Nov 19 07:45:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
`

**Comment by klicha** [comment]
![2021-12-31 20-49-27](https://user-images.githubusercontent.com/77979246/147837526-7dc7ccfc-5598-4f03-8bce-eab1d72f8861.png)

Sorry for screenshot, I don't know how to insert text to be well formatted.

**Comment by kn0wmad** [comment]
^ Original reporter, thanks @klicha

**Comment by ProofOfKeags** [comment]
Is this part of the init script? In general we don't want to support user driven kernel upgrades *independent* of EOS upgrades.

**Comment by kn0wmad** [comment]
I believe the kernel is updated as part of the init script, OP is suggesting we add a line to force it as his init did not complete kernel upgrades.  I have not witnessed this issue

**Comment by ProofOfKeags** [comment]
We should be pinning the kernel version every EOS release rather than leaving it up to the latest package versions so that we reduce the chances of system divergence in the DIY case.

**Comment by kn0wmad** [comment]
Sounds good, is this assigned appropriately then?

**Comment by dr-bonez** [comment]
> need to investigate which kernel version we are using and whether that is desired.

this is the correct scope of work for this ticket

**Comment by Blu-J** [comment]
```sh
root@embassy-27adf846:~# apt-get --with-new-pkgs upgrade -y
#Reading package lists... Done
#Building dependency tree... Done
#Reading state information... Done
#Calculating upgrade... Done
#0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
So the only way that I was seeing a new version of the os was doing an 
`sudo apt update`

Now, on for the side of locking, we could follow https://askubuntu.com/questions/938494/how-to-i-prevent-ubuntu-from-kernel-version-upgrade-and-notification
But this doesn't make sense to lock the version of the OS. Right now because we are not doing an apt-update we don't have the issue that the builders will have another OS. And if they do, we are going to run into bigger issues that the rest of the programs will have different versions, which is loads worse than holding the version of the os.

**Comment by ProofOfKeags** [comment]
We currently do kernel updates as part of the initialization.sh script. 

https://github.com/Start9Labs/embassy-os/blob/integration/0.3.0/build/initialization.sh#L9-L32

**Comment by Blu-J** [comment]
We are going to stick with the locked in version
