### ISSUE TITLE
Unable to recover existing Embassy disk

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1019]
Disk management error, undefined

RPC ERROR in console

![image](https://user-images.githubusercontent.com/39687477/147940950-78b02860-67e1-47b6-9e61-f518ab69c0cb.png)

Reboot does fix.

Sidenote: "importing" spinner lasts a very long time, a progress bar would be preferred

Reported by: @kn0wmad

**Comment by dr-bonez** [comment]
it would be nice to see what the failed request was. If you can, repro and click through the v1s on the network tab, see if there is an rpc error

**Comment by chrisguida** [comment]
Here's mine

![Screenshot from 2021-12-24 12-01-10_20220103160138.png](https://user-images.githubusercontent.com/7445670/147985191-0df48b00-2446-4833-b1f2-db6c733805a8.png)

IIRC there weren't any failures on the network tab

**Comment by dr-bonez** [comment]
@DrewAns can you explain why it would say undefined in the toast, when the details are clearly there in the console?

**Comment by DrewAns** [comment]
@dr-bonez errors in the setup wizard display the message key on every error

**Comment by dr-bonez** [comment]
it did, but it should also display `data.details` which it clearly is not here.

**Comment by kn0wmad** [comment]
Was able to repro, but different error this time:

![image](https://user-images.githubusercontent.com/39687477/148083709-52b0218a-696b-4942-8785-e4d46367b9c4.png)

**Comment by dr-bonez** [comment]
is it possible that this drive went through a partial setup?

**Comment by kn0wmad** [comment]
I don't think so.  No issues on initial setup, and after reboots has no issues

**Comment by Blu-J** [comment]
Okay, so I can't recreate if I use the same product key
But if I use another product key I get an error, which I forgot to capture.

Not sure what is wrong or how to fix. Maybe we could figure out if the keys are different?

**Comment by dr-bonez** [comment]
you are getting the same error?
`... is not a valid LUKS device...`?
