### ISSUE TITLE
Improper placement of status when service installing

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1028]
The status percentage section previously appeared above the loading bars and should be corrected to present that way again.

<img width="1680" alt="Screen Shot 2022-01-04 at 3 34 37 PM" src="https://user-images.githubusercontent.com/12953208/148133953-bc91ec94-7848-4f18-b4b1-b3fc2230283b.png">

git hash: 4f6aca7712735dca3a0e2c7e697e83229493a242

**Comment by elvece** [comment]
Now, nothing appears on the service show page while the service is installing. @DrewAns 

<img width="1671" alt="Screen Shot 2022-01-10 at 12 12 04 PM" src="https://user-images.githubusercontent.com/12953208/148828452-43670d5f-68c4-45f6-923e-53a3ae688737.png">

**Comment by ProofOfKeags** [comment]
Is the status of this affected by #1055 ?

**Comment by DrewAns** [comment]
This was fixed by Alex's pr
