### ISSUE TITLE
Health checks displaying nothing on service start

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1029]
The health check section previously displayed a loading spinner when the service was started, and the result of the health checks were still pending. Now there is nothing there. 

<img width="1680" alt="Screen Shot 2022-01-04 at 3 41 47 PM" src="https://user-images.githubusercontent.com/12953208/148134150-6c6aed3f-68e2-4363-b8aa-128489730a48.png">

git hash: 4f6aca7712735dca3a0e2c7e697e83229493a242

**Comment by chrisguida** [comment]
I figured this was intended behavior. Does this negatively impact the experience?

**Comment by elvece** [comment]
I think so, it looks awkward visually and does not effectively communicate health check state. 

Also, like I mentioned, there previously was a spinner while it was loading and if that was removed intentionally, I'm curious why.

**Comment by ProofOfKeags** [comment]
@MattDHill please assess priority here.

**Comment by MattDHill** [comment]
This is almost certainly a bug resulting from the refactor of this component. It is high priority because it indicates a regression, which could be more extensive than this presentation. Assigning @DrewAns
