### ISSUE TITLE
[bug]: Setup Wizard asks for product key even when `product-key: false`

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1040]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

unknown

### Browser

Firefox

### Browser Version

unknown

### Current Behavior

When an embassy is flashed without a product key, the setup wizard asks for a product key before asking for a recovery drive.

### Expected Behavior

The setup wizard should ask for an 0.2.x recovery drive before asking for a product key.

### Steps to Reproduce

1. Full-Flash an embassy with `NO_KEY=1`
2. Open setup flow

### Anything else?

Backend response for `setup.status` is 
```json
{
  "product-key": false,
  "migrating": false
}
```

**Comment by ProofOfKeags** [comment]
@DrewAns if this is in CR where is the PR?

**Comment by BitcoinMechanic** [comment]
This may now be fixed and given way to an issue with the following step:

https://github.com/Start9Labs/embassy-os/issues/1041
