### ISSUE TITLE
[bug]: Setup wizard doesn't accept product key when migrating from 0.2x with NO_KEY=1

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1041]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

After going straight to recovery as it should, it returns to Product Key entry
![Screen Shot 2022-01-07 at 12 36 08 PM](https://user-images.githubusercontent.com/45926711/148611781-1059750c-45b0-4c1a-a0f4-dc753f7acfe5.png)

This is expected I believe, but the product key for the 0.2x build I am migrating from does not work. 

### Expected Behavior

That product key should work.

### Steps to Reproduce

Build 0.3.0 with flag NO_KEY=1
Attempt to migrate from 0.2x
Enter product key from 0.2x

### Anything else?

This might be a dupliacte of https://github.com/Start9Labs/embassy-os/issues/1040

**Comment by dr-bonez** [comment]
fortunately the screenshot you sent includes enough of the error :)
in future bug reports, please copy the contents of `error.details`, and `error.debug` into the ticket.

**Comment by BitcoinMechanic** [comment]
Just tested - this works now.
