### ISSUE TITLE
[feat]: Change of Country Messaging + Refresh

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1043]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

I don't want to refresh the options when I change countries.

https://user-images.githubusercontent.com/2364004/148620168-8e6462f0-f701-4556-9e34-ccde12f35b3f.mp4

Also we need to let the users know that the action of changing the countries is going to make the configurations be dropped.

### Describe the Use Case

These are small improvements for ease of life and messaging for the country changes.

**Comment by dr-bonez** [comment]
@MattDHill please consult on messaging

**Comment by DrewAns** [comment]
https://github.com/Start9Labs/embassy-os/commit/1086ce13d2a0abb6ac81c6f0278e65b99443bcba

messaging taken care of by this pr
