### ISSUE TITLE
[bug]: Embassy has 2 working IP addresses for eth0

### ISSUE THREAD

**Issue by pieslinger** [Start9Labs/embassy-os#1044]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0 165e919e630e9e68e7108cf73c0a1a97bec6b12b

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 21.04

### Browser

Firefox

### Browser Version

95.0.1

### Current Behavior

After sshing in to my Embassy I noticed it has 2 IP addresses for eth0. Both can be pinged. Not sure if this is by design or not. Based on my router's screenshot and the machine names - its possible it has to do with the initialization process.

![Screenshot from 2022-01-08 00-09-45](https://user-images.githubusercontent.com/87915068/148656538-23b0c8dd-2790-4edd-825b-716863753f74.png)
 
![Screenshot from 2022-01-08 12-07-30](https://user-images.githubusercontent.com/87915068/148656634-6be260a6-9674-45e7-ad6b-f54ffae1c691.png)

### Expected Behavior

A single IP address for eth0.

### Steps to Reproduce

As described.

**Comment by dr-bonez** [comment]
@pieslinger are you having any network problems as a result of this?

**Comment by pieslinger** [comment]
No apparent network issues. I just noticed it in my router and then when sshing in. For kicks, I tried to ping both and they worked.

**Comment by ProofOfKeags** [comment]
If there aren't networking issues I'm gonna suggest we P3 this @dr-bonez

**Comment by pieslinger** [comment]
FYI - I could not recreate this on another router only with a Ubiquiti  EdgeRouter X.
