### ISSUE TITLE
[bug]: Vaultwarden LAN URL takes you back to Embassy login screen.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1045]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

![Screen Shot 2022-01-10 at 10 03 16 AM](https://user-images.githubusercontent.com/45926711/148815973-165dda32-3b8f-4cfa-92b8-f6ec39da5e4f.png)

### Expected Behavior

Interface for Vaultwarden should load (works fine using Tor interface)

### Steps to Reproduce

0.3.0 -> Installed Vaultwarden -> Launch LAN interface

**Comment by chrisguida** [comment]
<img width="488" alt="Screen Shot 2022-01-10 at 12 21 50 PM" src="https://user-images.githubusercontent.com/7445670/148818441-571f10cc-80fe-46e1-bffd-1f1dc59458b7.png">

**Comment by ProofOfKeags** [comment]
this is an nginx problem for sure. if it was an mDNS thing it wouldn't resolve at all.

**Comment by ProofOfKeags** [comment]
This is an issue in how we handle the port mapping. I need to change how the different aspects of the port mapping are written to the nginx config.

**Comment by ProofOfKeags** [comment]
@BitcoinMechanic this should be ready for testing as of b270011131aea8c325c8b2bb9f084eddab11f217

**Comment by BitcoinMechanic** [comment]
Tested on a normal build (wasn't migrating). It worked as expected. I don't think migrating is necessary to test here.
