### ISSUE TITLE
[feat]: Add Debouncer to Error Log Reporting

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#1046]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Add time+count based debouncer to the sharing layer of the embassy-os logger

### Describe the Use Case

Right now we have someone spamming the error logs reporting endpoint multiple times a second, this is putting unnecessary load on the central infrastructure.

### Describe Preferred Solution

We should buffer error log reporting on a certain time or size interval and batch upload them to the endpoint.

### Describe Alternatives

We can also literally debounce errors at the sharing layer and not report numerous duplicates.

**Comment by dr-bonez** [comment]
error log reporting is no longer a thing
