### ISSUE TITLE
[feat]: Support backing up multiple devices in the same cifs folder

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1056]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Currently when you back up, if there is a backup from an old device, the old backup is overwritten with data from the new device, and then the old device's backup is inaccessible. We need better support for backing up multiple devices on the same shared drive, or else communicate better to the user the dangers of using the same folder for multiple devices.

### Describe the Use Case

When I set up a new device, but I already have a CIFS folder from a previous device, the obvious choice is to re-use the existing folder, since creating a new folder is a bit involved and I have to look up how to do it every time. If there are existing backups in that folder from a different device, those backups are overwritten.

### Describe Preferred Solution

Ideally we'd create a separate backup for every new device id. Probably by keeping different devices in different subdirectories

### Describe Alternatives

Detect if someone is trying to backup over a different device. If not, warn them, and tell them to make a new cifs folder if this is not what they intended to do

Or, just communicate the danger of using old cifs folders a lot more loudly.

**Comment by k0gen** [comment]
Right now folder name `EmbassyBackups` is being created.
How about simply name this folder `Embassy-q1w2e3-Backups`?

**Comment by elvece** [comment]
Closing in favor of https://github.com/Start9Labs/embassy-os/issues/2053
