### ISSUE TITLE
Breakages improperly reported

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/embassy-os#1062]
Prerequisites

    I have searched for existing issues that already report this problem, without success.

EmbassyOS Version

0.3.0
Device

Laptop/Desktop
Device OS

MacOS
Device OS Version

unknown
Browser

Firefox
Browser Version

unknown
Current Behavior

When i download both c lightning and bitcoin, run them both and uninstall btc, the breakages response from the BE is empty
![0559540d-3711-473c-91db-ecffad20b9f4](https://user-images.githubusercontent.com/6719222/149380246-3f4ee787-6b2a-4528-807b-d4a292952c8e.png)

**Comment by ProofOfKeags** [comment]
you screenshotted the request not the response.

**Comment by dr-bonez** [comment]
c-lightning depends on proxy, not bitcoind. so if proxy was never installed, there is no new breakage when uninstalling bitcoind, so this is correct behaviour

**Comment by ProofOfKeags** [comment]
@DrewAns please try this again with proxy.

**Comment by DrewAns** [comment]
nm this works
