### ISSUE TITLE
Create image with marketplace for store

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1078]
Update image that is currently on the website to show the new marketplace to this can be added to the Start9 store.

**Comment by kn0wmad** [comment]
![image](https://user-images.githubusercontent.com/39687477/149631293-ea00971f-1732-44d7-a907-431c5759ab4b.png)

I don't like that BWT shows, but this is the only page that fills and shows the most available options

**Comment by chrisguida** [comment]
We can remove bwt from beta, I'm not making progress on it and I don't think we're planning to release it with 0.3

**Comment by elvece** [comment]
Completed images can been seen [here](https://github.com/Start9Labs/embassy-os)
