### ISSUE TITLE
[bug]: Cannot select text (...can't copy error messages) when expanding notifications.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1081]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

.

### Expected Behavior

.

### Steps to Reproduce

.

**Comment by dr-bonez** [comment]
@BitcoinMechanic I *do* understand what this ticket means, but a short sentence in current and expected behavior are helpful.
