### ISSUE TITLE
Assign unique names to Embassy Root CAs

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1082]
Currently all files are named Embassy Root CA, which is confusing if you have to download more than one

May close #1068 

Reported by: @kn0wmad

**Comment by k0gen** [comment]
Simply name it by the hostname + .crt
like:
`embassy-q1w2e3.crt`

**Comment by ProofOfKeags** [comment]
The only trouble will be the migration from 02x. We can absolutely do this. But theres no way to change it without forcing people to redo their trust setup. Given that the CA trust setup is the most annoying part of the setup UX, we've preferred to migrate them as opposed to regenerate them. So even if net-new generation has the host id in it, it may not take effect for many users coming from an old system.

**Comment by chrisguida** [comment]
Seems reasonable to just update the name for new 0.3 boxes then?

**Comment by k0gen** [comment]
<img width="980" alt="Screenshot 2022-04-20 at 21 19 11" src="https://user-images.githubusercontent.com/3606313/164784321-125d4841-11e3-45f8-9a79-94869f7d7587.png">

Screenshot as an reminder 😉
