### ISSUE TITLE
[feat]: Custom MOTD for EmbassyOS

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#1083]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

When users login to their Embassy via ssh they are grated with standard/boring ubuntu's MOTD. The idea is to fine tune MOTD to display useful information for EmbassyOS (not ubuntu).

### Describe the Use Case

Cooler shell experience. 

### Describe Preferred Solution

Here is my MOTD shell as an example
![Screenshot from 2022-01-15 21-50-48](https://user-images.githubusercontent.com/3606313/149651448-8dcee624-3fe8-42a9-8242-3d411189d36b.png)

### Describe Alternatives
```
Welcome to
,---.     |                        ,---.,---.
|--- ,-.-.|---.,---.,---.,---.,   .|   |`---.
|    | | ||   |,---|`---.`---.|   ||   |    |
`---'` ' '`---'`---^`---'`---'`---|`---'`---'
                              `---'  B E T A
```
```
WELCOME TO
 _____       _                   _____ _____
|   __|_____| |_ ___ ___ ___ _ _|     |   __|
|   __|     | . | .'|_ -|_ -| | |  |  |__   |
|_____|_|_|_|___|__,|___|___|_  |_____|_____|
                            |___|  0.3.0 BETA
```

### Anything else?

This would look even better with issue #904 implemented

**Comment by kn0wmad** [comment]
I think you could go ahead and make a PR for this one for consideration / review by the team.  Looks cool!!

**Comment by ProofOfKeags** [comment]
We will accept a PR that implements this, if you need guidance on exactly what to change please reach out. I haven't done anything with MOTD's before so I may need to understand what you actually did to get this to happen in the pictures you submitted above but this should be doable.

**Comment by k0gen** [comment]
OK than.
Keep smashing those bugs guys and I'll do my best to beautify Embassy's shell experience.

**Comment by k0gen** [comment]
The initial work is done. Merging #1116 will result in something like this:

![Screenshot from 2022-01-23 16-28-01](https://user-images.githubusercontent.com/3606313/150685982-0542698f-3b73-4804-82d4-b028188fc50a.png)

Because ubuntus landscape-sysinfo is broken at the moment I have disabled it. We can discuss fixing it or just adding our own code to `00-embassy` file.
