### ISSUE TITLE
[bug]: Recovery from backup failing

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1086]
Backing up and then restoring to an external HD results in the error below.

<img width="1673" alt="Screen Shot 2022-01-14 at 6 42 09 PM" src="https://user-images.githubusercontent.com/12953208/149841947-decdd1f5-d623-45ef-8e00-2270a2945004.png">

**Comment by ProofOfKeags** [comment]
Is this reproducible. It is certainly possible that this is downstream of the drive powering issue.

**Comment by dr-bonez** [comment]
ok so what this *primarily* tells me is that we need to change how we do error handling for individual package restore failures during a full embassy restore. 

the error message here does not look like a disk i/o issue. this is probably a duplicity specific issue that needs to be resolved.

**Comment by elvece** [comment]
Reproducing this error is still in progress. Upon further testing, I *think* this issue may have arose from clicking the wrong button in the recover flow. I definitely clicked "Use drive" in the first iteration of this test. I have subsequently clicked "Cancel" as correctly indicated for the recover from backup flow that is intended to be tested. This resulted in other errors that blocked completion yesterday; testing with these fixes will resume today.

<img width="1331" alt="Screen Shot 2022-01-26 at 2 49 35 PM" src="https://user-images.githubusercontent.com/12953208/151416827-4f9218d9-b05a-4c62-86af-c911ce882aea.png">

**Comment by dr-bonez** [comment]
Ok, so this is a specific service failing to recover... It begs the question whether we should fail the entire recovery over a single service failure.

**Comment by ProofOfKeags** [comment]
In general, we should not fail the entire thing, at least not unconditionally. However, I think we should also try to fix as many failures as we can. Do we know *why* it is failing?

**Comment by dr-bonez** [comment]
blocks #1160

**Comment by elvece** [comment]
Update: The environment to test this still needs to be recreated, which will be accomplished when [this](https://github.com/Start9Labs/embassy/issues/7) is in progress.
