### ISSUE TITLE
[feat]: Do not rebuild docker state on every restart.

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1087]
Currently, we wipe and rebuild docker state (/var/lib/docker) on every restart. This is very slow, and it may be better to only do this if specifically requested.

**Comment by ProofOfKeags** [comment]
The main problem we are trying to circumvent here is getting the system to boot and quickly be in a usable state. Currently the main blocker for startup times is image loading on the state rebuild of Docker. What has been discussed so far is that we are going to move this to a button in the UI with some extreme messaging indicating that it is an expensive operation.

This will involve excluding the docker state from the overlayfs and intentionally resetting it based off of an action.
