### ISSUE TITLE
Set current dependencies when configuration changes for optional dependencies

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1111]
This problem is best explained with the specific example of btcpay. When configured to use either lnd or clightning, btcpay's dependencies do not reflect the updated dependency configuration. This is because the dependency is not listed in the `current-dependencies`. The reason it is not reflected in this list is because the config spec no longer has a pointer to either of these services once the configuration choice has been made. This was solved in 0.2.x using lan address pointers (which were needed to access lnd/clightning), and no longer exist in 0.3.0. To solve this, we can either have a dummy pointer, which is confusing and misleading, or augment the compat image to set dependencies on configuration using a new file and the existing config rules language, which is the more elegant and robust solution.

This ticket is tracking the latter implementation.

**Comment by chrisguida** [comment]
Am I understanding that this will add a new file just for config dependencies? `dependencies.yaml` or something?

**Comment by elvece** [comment]
Implementation in wrapper looks like [this](https://github.com/Start9Labs/btcpayserver-wrapper/pull/9/commits/e90c31fafb64adb7bf5a8f92f16a2a47c244d511).
