### ISSUE TITLE
[bug]: Error by stopping service

### ISSUE THREAD

**Issue by klicha** [Start9Labs/embassy-os#1117]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Linux embassy-ac7cb5e2 5.11.0-1007-raspi #7-Ubuntu SMP PREEMPT Wed Apr 14 22:08:05 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### Browser

Chrome

### Browser Version

97.0.4692.99

### Current Behavior

Yesterday I compiled a new image embassy.img version 0.3.0. I have the following 4 services running: Bitcoin Core, Bitcoin Proxy, Lightning Network Daemon and Ride the Lightning. I tried to stop them gradually. First Ride the Lightning ... the service stopped without any problems. Then LND ... stopping the service took a long time and never ended. The following errors occurred in the log file:
![Snímek obrazovky pořízený 2022-01-23 12-15-22](https://user-images.githubusercontent.com/77979246/150688416-d650bf34-4e88-471a-b43d-cf49b7d69530.png)

Embassy has been responding ever since with Error: Bad Gateway for almost every event. I can't shutdown or restart Embassy. For example, when I try to start the RTL service again I got following error in the log file:
![Snímek obrazovky pořízený 2022-01-23 12-15-52](https://user-images.githubusercontent.com/77979246/150688470-c49a65b0-d3a7-44d9-bbdc-dcb07c6416bf.png)

### Expected Behavior

Stop the service without errors.

### Steps to Reproduce

1. Start LND service
2. Stop LND service

**Comment by klicha** [comment]
A similar error occurs when I run a backup and the Bitcoin Core service is running.
![Snímek obrazovky pořízený 2022-01-23 20-31-21](https://user-images.githubusercontent.com/77979246/150695006-2ceac1da-33c4-4ca7-8442-65d812d2ff20.png)
If all services are stopped, the backup will be OK.
The bitcoind.embassy docker container remains paused after this error. The UI reports a Bad Gateway error and does not respond to anything.

**Comment by dr-bonez** [comment]
duplicate #1115
