### ISSUE TITLE
[bug] Updating from 0.3.0 to 0.3.1 via Marketplace fails and seemingly causes future I/O errors

### ISSUE THREAD

**Issue by chadat23** [Start9Labs/embassy-os#1122]
I haven't searched existing issues but I was asked to report a bug via Telegram

EmbassyOS Version
0.3.0 [86cccca](https://github.com/Start9Labs/embassy-os/commit/86cccca0c5fb06dd9cc4c549e21ed2d231193106#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

Device
8gb Pi 4 with the recommended 1T drive and enclosure & laptop

Device OS
PopOS

Device OS Version
20.10

Browser
Firefox

Browser Version
96.0

Current Behavior
While trying to update from 0.3.0 to 0.3.1 via the Marketplace, multiple times, the update downloaded, the shutdown chime sounded and then I received an error: `EmbassyOS Update Failed
Update was not successful because of Network Error: Hash sum does not match source `. Now, despite multiple restarts, when I click to update I immediately get the error: `EmbassyOS Update Failed
Update was not successful because of Filesystem I/O Error: No such file or directory (os error 2) `. Additionally, the `Downloading EOS` progress bar is stuck on the bottom of the window and it's stuck at 0%.

Expected Behavior
.

Steps to Reproduce
.

Anything else?
Another Telegram 030 beta testing person reported the same behavior.

**Comment by ProofOfKeags** [comment]
Should be fixed now. This is an issue with the central infrastructure that hosts the new images. We have cleared the mismatched hash problem.

**Comment by chadat23** [comment]
Something on my end still seems to be messed up/not automatically recovering. I'm still getting the same I/O Error.

**Comment by ProofOfKeags** [comment]
@dr-bonez did you fix this with #1119?

**Comment by dr-bonez** [comment]
yes
