### ISSUE TITLE
[refactor]: abstract avahi error handling

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1147]
Currently we have a lot of syntactic redundancy in the [mdns](https://github.com/Start9Labs/embassy-os/tree/master/backend/src/net/mdns.rs) module. We should eliminate this to reduce probability of issues introduced by future refactors.

**Comment by dr-bonez** [comment]
@ProofOfKeags please fill out the description on this

**Comment by ProofOfKeags** [comment]
Currently we have a lot of syntactic redundancy in the [mdns](https://github.com/Start9Labs/embassy-os/tree/backend/src/net/mdns.rs) module. We should eliminate this to reduce probability of issues introduced by future refactors.
