### ISSUE TITLE
explore different kernels or base OS's to resolve stability issues

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1155]
related #901 

Currently the raspberry pi has stability issues after being up for several days. Investigation into this has revealed processes are getting stuck in state `R` while being unable to be `SIGKILL`ed. According to https://unix.stackexchange.com/questions/386380/wget-cant-be-killed-with-kill-9, this is either a hardware fault or a kernel bug. Given that there is likely a problem with the kernel, or its compatibility with the pi, we need to upgrade the kernel. We have a few options here:

- Upgrade the kernel in `initialization.sh`
- Use the official Raspberry Pi OS as the base image (https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-05-28/)

**Comment by chrisguida** [comment]
Did we try RaspiOS?

**Comment by ProofOfKeags** [comment]
CC @Blu-J
