### ISSUE TITLE
[feat]: validate icon size when packing s9pk

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1163]
The size of an icon should be limited for performance reasons, especially given that we would like to cache them in memory. 

blocks #1150

**Comment by ProofOfKeags** [comment]
Validate only or shrink?

**Comment by chrisguida** [comment]
Maybe validate for P1, shrink for P2, unless shrinking is trivial?

**Comment by ProofOfKeags** [comment]
I suspect that any code needed to validate pixel dimensions of an image is going to be in a library capable of shrinking them. But if not, I agree. Validation is MVP.
