### ISSUE TITLE
[bug]: Better Errors When Wrapping + No Nginx Created

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1166]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

3fd3de293fac45b745b3691a1b1804cea6739950

### Browser

Firefox

### Browser Version

96.0

### Current Behavior

Trying to wrap a syncthing services.
Have the docker running.
Then after the wrapping, everything seems to be just fine *copied manifest from the filebrowser"
Installed into the os.
No nginx created for interfaces
![image](https://user-images.githubusercontent.com/2364004/152443101-aeec74bc-2c27-475e-826c-74964623090b.png)
And when clicking on the launch ui
![image](https://user-images.githubusercontent.com/2364004/152443184-33fa3b6c-0a68-4c31-b838-9f176fa11e2e.png)

I am then redirected to 
![image](https://user-images.githubusercontent.com/2364004/152443215-e67daf38-69b5-4f13-804c-e7e7424fc91f.png)

And this is proof
![image](https://user-images.githubusercontent.com/2364004/152443667-f8757a34-7733-4aae-82e9-b893f9afb06c.png)

That the system is currently working in the embassy system

### Expected Behavior

Tell me that the creation of nginx fails, or tell me there is something wrong in the manifest, 

### Steps to Reproduce

1. Pull https://github.com/Start9Labs/syncthing-wrapper/tree/f2090d020588a37f7b7ad977a71aab1183452471
2. Install into an embassy device
3. Notice the missing nginx after service is started

**Comment by ProofOfKeags** [comment]
Did you change anything about the manifest other than the id?

**Comment by ProofOfKeags** [comment]
what error would you expect? The manifest is the source of truth for how to set up the service in the embassy. At some point we can't distinguish between a mistake you make and there just not being any http protocols exposed by your service.

**Comment by dr-bonez** [comment]
If a service has a lan config and doesn't have http protocol, we should at least throw a warning

**Comment by chrisguida** [comment]
Did leaving out http break both the LAN and Tor frontends?

**Comment by Blu-J** [comment]
Not sure for the tor, but the port local and remote where swapped.

**Comment by dr-bonez** [comment]
tor requires tcp, not http

**Comment by dr-bonez** [comment]
relevant #1179

**Comment by elvece** [comment]
nginx be gone
