### ISSUE TITLE
[bug]: port mapping for lan is inverted from tor

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1168]
currently, for tor config, the external port is on the left, and the internal port is on the right.
for lan, the internal port is on the left, and the external port is under "mapping"

this is highly confusing and inconsistent.

@elvece @chrisguida fixing this will require updating all services

marking this as p1 cause we can't change it after shipping.

**Comment by ProofOfKeags** [comment]
Service checklist:
- [ ] bitcoind
- [ ] btc-rpc-proxy
- [ ] btcpayserver
- [ ] burn-after-reading
- [ ] c-lightning
- [ ] cups
- [ ] embassy-pages
- [ ] filebrowser
- [ ] lnd
- [ ] mastodon
- [ ] photoview
- [ ] ride-the-lightning
- [ ] spark-wallet
- [ ] sphinx-relay
- [ ] synapse
- [ ] thunderhub
- [ ] vaultwarden
