### ISSUE TITLE
Limit number of simultaneous installs

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1171]
Either solve issues surrounding large number of simultaneous installs, or create a queue and limit them

This also ought to apply to the installation of recovered services

Causes same issue as quoted in #905

Reported by: @kn0wmad

**Comment by chrisguida** [comment]
What is "a large number of installs", and what "bugs" are you seeing?

**Comment by kn0wmad** [comment]
This was discussed internally.  I noticed with 5-6 simultaneous installs and it causes failed installs and "hanging" (perceived, not permanent).  It's just a bad UX.  I personally think the solution is to just limit simultaneous installs to 3 (for now), but I don't know how difficult this is.  This is pretty common on any popular marketplace or app.

**Comment by ProofOfKeags** [comment]
kicking from 0.3.0 SoW

**Comment by kn0wmad** [comment]
Rebuilding a box and wanted to mention that multiple installs (3-4) while doing docker actions (configure) caused a crash.  Reproduced once after reboot.  Reboot is the solution.  This is easy enough to support to remain punted

**Comment by k0gen** [comment]
If the backup is done one by one, recovery should be like that as well.

**Comment by ProofOfKeags** [comment]
> If the backup is done one by one, recovery should be like that as well.

This is an issue primarily with fresh installs. Not with the overall backup restoration process. We have to put some upper bound on simultaneous installs so we don't hurt reliability.

**Comment by chrisguida** [comment]
People will probably hit this bug a lot when migrating from 02x, and probably very rarely otherwise

**Comment by cryptodread** [comment]
bumping this thread - migrating to 0.3.1 with all the service updates makes this prominent

**Comment by chrisguida** [comment]
Will be fixed by removing db locks #2052
