### ISSUE TITLE
Add flag to compile for beta marketplace in Makefile

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1174]
Since the front end gets compiled with a default configuration using `config-smaple.json`, whatever value is defined in this config for the marketplace is what anyone who builds from source will automatically be connected to. This value should default to the prod registry (registry.start9.com).

We need a case to include a convenience flag that alters this value when the user wants to compile for the beta registry. 

For example:
`Environment=dev KEY=somekey make gzip --beta`

I am not sure if this is possible with `make` in that precise syntax, something like [this](https://earthly.dev/blog/make-flags/) might need to be implemented instead.

**Comment by chrisguida** [comment]
I think this can also be implemented by adding a beta `make` target

**Comment by ProofOfKeags** [comment]
This is already a thing.

**Comment by ProofOfKeags** [comment]
There is already a flag in the backend code for this. right now the beta flag is default but that was going to change before release.

**Comment by chrisguida** [comment]
Does this mean that we don't need to build in any special way?

**Comment by ProofOfKeags** [comment]
you will if you want to change it away from the default. I was just providing extra context for what the scope of work is on this.

**Comment by dr-bonez** [comment]
`ENVIRONMENT=beta`
