### ISSUE TITLE
[feature]: Configurable startup delay and interval for healthchecks

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1180]
Sometimes health checks take over a minute to succeed, when the underlying service started succeeding after 5s. This significantly delays testing, among other things

**Comment by chrisguida** [comment]
What's wrong with this?

**Comment by dr-bonez** [comment]
we extended it to 10s in b57f12f7aec3be2c55029ea42cfa3ad9c7a09a2e, and haven't had issues since. I don't think it actually needs to be configurable, just needs to be long enough for the container to exist.

**Comment by chrisguida** [comment]
@dr-bonez I'm definitely still seeing this, at least on my HDD box. What would be the problem with configuring this in the manifest? Also, out of curiosity, why not use Docker's health checks?

**Comment by dr-bonez** [comment]
On what commit?

**Comment by chrisguida** [comment]
72cb451f5a4be02ad651e2c0bf4973dd8f36f9b1

**Comment by dr-bonez** [comment]
I guess it's possible that 10s isn't enough for an hdd, but that's sus. I'm not sure we should commit resources to tuning the experience for hdds though...

**Comment by chrisguida** [comment]
My alphabox has an HDD, I use it heavily for testing. The main reason I need this feature is to speed up testing.

This seems like it should just be a simple copy from the manifest into the `docker run` params: https://docs.docker.com/engine/reference/run/#healthcheck, if we were using docker's health check feature. Why not do that?
