### ISSUE TITLE
[bug]: Disk Metrics Reporting Incorrectly

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1182]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Arch

### Browser

Firefox

### Browser Version

96.0.3

### Current Behavior

Storage drive usage percentages are still way off.  On this box `df` reports 50%, which is accurate, but UI reports 79% as shown below;

![image](https://user-images.githubusercontent.com/39687477/153115886-bf2c9693-a82e-4534-a32c-40218e1b310a.png)

Another box shows about the same on `df` ~50%, but UI reports 64% as shown below:

![image](https://user-images.githubusercontent.com/39687477/153116070-db25cf73-770e-4a91-b2d0-7da55106a1de.png)

### Expected Behavior

Ballpark accurate disk use %age

### Steps to Reproduce

- Embassy Tab -> Metrics -> Disk
- Check `df`
- Compare

### Anything else?

Possibly related to #715

**Comment by DrewAns** [comment]
@kn0wmad It doesnt appear as thought the frontend does anything to mutate the data provided from the backend.  Im notifying @dr-bonez

**Comment by kn0wmad** [comment]
I would classify this as very low priority as well.  I only made a ticket for tracking and because beta testers are reporting it as well
