### ISSUE TITLE
[bug]: Containers launch before ntp is synced

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1193]
This causes bitcoind to autoreindex because it thinks the blocks are from the future

from @ProofOfKeags :

```
2022-01-31T22:08:59Z : The block database contains a block which appears to be from the future. This may be due to your computer's date and time being set incorrectly. Only rebuild the block database if you are sure that your computer's date and time are correct.
Please restart with -reindex or -reindex-chainstate to recover.
2022-01-31T22:08:59Z Aborted block database rebuild. Exiting.
```

We could fix this at the package level too (by not autoreindexing when this particular log message accompanies the autoreindex trigger message), but it seems like the real fix is to make sure, at the system level, that ntp is synced before launching containers.

**Comment by dr-bonez** [comment]
imo we shouldn't autoreindex on this message. seems dangerous. we can add a `Wants systemd-time-wait-sync.service` directive to embassy-init, but if ntp fails for whatever reason this can still happen

**Comment by ProofOfKeags** [comment]
> imo we shouldn't autoreindex on this message. seems dangerous. we can add a Wants systemd-time-wait-sync.service directive to embassy-init, but if ntp fails for whatever reason this can still happen

Completely agree, the autoreindex is triggering on a bad heuristic right now. We should probably improve the heuristic either way or potentially key off of exit codes assuming they are in any way different.
