### ISSUE TITLE
[feat]: "New Changes" badge on config and properties rows on the service to indicate when data has changed but has not been seen yet.

### ISSUE THREAD

**Issue by cryptodread** [Start9Labs/embassy-os#1213]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Display a badge/icon when there is a change in the config or properties page made by another process, and the user has not opened that config or properties page to see it yet.

### Describe the Use Case

When this service (A) changes the config/properties of another service (B), It would be useful for a user to be able to identify that the change was made when they navigate to the other service (B).

### Describe Preferred Solution

A colorful circular badge (green or red) on the same row as the page that contains the changed data.
This badge would disappear when the user opens the page to view the changed data.

### Describe Alternatives

The badge could be placed inside the config page similar to the 'changed' tag displayed when a config is changed during the "Needs Config" process.

**Comment by ProofOfKeags** [comment]
This should already be something for config. I'm not sure what a properties "change" would be, or rather, what constitutes "changed but not seen"

**Comment by MattDHill** [comment]
If service A makes a change to service B, the user must approve this change beforehand.

If a new version of a service introduces new Config options, these are already displayed as "New", and the user must save the config.

If a new version of a service introduces new Properties, there is no indication, nor is there an easy way to track whether or not he user has seen these new Properties. I do not see much value in building out this infra, as the newly added Properties (or just the fact that new Properties were added) can be included in the release notes. Closing.
