### ISSUE TITLE
[feat]: Add aliases for your embassy main UI

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/embassy-os#1220]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Ability to add an alias URL for your embassy landing page. This would be in addition to the default embassy-xxxxxxx.local URL.
This would need to come with a CA cert, or instructions on how to add a CA cert to the additional alias URL.

### Describe the Use Case

Having an alias URL will make it easier for a user with multiple embassy servers to be able to identify and use them over LAN.

### Describe Preferred Solution

Option on the Embassy page to add Alias URL, with a string field that has validation to make sure the URL is formed correctly.

**Comment by MattDHill** [comment]
Currently, you can create a friendly name for your Embassy inside the Preferences section of the Embassy tab. Is this sufficient? Or can you explain the use case where it's not?
