### ISSUE TITLE
[bug]: Bitcoind Recovery

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1225]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

?

### Browser

Firefox

### Browser Version

97.0

### Current Behavior

![image](https://user-images.githubusercontent.com/2364004/154375858-1e356c5e-da4c-447a-850d-22b08e7a83cb.png)

### Expected Behavior

There should be no error notifications after recovery

### Steps to Reproduce

1. Create a backup file, I did big with as much for #1086 
2. Start the recovery process with the image
3. On embassy notifications after the recovery we get the seen notification for bitcoind

**Comment by dr-bonez** [comment]
Unable to reproduce. Will reopen if additional reports.

**Comment by ProofOfKeags** [comment]
I'll try to repro. If I cannot I'll close as ghost.

**Comment by ProofOfKeags** [comment]
Wait. What were you backing up if you were backing it up to a thumb drive?

**Comment by Blu-J** [comment]
https://www.amazon.com/SanDisk-Ultra-Flair-128GB-Flash/dp/B015CH1PJU/ref=sxin_14_ac_d_bv?ac_md=0-0-QmVzdCBWYWx1ZQ%3D%3D-ac_d_bv_bv_bv&crid=F57T3XW5MX3W&cv_ct_cx=sandisk&keywords=sandisk&pd_rd_i=B015CH1PJU&pd_rd_r=9d76e9b7-943c-40e6-8b57-313a0ac1d207&pd_rd_w=MU3Vh&pd_rd_wg=AuCJK&pf_rd_p=f77357a4-3bc9-48f9-a560-10a39068cae9&pf_rd_r=4A2F9KT246E0R880J7CQ&qid=1645211066&sprefix=sandisk%2Caps%2C106&sr=1-1-f4ff053e-b1e8-4d31-8f95-56d755c862ba&th=1

And 

https://www.amazon.com/Sabrent-EC-NVME-Aluminum-Enclosure-Nvme/dp/B07K4TZQ7D/ref=sr_1_27?crid=2JCMZG06CLTLG&keywords=sabrent&qid=1645211132&s=electronics&sprefix=sabrent%2Celectronics%2C97&sr=1-27

**Comment by ProofOfKeags** [comment]
no like...what data is fitting onto the 128G? it sure as hell isn't a full archive.

**Comment by Blu-J** [comment]
Don't believe that I have a full archive complete anything so the size wasn't an issue at the time.
Also this is only a backup.


Also: Using the following hub
https://www.amazon.com/j5create-USB3-0-SuperSpeed-7-port-JUH377/dp/B01AS1Y3G2/

**Comment by ProofOfKeags** [comment]
I cannot reproduce this. However I only tried to via CIFS. that seems to suggest that the issue is with the physical media backups. I will try that next.

**Comment by dr-bonez** [comment]
current theory is that it might have something to do with trying to backup to vfat. testing that theory now...

**Comment by ProofOfKeags** [comment]
What should I be doing about this right now @dr-bonez ?

**Comment by dr-bonez** [comment]
If you want to test backing up to a fat32 drive that would help

**Comment by ProofOfKeags** [comment]
I successfully verified that fat32 drives could be used as backups and restores for bitcoind. Some changes were needed to support that but this is complete.
