### ISSUE TITLE
[bug]: Recovery Lost page

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1226]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Current Behavior

After the recovery finishes, we get no beep

Setup complete page has everything but all the tor and local are nothing.

![image](https://user-images.githubusercontent.com/2364004/154378181-a8d97a37-e1a4-4995-ab62-7df61e1bd570.png)

### Expected Behavior

Be something there and beeped.

### Steps to Reproduce

1. Create a backup file, I did big with as much for #1086 
2. Start the recovery process with the image
3. Drop the page in the browser
4. Go back into embassy.local and re- enter the product key
5. Let the System finish

###  Work Around

1. Hard reboot
2.  Recovery
3. Recover the hd (Or start again)

**Comment by MattDHill** [comment]
If this is real, it is a massive P1

**Comment by Blu-J** [comment]
Still saw it yesterday with Aiden.

**Comment by MattDHill** [comment]
Closed in favor of [#1288](https://github.com/Start9Labs/embassy-os/issues/1288)
