### ISSUE TITLE
[feat]: joinmarket webui

### ISSUE THREAD

**Issue by secondl1ght** [Start9Labs/embassy-os#1237]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

There is a currently a joinmarket web interface in development here: https://github.com/joinmarket-webui/joinmarket-webui it would be great if users of Start9 could have easy access to a coinjoin implementation like this!

### Describe the Use Case

Currently I am not aware of any coinjoin implementations made available to Start9 users. joinmarket is solid software and the new webui makes it easy for users to enhance the privacy of their UTXOs or earn a yield on their bitcoin by being market makers. I think this would be an attractive application for Start9 users to have available in the marketplace.

### Anything else?

Please let me know if you need any more information on this, I am contributing to the project and can put you in contact with the lead maintainers to coordinate if needed.

**Comment by kn0wmad** [comment]
You may also like to add this to the unofficial community wish list at https://s9.altweb.me/

It is already on our internal wishlist.  We will be adding more Bitcoin privacy tools this year

**Comment by MattDHill** [comment]
Given this is not an OS feature or bug, closing in favor of listing on https://s9.altweb.me/.

**Comment by dergigi** [comment]
Listed. https://s9.altweb.me/posts/67/add-jam-for-joinmarket

**Comment by kn0wmad** [comment]
@dergigi You'll be happy to know someone is investigating this https://github.com/cryptodread/joinmarket-webui-wrapper :)
