### ISSUE TITLE
Add textarea boolean to string config spec

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/embassy-os#1239]
ConfigSpecString should now have a boolean called textarea that allows a user to indicate if they want their string input to be a textarea

IMPORTANT:  Masked: true does not affect a text area on the FE, so saying masked:true, textarea: true is misleading because the words will always appear in a textarea

**Comment by MattDHill** [comment]
strings are <input> elements. <textarea> elements are expandable/resizable, better for paragraph entry.
