### ISSUE TITLE
[feat]: Allow service developers to add a lightning address to the 'Donate' functionality

### ISSUE THREAD

**Issue by cryptodread** [Start9Labs/embassy-os#1243]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

In addition to a hyperlink, 3rd party app developers can add a lightning address to the donate section.

### Describe the Use Case

Allow donors to pay 3rd party app developers directly via lightning from inside EmbassyOS. 

### Describe Preferred Solution

When creating a service package, in the manifest.yaml there would be an option to include 
donation-lightning-address: "jimbo3rdpartydev@lightningaddress.com" instead of 
donation-url: "https://3rdpartyapp.com/donate"

This additional option will allow the donor to open a lightning address enabled wallet and pay the developer directly.

**Comment by ProofOfKeags** [comment]
Maybe this could be generalized to extra manifest keys. If we put anything bitcoin related directly into the manifest it definitely ties the OS to bitcoin in a strictly tighter way than it is today. While I prefer Bitcoin to other means of donations, and would like to make it more user friendly to do so, we need to be careful about how much we make Bitcoin a dependency of the OS. right now the OS stands alone.

**Comment by MattDHill** [comment]
The "donations" feature has a highly uncertain future for a few reasons: (1) who should be the receiving party? The upstream service developers or the package developers? (2) if we are facilitating the donation, we have a degree of liability to ensure it arrives at its destination, which we cannot possibly do.

The current donation approach strikes a good balance by navigating the user to a third party page where they can decide for themselves if and how they want to make a donation. Until we understand the problem better, I don't think we should make any changes at the present time.

**Comment by chrisguida** [comment]
I think it would be valuable to design the successor to this feature at some point before 0.4. Lightning donations would be awesome, if we could get them working somehow.
