### ISSUE TITLE
[feat]: Display Tor address on LAN setup page when accessed over LAN

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1277]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

I have to go find my Tor address whenever I want to download my Root CA. Why? It should just display on this page:

<img width="1138" alt="Screen Shot 2022-02-25 at 3 07 29 PM" src="https://user-images.githubusercontent.com/7445670/155804098-84a4695c-ae6c-404f-8821-b5689bf4c6ab.png">

### Describe the Use Case

Eases the already frustrating experience of installing root CAs

### Describe Preferred Solution

Tor address should display on the LAN setup page.

### Describe Alternatives

Alternatively, could display a *link* to the Tor address in the About section

**Comment by elvece** [comment]
I think it was for security reasons that we initially suggested to only download the cert over Tor, remind me why @dr-bonez . If there isn't a significant attack vector / value of doing this, then I agree it would be useful to display on this page.

**Comment by dr-bonez** [comment]
If they are accessing on lan, it's probably an insecure connection if they've not downloaded the CA yet. But that also means they've sent their master password over an insecure connection anyway so I'm not sure how much it matters.

**Comment by chrisguida** [comment]
Right, and the requested feature is not that we allow downloading of cert over LAN, just that we make it easier to find the Tor address from this page.

**Comment by ProofOfKeags** [comment]
> For security reasons you must set up LAN over a Tor connection. Please navigate to your Embassy Tor address and try again.

For security reasons you must set up LAN over a [Tor connection](torproject.org). ~~Please navigate to your Embassy Tor address and try again.~~

**Comment by chrisguida** [comment]
I'm for it

**Comment by elvece** [comment]
> Right, and the requested feature is not that we allow downloading of cert over LAN, just that we make it easier to find the Tor address from this page.

Whoops, I left misunderstood the original ask 😅 

For sure to all of this.
