### ISSUE TITLE
[bug]: no Marketplace after fresh install

### ISSUE THREAD

**Issue by lvlouro** [Start9Labs/embassy-os#1285]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0 - hash 840fa8d49b06b7b34de021857097b49bb47faf63

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 20.04 LTS

### Browser

Firefox

### Browser Version

97

### Current Behavior

After fresh install clicking on marketplace returns an error "this.marketplace is undefined"

When checking in Embassy>Marketplace settings there is no record

### Expected Behavior

There should be a defined marketplace

### Steps to Reproduce

1. Start fresh embassy
2. click on marketplace
3. see error

### Anything else?

I added https://beta-registry-0-3.start9labs.com and installed services successfully

After reboot there is no record of any registry on the marketplace settings although I can install new services

**Comment by dr-bonez** [comment]
this is due to the prod registry not being up when you built this.

this is now fixed
