### ISSUE TITLE
[refactor]: Modify APIs of patch-db to minimize non-canonical ordering issues without hyper-aggressive locking

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1304]
## Motivation

The current behavior of using patch-db locking to manage concurrency across tasks. This is hyper aggressive, and full of danger of deadlocks.

## Proposed Solution

Modify the API of patch-db to take all locks as a single batch request. it should not be able to acquire new locks until it drops all locks that it has.

**Comment by ProofOfKeags** [comment]
Investigate possibility of using predicate filters and how it maps onto data tree cardinality changes.
