### ISSUE TITLE
[feat]: Display when registry 401 is because of faulty internet

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/embassy-os#1305]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Customize an error message so the user can know the connectivity issue is with their embassy rather than the registry.

### Describe the Use Case

When the embassy cannot connect to the registry, the embassy could ping something else to determine if the issues are with internet connection

### Describe Preferred Solution

maybe have a variable in patch db that communicates to the FE whether its online, and then have the FE display a dialogue when its offline.

### Describe Alternatives

Not sure

**Comment by ProofOfKeags** [comment]
We should never have 401's as a result of faulty internet. How is this presenting?

**Comment by MattDHill** [comment]
Not sure what this has to do with 401. But we have already considered using alternative websites to ping if BE is unreachable, and we dismissed it for privacy considerations. Unfortunately I think this is something we will just need to live with.

**Comment by ProofOfKeags** [comment]
To be clear, this was in response to the demo uncertainty that @MattDHill and @cryptodread experienced where the marketplace appeared to be "down" because the internet was out. We can leave it as is, but I'm not sure what the main privacy issue would be in this case.

**Comment by chrisguida** [comment]
Could reach out to a known Tor service
