### ISSUE TITLE
[feat]: SSH keys should go to start9 user (not root)

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#1306]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Right now if you want to add SSH keys to your Embassy those keys are for root account. I suggest changing this to non-root `start9` user account.

### Describe the Use Case

Using root account is not a good practice security wise. The less we depend on `root` account the more secure the system will become.
Also longing as `start9@embassy-q1w2e3.local` looks cool.

### Describe Preferred Solution

Just add keys to /home/start9/.ssh/authorized_keys and disable root login via ssh.

### Describe Alternatives

none

### Anything else?

Elevate `start9` user permissions to use tools like embassy-cli, docker etc.

**Comment by ProofOfKeags** [comment]
[Relevant Code](https://github.com/Start9Labs/embassy-os/blob/master/backend/src/ssh.rs) for anyone who wants to try and tackle this.

**Comment by k0gen** [comment]
Thanks. I'll take it from here.

**Comment by k0gen** [comment]
> [Relevant Code](https://github.com/Start9Labs/embassy-os/blob/master/backend/src/ssh.rs) for anyone who wants to try and tackle this.

[Work in progress ...](https://github.com/k0gen/embassy-os/commits/patch-1)
Should `backend/copy.sh` also be addressed regarding the ssh keys for start9 user?

**Comment by dr-bonez** [comment]
That's a utility script that @elvece uses, I think. It's not part of the mainline development flow for embassyos

**Comment by elvece** [comment]
Apologies, I am unfamiliar with that script. It's either a relic from a prior version of a build script, or an old utility for development purposes. I do not think it is used or needed any longer.

**Comment by ProofOfKeags** [comment]
@k0gen feel free to delete that script as part of this PR.

**Comment by k0gen** [comment]
Done.
