### ISSUE TITLE
[bug]: Generalize copy in config save to account for new and updated services.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1307]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

When migrating a service, you are advised that the default config can/will be used. In reality it will use the config that you had set up prior to migration.

We also need to account for the situation where an app is updated, as opposed to migrated.

### Expected Behavior

A more accurate description of what is being offered.

### Steps to Reproduce

migrate/update a service

**Comment by ProofOfKeags** [comment]
This is referring to the help text in the OS migration flow, I think.

**Comment by dr-bonez** [comment]
the help text of the config dialog when in `needs config` state

**Comment by chrisguida** [comment]
Where was this fixed?
