### ISSUE TITLE
[feat]: Add external disk usage stats in the Monitor page

### ISSUE THREAD

**Issue by maupet** [Start9Labs/embassy-os#1308]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

The Monitor section already contains a Disk section, but that is reporting only about the SD card as of 0.3.0.
It would be useful to add the same statistics also for the external SSD drive.
Additionally, it would also be useful to break down the used space by service.

### Describe the Use Case

It will make it easy to assess how much space your service are taking up

### Describe Preferred Solution

Add a section for external disk usage to the Monitor page.
Preferably add a breakdown of disk usage by service too.

### Describe Alternatives

Add a section on each individual Service Properties page showing the disk space used.

**Comment by kn0wmad** [comment]
The bottom section of the Monitor page is your SSD usage, not SD Card

![image](https://user-images.githubusercontent.com/39687477/156892443-f953c6c0-11da-43fc-8800-42c09b9048ea.png)
