### ISSUE TITLE
"View in Marketplace" button should be disabled if marketplace-url does not exist

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#1324]
With multiple marketplaces, we need to honor the marketplace-url stored on the installed package before navigating to the marketplace.

**Comment by elvece** [comment]
On service show page when a service is installed, "Marketplace" menu button should now:

- check patch-db to see what marketplace UI is connected to
- do a diff with `pacakge-data.<pacakge-id>.installed.marketplace-url` and the current value fetched from patch-db
- if different, present a modal with warning message to user that they will need to switch to the original marketplace of the installed package. Add a button to this modal entitled "Switch" that will take the user to `Embassy > Marketplace Settings`.

**Comment by elvece** [comment]
If the marketplace url does not appear at `pacakge-data.<pacakge-id>.installed.marketplace-url`, then the package was side-loaded and this button should be disabled.

Also, add descriptive text, such as: "This package has been side-loaded and is not available in the Start9 Marketplace"

**Comment by elvece** [comment]
Related: https://github.com/Start9Labs/embassy-os/issues/1247

This bug will be resolved by this feature.

**Comment by BBlackwo** [comment]
Btw, @elvece, I noticed the original intent of this issue was to use the `marketplace-url` in case the package was installed from an alternative marketplace. Is that no longer desired, or will it be done in a separate issue?

**Comment by elvece** [comment]
> Btw, @elvece, I noticed the original intent of this issue was to use the `marketplace-url` to navigate, in case the package was installed from an alternative marketplace. Is that no longer desired, or will it be done in a separate issue?

Good catch, what we actually want to do is, in the event that the marketplace-url of the package differs from the currently connected marketplace, pop an alert mentioning this discrepancy. In the alert, include a link to the embassy > marketplaces tab so the user could switch marketplaces, if desired.
