### ISSUE TITLE
[feat]: display CA cert fingerprint in the ui

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1329]
this is useful in determining which cert is which when you have multiple embassy cas installed

**Comment by chrisguida** [comment]
Example of this using `openssl` https://github.com/Start9Labs/synapse-wrapper/blob/e3067f821379a29ca6fba8e44cb8422cb2231524/configurator.py#L55

**Comment by elvece** [comment]
Add to about section
