### ISSUE TITLE
[bug]: SSL for tor

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1331]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

?

### Browser

Brave + TorBrowser

### Browser Version

V1.36.112

### Current Behavior

Our current brochure tor does not support https and defaults to http
![image](https://user-images.githubusercontent.com/2364004/158238378-c0bc63db-61fa-4840-acf4-741b5393bcd7.png)
![image](https://user-images.githubusercontent.com/2364004/158238192-28bffa0f-b1dc-4639-b5a1-945c6186d85e.png)
Notice the 404 and not secure tabs

Below is an example that works
![image](https://user-images.githubusercontent.com/2364004/158238242-944cc59e-d6cf-4d3b-90dc-f5c81da05457.png)

And this is needed for the web app to work with 
![image](https://user-images.githubusercontent.com/2364004/158238272-ff708ad6-5850-463d-9529-1c1194aaa89f.png)

### Expected Behavior

Making tor work, and the certificate to not warn would be great but is this possible. Could I get this for all tor routes please?

### Steps to Reproduce

Go to 

t4imfm56resxwanudhhmpvb5xorx46lde64r3cjrvtrv5a4ogbzmlxqd.onion/#/
privacy34kn4ez3y3nijweec6w4g54i3g54sdv7r5mr6soma3w4begyd.onion//latest/

**Comment by ProofOfKeags** [comment]
The tor team has specifically requested that people don't normalize certificate use with onion addresses. I actually decreases security when analyzed from a holistic perspective. This is a bug in the browser.

**Comment by chrisguida** [comment]
Ftr we do use SSL over Tor on Synapse, because it literally doesn't work otherwise. We could implement this on VW.

**Comment by dr-bonez** [comment]
Yeah, so I think this is not worth an OS feature, but we may want to consider enabling ssl for the main embassy ui.

**Comment by MattDHill** [comment]
closing in favor of #1568
