### ISSUE TITLE
[feat]: Allow the user to disable health checks globally

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1343]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Either in the UI or CLI, add a setting that allows the user to disable health checks globally

### Describe the Use Case

Health checks use a lot of resources and I suspect that they slow things down a lot, particularly on boxes running lots of services. This will both help determine what impact they are having, and also mitigate their effects if the user has something time-sensitive to get done.

### Describe Preferred Solution

A setting in the database, or in a file, that disables all health checks.

### Describe Alternatives

None

**Comment by dr-bonez** [comment]
I can add a compiler flag for this, but it is not worth building a ui flow.

**Comment by ProofOfKeags** [comment]
Disabling it should not "hold" healthcheck state though, maybe add a new status "disabled" to the state set? or hijack an existing one if there's a sensible option.

**Comment by dr-bonez** [comment]
if this was ever going out to users, I'd agree. This is really just to prove out whether or not health checks are "causing problems"

**Comment by ProofOfKeags** [comment]
Yes, but the last thing we want is our own devs drawing the wrong conclusions because they forgot they left this setting set one way or another and proceeded to understand health check state as normal.

**Comment by chrisguida** [comment]
It will also allow us to gather detailed performance data on health checks.

**Comment by elvece** [comment]
In favor of https://github.com/Start9Labs/embassy-os/issues/2055
