### ISSUE TITLE
[feat]: Adjust setup wizard for Embassy Pro

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1352]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Make adjustments to the setup wizard flow to enable the Embassy Pro. Specific details to follow @dr-bonez 

Also update styling - remove white and increase logo size (suggestion from designer)

### Describe the Use Case

Enable setting up the Embassy Pro via the setup wizard.

**Comment by chrisguida** [comment]
For reference, this is how it looks now

<img width="660" alt="Screen Shot 2022-03-24 at 10 06 26 AM" src="https://user-images.githubusercontent.com/7445670/159960014-4ad3ad2d-8e0c-4e45-a9ac-575699d85259.png">

**Comment by elvece** [comment]
Add option to migrate data from a previous drive
