### ISSUE TITLE
[bug]: Password validation fails first time when creating/restoring backup.

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#1364]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Catalina

### Browser

Firefox

### Browser Version

96.0.3

### Current Behavior

Entering your master password fails on first attempt when (1) creating a new backup on top of an existing one or (2) restoring from backup. It always works on the 2nd attempt.

### Expected Behavior

Should work on first try if correct

### Steps to Reproduce

1. create a backup.
2. attempt to restore.
3. notice password appears to be invalid.
4. try again.
5. notice it works.

**Comment by dr-bonez** [comment]
pretty sure password validation is handled on the frontend, so that's where I'd start the investigation. see what changes between the attempts.
