### ISSUE TITLE
[feat]: Allow some services to skip "needs config" on reinstall

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1365]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Allow some services to skip the "needs config" state on reinstall/update. There are several potential ways to accomplish this.

### Describe the Use Case

When a service's config doesn't need to be changed, it's burdensome to have to save the config on every update, especially on services like proxy which take a long time to configure, and especially during development where saving the config is the vast majority of the build/deploy/run cycle.

So the idea here is to detect the cases when a service's config does not need to be updated, and in those cases simply perform the update and skip the config step.

### Describe Preferred Solution

Preferably the OS would default the service to configured immediately after update unless a migration is defined. 

In some cases we may want to define a migration as `configured: false` to force re-evaluation of the config, in cases where new config keys were added and we would like the user to have the option of using the new keys. 

There are also cases where the new config is incompatible with the old config, but simply saving the config again will clear this up. According to @elvece the next version of btcpay falls into this category.

In both cases we can define the migration as `configured: false` going forward.

### Describe Alternatives

We could also have the OS detect when the migration is a "self-migration" (that is, migrating to the same version, as most development migrations are) and automatically assuming no migration is needed in this case, unless a migration is defined.

So, the two options I currently see for this feature would be either treating all migrations the same, as above, or treating self-migrations differently, at the OS level. In either case, the service's manifest could override the default in the OS.

EDIT: We could also simply enable a service developer to manually flip a service to configured. This doesn't solve every case, but it solves the most painful case.

**Comment by ProofOfKeags** [comment]
That's not true though. The assumption is that the config + the defaults for the new config options work if there's no migration but you still want the user to co-sign things that are in the defaults. Additionally, pointers are resolved during the config process and there's no sensible way to resolve those in the migration, so any new pointers that are added in a service update need to be re-resolved.

**Comment by chrisguida** [comment]
Ok, in that case it sounds like just requiring a simple migration of `echo '{"configured": true }'` on self-migrations is the preferred solution to this issue.

**Comment by ProofOfKeags** [comment]
wait hold on are you saying you want this *only* for x.y.z -> x.y.z? if so I'm not sure migrations make any sense, plus the only reason for reinstalls is if we *change* something which implies the config spec might change.

**Comment by chrisguida** [comment]
Yes, that's what I mean by "self-migration"

**Comment by chrisguida** [comment]
Agreed, that's why I originally opened this issue

**Comment by ProofOfKeags** [comment]
The only thing I can think of to accomplish what you want is diffing the config.get action before and after reinstall. If they are the same, then the config is guaranteed to satisfy them both equally. Alternatively we can check if the config (as is) satisfies the new spec (even on update) and only require config if it doesn't pass.

**Comment by chrisguida** [comment]
Assuming the config is stored in embassy.db, this should be easily doable

**Comment by chrisguida** [comment]
I believe the resolution to this issue is that the burden of deciding whether or not a needs config is required is on the package dev rather than the OS. So, a null migration must be explicitly implemented in the case where no reconfiguration is required, such as in the case of self-migrations and upgrades with no changes to the config.

@MattDHill Can you please mark the resolution of issues when you close? It drives me nuts to see old issues where a thoughtful discussion takes place but are subsequently closed without any kind of resolution.
