### ISSUE TITLE
[bug]: UI events firing twice

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1391]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.16

### Browser

Firefox

### Browser Version

99

### Current Behavior

Clicking on 'Save' in Config or 'Update' during a service update causes a UI event to 'fire' twice

### Expected Behavior

UI event only fires once

### Steps to Reproduce

1. On Config or during a service update, click 'Save' or 'Update'
2. See bug

**Comment by conradcreel** [comment]
![btcpay_upgrade_error](https://user-images.githubusercontent.com/11894183/163052664-4469a1a0-2f3f-4e40-859c-344a5fd5f9db.png)

This error might be related. Using Chrome on Ubuntu 21.10; Occurred when I upgraded from BTCPayServer 1.1.2 to 1.4.7 using the beta marketplace. I didn't stop BTCPayServer previously. However, it appears to be only UI as the updated BTCPayServer is working just fine

**Comment by ProofOfKeags** [comment]
Yeah it's definitely related.

**Comment by elvece** [comment]
Vigorously attempted to reproduce unsuccessfully @34068ef6339b4b5a95301fcc0e71f5ad69b14c45.

Possibly fixed by https://github.com/Start9Labs/embassy-os/pull/1412 or https://github.com/Start9Labs/embassy-os/releases/tag/v0.3.0.3

Closing as ghost until reproducible again with more information.

**Comment by chrisguida** [comment]
To clarify, did you try similar testing on a known broken version of eOS? This happens to me maybe 1 out of every 3 installs
