### ISSUE TITLE
"bep" noise after EOS download complete

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#1393]
When updating from 0.3.0.1 to 0.3.0.2, Embassy made a "bep" noise when the download completed. Everything appeared as expected in the UI, Embassy did *not* restart or lose connectivity. Are we intentionally playing a bep noise on download complete, or did some other process accidentally run?

**Comment by dr-bonez** [comment]
we are intentionally doing so, though I personally think it is very odd. Very open to suggestions for alternatives.

**Comment by ProofOfKeags** [comment]
I thought it was a triple bep, but yes this was a design choice, we can do something else instead. We can change it to whatever.

**Comment by dr-bonez** [comment]
the triple bep is so fast it sounds like one

**Comment by ProofOfKeags** [comment]
We can drop the tempo down substantially, or insert rests between them. But @MattDHill suggested a jingle. I might sub it out for a circle of fourths or circle of fifths voicing.
