### ISSUE TITLE
[bug]: Toast asks to restart after OTA has already been applied

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1395]
Steps to recreate:

1. Do OTA update
2. click "restart" on toast once update is downloaded
3. wait for embassy to come back up
4. See toast identical to the first asking for restart again, after restart has already happened:

<img width="767" alt="Screen Shot 2022-04-13 at 10 07 22 AM" src="https://user-images.githubusercontent.com/7445670/163211783-5174e191-87d1-4242-ac38-d2516f4a2540.png">

**Comment by elvece** [comment]
Issue is that, when restarted, the patch describes `updated: false`, but then a patch comes in after the restart with `updated:true` _after_ the component loads.

Possible solution: wait to make that evaluation until synced with patchdb at least once before page is loaded
