### ISSUE TITLE
Memory Usage stats on Pi are misleading

### ISSUE THREAD

**Issue by rytido** [Start9Labs/embassy-os#140]
Done: Metrics correctly represent memory usage on Pi
Effort: 1 day (Keagan)
Dependencies: None

On the metrics page Embassy is showing incorrect memory stats. I believe it’s specifically the free memory that is incorrect. I suspect this has to do with running on an 8GB Pi instead of the recommended 4GB. A screenshot suffices to reveal the inconsistency:
![A72ABF0C-1780-4255-B730-3375F16F124E](https://user-images.githubusercontent.com/7735281/104399571-f0aa3b00-551e-11eb-9dde-f50064a8f051.jpeg)

**Comment by ProofOfKeags** [comment]
Interesting find. I'm seeing it here on the 4GB one as well. Not sure what's going on. We grab the stats from `top` originally. So maybe it's an issue with how we are parsing the output. I'll look into what might cause it. The relevant code is [here](https://github.com/Start9Labs/embassy-os/blob/master/agent/src/Lib/External/Metrics/Top.hs).

**Comment by ProofOfKeags** [comment]
Looks like we are using "free" from top when we should be using "available". The distinction is whether or not imminently reclaimable kernel buffers from disk reads and disk writes are to be included or not.

[citation](https://unix.stackexchange.com/questions/390518/what-do-the-buff-cache-and-avail-mem-fields-in-top-mean)

**Comment by k0gen** [comment]
Actually this is correct but a little bit misleading, there was a little lag but the values are correct  look:
<img width="776" alt="Zrzut ekranu 2021-02-26 o 17 05 19" src="https://user-images.githubusercontent.com/3606313/109324559-1da77880-7855-11eb-96be-1fad475c8cec.png">

**Comment by ProofOfKeags** [comment]
This will have to be fixed as part of the 0.3.0 upgrade in appmgr. This functionality used to exist in the agent but since the agent is retired in 0.3.0, it needs to be reimplemented in appmgr. Assigning to @dr-bonez
