### ISSUE TITLE
[bug]: Service update tab does not indicate "update available" tag on services

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1404]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.2

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.16

### Browser

Firefox

### Browser Version

99

### Current Behavior

Update tab shows green "Installed" badge, instead of yellow "Update available" tag

### Expected Behavior

Show tag as described above

### Steps to Reproduce

1. Updates tab in Marketplace
2. View a service with an update

**Comment by kn0wmad** [comment]
![image](https://user-images.githubusercontent.com/39687477/166803645-934c8793-4d85-4042-b56a-7a8a26f0086e.png)

**Comment by elvece** [comment]
This is a bug that needs investigation.

This is [related](https://github.com/Start9Labs/embassy-os/issues/1425) wrt needing better copy. These two issues can likely be resolved together.

**Comment by ProofOfKeags** [comment]
CC @MattDHill for reprioritization

**Comment by varacohete** [comment]
Ditto on this issue, I have been running an old version of LND as I missed this upgrade due to misreading the update page: I understood "installed" to mean that I had the most recent version

**Comment by ProofOfKeags** [comment]
> Ditto on this issue, I have been running an old version of LND as I missed this upgrade due to misreading the update page: I understood "installed" to mean that I had the most recent version

This is reasonable as older versions of EmbassyOS did inform when updates were available on the marketplace. At some point a refactor introduced this bug, and it should be relatively easy to sort out.

**Comment by MattDHill** [comment]
Moving to 0.3.1 and assigning to self.
