### ISSUE TITLE
[bug]: LND: "lnd  Failed: Can't do backup because service is in a backing up state"

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1406]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0~2

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

99.0.1

### Current Behavior

![Uploading Screen Shot 2022-04-16 at 8.30.06 AM.png…]()

### Expected Behavior

successful backup (all other services backed up correctly)

### Steps to Reproduce

Do a backup - sorry to not be more verbose.

**Comment by BitcoinMechanic** [comment]
LND was stuck "backing up" even after backup completed. A restart fixed this and then I was able to fully backup everything, including LND.

**Comment by chrisguida** [comment]
You should upload the actual screenshot

**Comment by ProofOfKeags** [comment]
Are you sure this isn't the "double click" issue?

**Comment by BitcoinMechanic** [comment]
@chrisguida I don't have one, sorry.

@ProofOfKeags I don't know.

**Comment by chrisguida** [comment]
Just noticing that there seems to be a broken reference to a screenshot

**Comment by BitcoinMechanic** [comment]
Yes good point. Sorry - unreliable internet must have chosen that exact point to have a hiccup. I no longer have it to upload.

**Comment by dr-bonez** [comment]
closing for not enough information
