### ISSUE TITLE
[feat]: When asking for password to initiate back up, password appears in plain text.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1407]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Typed test should appear as stars/dots not plain text.

### Describe the Use Case

Entering password to initiate a back up.

**Comment by ProofOfKeags** [comment]
This was done to avoid Bitwarden prompting overrides when the current and previous passwords diverge. This isn't a bug, but the plan as I remember it is to add a special CSS class that will render things differently.

**Comment by kn0wmad** [comment]
Can this be done globally for passwords in the UI?  I encounter both masked and clear passwords and ideally it would be uniform

**Comment by elvece** [comment]
> 

Yes - this will be done for all passwords - it will be uniform. Closing in favor of original [ticket](https://github.com/Start9Labs/embassy-os/issues/1370) and increasing priority on that ticket.
