### ISSUE TITLE
[feat]: Add "Last Updated" date to services

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1409]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

On a service's marketplace page, add the Last Updated date

### Describe the Use Case

Shows "current-ness" of a service, which may affect a user's desire to install.  e.g., how well maintained is this particular package?  This is done in many modern digital marketplaces

**Comment by elvece** [comment]
Would this correlate to the version release date? And would that be of the of the upstream service version release date, or that of the latest release to the marketplace? The latter might be more accurate for updates related to EOS, but might not provide any notion of the upstream service's updates. 

Some packages, like bitcoin or lnd, do not have new version releases very frequently, but they are very much in active development. I'm not sure this is the most valuable metric in this case.

I agree that it would be nice to have some notion of when the service was last published to the marketplace (we actually do have this persisted so I think this as a solution would be straightforward), but I'm just not certain this is the best metric for a project's state of activity. Last commit would probably be most pertinent.

**Comment by kn0wmad** [comment]
Last commit would be useful, although not to a 'typical' user.  Perhaps dates for both upstream service and package wrapper would be appropriate in future.  Obviously this is ultra low priority feature

**Comment by ProofOfKeags** [comment]
EmbassyOS isn't commit-aware for packages.

**Comment by elvece** [comment]
How I envision this at the moment is like so:

- return the `updated_at` column as part of the registry response for a package's versions
- using this field for the latest version, add a section in the marketplace UI to display this data, something like:
<img width="1389" alt="Screen Shot 2022-04-29 at 12 24 48 PM" src="https://user-images.githubusercontent.com/12953208/166004208-2d86ae93-c28f-45b4-a3e6-074506c62e9b.png">

**Comment by ProofOfKeags** [comment]
> could add the commit to the manifest, though that would be a chore to implement on all services.

This would create a hash cycle and thus is not possible. The act of committing the change with the commit hash will change the commit hash.

**Comment by chrisguida** [comment]
Oh, true, my bad xD

**Comment by MattDHill** [comment]
Closed by #1689
