### ISSUE TITLE
[bug]: Backups hanging indefinitely, hard reset leads to brick

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1411]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.2

### Device

Laptop/Desktop

### Device OS

Windows

### Device OS Version

11

### Browser

Firefox

### Browser Version

99

### Current Behavior

Attempt backup, backup hangs on Mastodon and crashes Embassy

User did a hard reset at this point to try to remedy, this resulted in *bep/beethoven* and the user re-flashed to fix

### Expected Behavior

Backup does not hang indefinitely

### Steps to Reproduce

1. Perform backup
2. Hang occurs

### Anything else?

Ability to cancel backup would be an MVP remedy

**Comment by kn0wmad** [comment]
Logs from Diag:

![image](https://user-images.githubusercontent.com/39687477/164728934-c4dcb31a-64bc-40a8-9ae4-6ee86aad3b26.png)

**Comment by dr-bonez** [comment]
Would need to interact directly with this user to dive into what specifically is wrong here, though seems disk i/o related. But backup cancellation is a feature we can add.

**Comment by chrisguida** [comment]
There is already an issue for backup cancellation https://github.com/Start9Labs/embassy-os/issues/1410

**Comment by dr-bonez** [comment]
ok, then will leave this ticket for addressing the backup hanging, but I need more information  before I can proceed.

**Comment by kn0wmad** [comment]
Addressing out of band

**Comment by dr-bonez** [comment]
@kn0wmad any update on this?

**Comment by kn0wmad** [comment]
Waiting on user to test on a different network

**Comment by kn0wmad** [comment]
Never got a response, leave this open or close for now?

**Comment by elvece** [comment]
Likely has to do with locking issues, resolved by #2052
