### ISSUE TITLE
[bug]: Bitcoin Core health checks report "Timed out...." incorrectly

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1413]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.2

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.16

### Browser

Firefox

### Browser Version

99

### Current Behavior

Bitcoin Core health checks both report "Timed out, retrying soon...." despite Logs reporting blocks actively being synced

### Expected Behavior

Health checks should report back correctly

### Steps to Reproduce

1. Time outs occur randomly, but often.  Try a reboot to trigger
2. Go to Bitcoin Core and see Time outs in health checks
3. Check logs to find that Core is in fact syncing (or synced)

**Comment by kn0wmad** [comment]
Alternatively, I have just noticed both health checks go to "green," although the sync was still 100 blocks behind, enough to cause LND to not work

**Comment by ProofOfKeags** [comment]
It is not clear this is an OS bug. It is possible that it is an issue with Bitcoin Core.

**Comment by chrisguida** [comment]
This just means the rpc isn't working. It's actually an accurate message.

**Comment by kn0wmad** [comment]
> This just means the rpc isn't responding within 60 seconds. It's actually an accurate message.

Is it accurate if there is no problem with RPC calls and yet the timeouts are consistently appearing??  I can reopen in Bitcoin wrapper

**Comment by chrisguida** [comment]
This means there *is* a problem with RPC calls. Are you saying you're calling the RPC manually and it's working, but the frontend says it's timing out?

**Comment by kn0wmad** [comment]
I'm saying the Bitcoin logs are humming along fine, receiving calls, not that I'm giving them manually.  Even if it is "working" correctly, which does not seem to be the case, it is still messaged far too aggressively to the user, causing a lot of support load

**Comment by ProofOfKeags** [comment]
This is very unlikely to be an issue with EmbassyOS itself, but rather an issue with the bitcoind package. Perhaps we should consider moving it?

**Comment by chrisguida** [comment]
@kn0wmad the fact that the logs are "humming along" is irrelevant to whether or not the RPC is responding within 60 seconds. Please verify whether the RPC is responding within 60 seconds by calling it manually. If it doesn't respond within 60 seconds, then everything is working as designed.

**Comment by elvece** [comment]
No convinced this is a UI bug. FE simply relays the error from the BE, which relays from the service. Needs more information imo.

**Comment by chrisguida** [comment]
Agreed, pretty sure nothing is wrong here

**Comment by kn0wmad** [comment]
Seems the issue is heavier on the 4G Pi (by my testing), and the only solution is to stop every other service (assuming you want to use a heavy bitcoin stack).  Unfortunate, but perhaps nothing can be done at this time.  Closing as not worthy of dev resources at this time.

**Comment by kn0wmad** [comment]
It is also a duplicate (and in the wrong place)

There was a ticket in the bitcoin wrapper already @ https://github.com/Start9Labs/bitcoind-wrapper/issues/63
