### ISSUE TITLE
Make logs copy-paste friendly

### ISSUE THREAD

**Issue by maupet** [Start9Labs/embassy-os#1416]
Service logs, OS logs and Kernel logs should be easy to copy and paste. Ideally, also to save to a file.
Currently it is not straightforward to copy a log under Windows and Android, because in both environments, the native behavior (right click, select, long tap) is inhibited.
The only way I found is to inspect the window from the browser, and paste the HTML logs code to a new HTML file, then open the resulting file.

**Comment by kn0wmad** [comment]
This is both a bug report and feature request (can split in 2 if necessary)

Right-click works fine in Linux, need to test across all environments for the bug

Adding the ability to save logs to file would be a nice-to-have

**Comment by chrisguida** [comment]
There's already a ticket to download logs to a text file: https://github.com/Start9Labs/embassy-os/issues/1341

**Comment by elvece** [comment]
Closing in favor of https://github.com/Start9Labs/embassy-os/issues/1341.
Noted there to add copy/paste functionality in addition to file download.

**Comment by elvece** [comment]
Actually, reopening this as a single bug report for making sure its copy/pasteable in broken environements (Windows, Android).
