### ISSUE TITLE
Mask the backup password

### ISSUE THREAD

**Issue by maupet** [Start9Labs/embassy-os#1417]
Currently the backup password is visible to the user as it is input (both at backup and at restore).
The field should mask the password with asterisks.

**Comment by kn0wmad** [comment]
Closing as duplicate of #1370

**Comment by elvece** [comment]
Reopening to track resolving one of the two components needed to reimplement masking securely.

The second component is addressed [here](https://github.com/Start9Labs/embassy-os/issues/1370).
