### ISSUE TITLE
Switching dependencies in config does not take effect until manual service restart

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#1418]
Observed when switching Mempool config to use Core instead of Proxy as the internal dependency. Upon saving config, Mempool went back into a "Running" state, but it was still using Proxy, despite the UI displaying only a dependency on Core. Mempool continued to spam Proxy logs despite being configured to use Core directly. Restarting Mempool resolves the issue.

Concern here is that saving config appears to have not restarted the service. If this is a universal behavior, it would mean that no config changes are not taking effect until the user manually restarts a service.

**Comment by dr-bonez** [comment]
The OS typically fires a SIGTERM to the service after config is saved. But it's actually up to the service how to handle that SIGTERM, or it can even ask for a different signal. I suspect this is an issue with mempool specifically not responding to SIGTERM.

**Comment by ProofOfKeags** [comment]
We can't solely depend on services to be good citizens and always respond to SIGTERM. Do we fire a SIGKILL on a timeout in this situation? If not, we should be.

**Comment by dr-bonez** [comment]
> We can't solely depend on services to be good citizens and always respond to SIGTERM. Do we fire a SIGKILL on a timeout in this situation? If not, we should be.

I disagree. If the service needs a sigkill, it can ask for a sigkill. This situation does not have the same consequences as a failed stop - it will not leave the os in a bad state or prevent you from uninstalling / updating. I feel like responding properly to sigterm is table stakes for a service to have a positive UX.

**Comment by ProofOfKeags** [comment]
What you're saying here is that the OS doesn't guarantee that saving the config is guaranteed to take effect. I would bet fairly strongly that this will be surprising to users. Explaining to users that a "SIGTERM is sent to the process and if it chooses to ignore it, then the config won't be updated", is going to not be well-understood.

**Comment by chrisguida** [comment]
Yeah, seems like the OS should handle malformed packages. Obviously the package should be fixed too
