### ISSUE TITLE
[bug] Unclear if service update avaiable

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1425]
On the marketplace service show page, it is unclear what version of the service is available for update. In other words, it's unclear what version of the service is installed, and what version is available to update to.

![Screenshot from 2022-05-03 14-45-40](https://user-images.githubusercontent.com/12953208/166809782-24f5b775-53ff-4ecc-91b2-d90cfaaed4a8.png)
![Screenshot from 2022-05-03 14-45-53](https://user-images.githubusercontent.com/12953208/166809785-28ff2bb5-4f9f-489a-aa74-a499a8bee1f8.png)

Proposed solution(s):

- [ ] Update the text to `Installed at 2.1.5~4`, maybe make it yellow if theres an update available.
- [ ] Make update button yellow
- [ ] Maybe say `Latest version: 2.2.7` where version is

**Comment by MattDHill** [comment]
#1404 improves messaging to indicate there is an update available.

<img width="1282" alt="Screen Shot 2022-06-04 at 8 09 50 PM" src="https://user-images.githubusercontent.com/9935159/172031952-543b4381-05fc-4c08-811c-918de674d699.png">

I'm not convinced there is any benefit to seeing the currently installed version on this marketplace page. If the user cares about the current version for some reason, they can view it by clicking the "View Service" button.

Closing.

**Comment by chrisguida** [comment]
The benefit is that it saves a click
