### ISSUE TITLE
[feat]: Dynamic `index.html` Message

### ISSUE THREAD

**Issue by mirkoRainer** [Start9Labs/embassy-os#1431]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Upon initial boot after a build, a loading screen appears and "Please wait several minutes and refresh the page." is displayed on the screen. This was updated  in https://github.com/Start9Labs/embassy-os/pull/1419/files/f948d4d0fa7246eb17b095744bb4ea2023e5ff9b#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051 since the previous message was much too short for an initial boot. Devices that have been booted before do not "load" on this screen for long. A dynamic message based on whether eOS has been booted before or not would be a "better" solution.

### Describe the Use Case

Enabling a dynamic "loading" message can be useful in a number of situations. A couple are listed here but please comment with any more.
1. When building from source, the initial boot can take ~30min or so. A message detecting an initial boot can inform the user of this time.
2. The "loading" screen is up for too long. This might be indicative of a number of issues, but detecting the context of a boot and timing of a boot can help influence user action (or inaction in the case of initial boot)

**Comment by mirkoRainer** [comment]
@elvece Happy for direction for implementation or suggestions.

**Comment by dr-bonez** [comment]
the process of initialization after building from source is a difficult thing to measure and predict. it may be less effort to get an emulated raspberry pi environment running in qemu and perform this work during the build than to implement this

**Comment by MattDHill** [comment]
Will be obviated by init UI
