### ISSUE TITLE
[bug]: Bitcoin price too low

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1432]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0~2

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

99.0.1

### Current Behavior

Price too low

### Expected Behavior

Mewn

### Steps to Reproduce

1. Buy dip
2. Repeat
3. Deny possibility of market downtrend
4. Pain

**Comment by kn0wmad** [comment]
Closing as 1BTC is still 1BTC

Price has not moved and remains stable
