### ISSUE TITLE
[feat]: Update Tor to 4.7

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1433]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Tor has added performance improvements, which would be highly desirable for EOS users

### Describe the Use Case

Self-explanatory

**Comment by ProofOfKeags** [comment]
The overlay system will make this hard to do in an update.

**Comment by dr-bonez** [comment]
We can easily update tor when the system updates by baking the new tor into the new image
