### ISSUE TITLE
Fix UI build to not rebuild every time `make` is invoked if nothing has changed

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#1434]
Right now the UI rebuilds every single time. This shouldn't be the case.

**Comment by elvece** [comment]
Do you always run `make clean` first? Because it will always rebuild the frontend in that case.

Otherwise, curious, afaict the way the Makefile is currently setup, it should only rebuild on changes. 🤔

**Comment by ProofOfKeags** [comment]
> Do you always run make clean first?

No.
