### ISSUE TITLE
[bug]: Embassy takes 12+ hours to connect to the internet (plus Mastodon does not work)

### ISSUE THREAD

**Issue by maupet** [Start9Labs/embassy-os#1443]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.3

### Device

Laptop/Desktop

### Device OS

Windows

### Device OS Version

11

### Browser

Firefox

### Browser Version

100.0 (64-bit)

### Current Behavior

After reboot, it takes 12+ hours for the device to be accessible over TOR (tor browser says that the onion sites are disconnected), and it is basically unable to connect to the internet, and to the backup folders, during this time.

During this time:
- Bitcoin core seems unable to connect to any peers (see logs)
- Mempool crashes because it cannot load an external asset (see logs)
- remote devices cannot connect to Syncthing (see logs)
- ,can't open the Marketplace (see error - appears as I try to open the marketplace).
- Backup folders are also not reachable (see error - appears as I try to reconnect).
- Services work fine, but on LAN only.
- I am unable to get both OS and kernel logs (the UI gets stuck with the spinning wheel), but I can still get individual services logs.

Some additional information for context:

- I had an issue with LND that was unable to unlock the wallet, after restoring it from backup. This issue was solved with LND 0.14.2.1.
- Before the LND fix, backups often took way more than they should (initial full backups did complete in about 7 hours, now some backups take more than double the time for roughly the same data). Now they take less than 1 hour.
- Before the LND fix, sometimes the device got stuck while backing up. When this happens: I can't access any logs; there are networking issues (see below); I have to reset to fix it. Soft does not work under such circumstances, but Hard reset gives me Bep-Beethoven sounds, and then I can reset successfully only via the Diagnostic mode button.
- Mastodon is unreacheable over tor (tor browser says that the onion site is disconnected), even at a time when all other services are reacheable at their .onion addresses. This is still an open issue that does not get solved by stopping and restarting the service, rebooting the device (except when rebooting from Diag mode, which is accessible only after a Bep-Beethoven reboot, see above), uninstalling and recovering the service from backup.
-The OS was downladed from images.start9.com with a license, and never SSH'd into.
- I tried to substitute all and any hardware parts (except the SSD) with new ones, to no avail.
- I also tried both to reflash and restore from backup, and to start a new embassy and then restore from backup.

### Expected Behavior

I have a second Embassy on the same network, which is completely online in just a few minutes after rebooting. I would consider that as the normal behavior.

### Steps to Reproduce

Unfortunately I couldn't reproduce the issue on a different Embassy, without restoring my data.
The issue seems to be related to a specific set of data that gets restored from backup. I have less than 500GB of total data.

### Anything else?

[marketplace error.txt](https://github.com/Start9Labs/embassy-os/files/8688566/marketplace.error.txt)
[bitcoin logs.txt](https://github.com/Start9Labs/embassy-os/files/8688568/bitcoin.logs.txt)
[mempool.txt](https://github.com/Start9Labs/embassy-os/files/8695961/mempool.txt)
[syncthing.txt](https://github.com/Start9Labs/embassy-os/files/8695973/syncthing.txt)
[bitcoin logs 2.txt](https://github.com/Start9Labs/embassy-os/files/8696005/bitcoin.logs.2.txt)

**Comment by MattDHill** [comment]
Closing due to multiple improvements throughout OS

**Comment by maupet** [comment]
Thanks @chrisguida.
BTW, I am unsure that the issue is resolved on 0.3.1.
I haven't been able to get the device stuck at boot, but it still takes hours to gain connectivity (just as described in the report) after each reboot.
If it will get stuck again I will update this.

**Comment by maupet** [comment]
After updating EOS to 0.3.2 and testing a little bit, it seems to me that all of these issues have been finally solved!
I don't know what you did here, but apparently it worked 🥇 
I will reopen the issue if I encounter it again.

**Comment by kn0wmad** [comment]
Thank you for following up!!
