### ISSUE TITLE
[feat]: config ui modal: put new list items at the bottom of the list

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1454]
Steps to reproduce:
1. configure a service that has a list of objects (or unions)
2. click "+add" to add a new list item
3. new item is added to top of list instead of bottom:

<img width="736" alt="Screen Shot 2022-05-19 at 3 01 57 PM" src="https://user-images.githubusercontent.com/7445670/169395134-dd206858-d8e9-4ad8-a5f9-7ad66d1cbbf9.png">

This is confusing and inelegant, and may lead to downstream bugs. For instance, a user trying to keep their RTL nodes in a specific order, for instance, would have a rough time keeping their nodes in their desired order, since the last node added ends up first on the list. This would also then have an effect on their backups, since backups are stored by the order the nodes appear in the config.

New list items should be added to the bottom of the list, not the top.

Alternatively, there needs to be a way to easily reorder the items in the list.

**Comment by ProofOfKeags** [comment]
Lists probably ought to be reorderable

**Comment by chrisguida** [comment]
The biggest issue is that in RTL the first node in the list is the "default node", that is, it's the node that displays in the RTL dashboard every time you log in. So, when adding a new node, the new node always becomes the new default node, which is not intuitive to the user, and requires awkward deletions and re-additions in order to put the list in a desirable order, while processing information in the reverse manner from what they're used to. A prepend-only list is just not an intuitive data structure for either users or package devs.

As for backups, it's mostly fine, but again, as a package dev it's much less intuitive to deal with a prepend-only list, because what ends up happening in this case is that the backup for node 1 is stored int the `node-1` directory. Then if you add a node 2, node 2 becomes node 1, and the old node 1 becomes the new node 2. So the backup that used to exist in the `node-1` directory is now in the `node-2` directory, which, again, is just confusing, for both the user and the package dev. An append-only list is a much more straightforward data structure to handle.

**Comment by MattDHill** [comment]
Totally agree from a data structure standpoint. The primary challenge is that appending new items might be invisible unless the screen auto scrolls to the bottom of the list. I will think on a UX solution, any ideas are welcome.

**Comment by MattDHill** [comment]
We scroll when you attempt to save and there are errors on the page. We scroll to the first error

**Comment by MattDHill** [comment]
Scrolling is an option. Need to test with lists of varying length and see how it feels

**Comment by MattDHill** [comment]
Implemented, very nice. Will go into 0.3.1.
