### ISSUE TITLE
[feat]: Show existing version on Marketplace page when an update is available

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1473]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Currently, it is not shown what version is currently running on the Markteplace page of a service with an available update, only the version that is available to update to.  This is also a bit confusing as it appears above the "Installed" state, which makes it seem as though that is the installed version, see below:

![image](https://user-images.githubusercontent.com/39687477/171209552-bbdd43da-fb65-4806-bc58-84faec4f69a2.png)

### Describe the Use Case

Quick reference point for the user

### Describe Preferred Solution

The preferred solution would be to show the current version, and the updated version available, perhaps in the format:

12.2.2 *Installed* -> 12.2.3 *Available*

**Comment by MattDHill** [comment]
Closing in favor of #1473
