### ISSUE TITLE
[bug]: SDK is confused about dependencies.[dependency].requirement.how

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1474]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Other

### Browser Version

n/a

### Current Behavior

If dependencies.[dependency].requirement.how is included, SDK complains that it is an `Unrecognized manifest key`

If dependencies.[dependency].requirement.how is NOT included, SDK complains with `Deserialization Error: missing field how`

### Expected Behavior

SDK needs to know whether this key is needed, and if so, it betta recognize

### Steps to Reproduce

1. Add the key in question (or don't)
2. make
3. see error or warning

**Comment by chrisguida** [comment]
To clarify, this is only ambiguous when the requirement is `required`. Otherwise the `how` field is required.

**Comment by dr-bonez** [comment]
pretty sure this is fixed. reopen if encountered

**Comment by chrisguida** [comment]
Yep, @BitcoinMechanic verified this bug is gone as of a couple weeks ago
