### ISSUE TITLE
[feat]: Startup into standby mode after "shutdown"

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1477]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Graceful shutdown is not possible on new cases, so logic needs to be added to prevent coming back up in a bad state

### Describe the Use Case

Required for new cases

**Comment by chrisguida** [comment]
Blocks... ops?

**Comment by MattDHill** [comment]
Instead of treating the new case differently, we will implement a pseudo shutdown strategy universally. "Shutting down" an Embassy (any Embassy) will actually reboot it into idle mode.
