### ISSUE TITLE
[feat]: Handle category descriptions

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1492]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

1. Update the UI to handle category descriptions received from v1 version of registry api. 
2. ~~Update the UI to handle and display marketplace descriptions.~~ [Completed](https://github.com/Start9Labs/embassy-os/pull/1812) 

### Describe the Use Case

This will be useful for conveying information about what marketplace the user is connected to, as well as the intention of this marketplace.

**Comment by elvece** [comment]
category titles should be descriptive enough

**Comment by chrisguida** [comment]
>category titles should be descriptive enough

?

Does this mean we are going to lengthen all the category titles? And display them somewhere else so that longer titles will fit in the UI?

**Comment by elvece** [comment]
What I meant is that, a category title should be curated to be descriptive enough that its intention can be understood in succinct text.

**Comment by chrisguida** [comment]
How succinct?

**Comment by elvece** [comment]
Ideally one word, think 3 words at max seems sane. If it is long, the UI will handle it (I image that section will expand to be scrollable). 

Do you have something in particular for consideration?

**Comment by chrisguida** [comment]
I'm mostly trying to figure out if there's a change happening here or not. It sounds like we are going forward as we were.

**Comment by elvece** [comment]
Yes, proceeding as we were for now. Alt marketplaces should also abide by succinct category names as part of the protocol.
