### ISSUE TITLE
[bug]: Possible UI Replay

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1494]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

100

### Current Behavior

Installed several services on a brand new box (fresh install).  Installed 6 services and started them all, roughly in this order:

Bitcoin
Proxy
FileBrowser
BAR
Mempool
Vaultwarden

Configured and ran all services, walked away.  Returned several hours later to discover services had been re-installed, leaving them in "Needs Config" state.

### Expected Behavior

Services continue running without interruption

### Steps to Reproduce

Described above

### Anything else?

Ghost... the event was triggered while no users were accessing the device, despite the logs saying a new session was established, at which time the resintalls were triggered

**Comment by chrisguida** [comment]
I also experienced this issue in the middle of bitcoin IBD. Very disconcerting.

**Comment by MattDHill** [comment]
What leads you to believe this is a UI issue?

**Comment by dr-bonez** [comment]
>the logs saying a new session was established, at which time the resintalls were triggered

**Comment by kn0wmad** [comment]
We now have a user that has run into this in the wild

**Comment by MattDHill** [comment]
I have reproduced this. It happens when web sockets disconnect for some reason. Could be wifi connectivity, computer going to sleep, etc. The duplicate install requests fire on web socket reconnect. This will be fixed for 0.3.1.

**Comment by kn0wmad** [comment]
Great to hear!!
