### ISSUE TITLE
[feat]: Install on existing system?

### ISSUE THREAD

**Issue by kroese** [Start9Labs/embassy-os#1504]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

I would really like to install EmbassyOS on a Ubuntu or Debian server, so without the OS.

Is there a technical reason why this is not possible today?

### Describe the Use Case

It would allow for a larger userbase

### Describe Preferred Solution

Install script

**Comment by ProofOfKeags** [comment]
We haven't tested it and certain features were developed with the assumption of the environment it runs in (GPIO for speaker feedback, WiFi exists and is managed by NMCLI). We are working to expand hardware so we will be sorting this out sooner than later. If you'd like you can try installing the binaries produced by the build process to the server and see where things go wrong.

**Comment by elvece** [comment]
Completed: https://github.com/Start9Labs/embassy-os-deb

**Comment by chrisguida** [comment]
Run in a VM instead if you don't want to provision separate hardware
