### ISSUE TITLE
[bug]: [cli]  No longer can login to embassy cli

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1511]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.1~pre

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu

### Browser

Firefox

### Browser Version

N/A

### Current Behavior

1. I ssh into the box
2. I run the `embassy-cli auth login` 
And now I get 
![image](https://user-images.githubusercontent.com/2364004/172660018-c81535d0-804f-47e8-ae57-c2fe7cade7d0.png)

### Expected Behavior

To login

### Steps to Reproduce

See behavior

**Comment by chrisguida** [comment]
☝️
