### ISSUE TITLE
[bug]: Embassy-Os Js Procudure Known Error 

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1512]
### Reproduction
1. Working on fix/config-rules-ts in https://github.com/Start9Labs/c-lightning-wrapper
2. When service is pushed Test Embassy

Test is getting an error from the auto config (expecting to get this error)
![Screenshot from 2022-06-07 15-46-18](https://user-images.githubusercontent.com/2364004/172664078-e6aa6edf-b377-48eb-9868-70e113970f90.png)

### Possible Fix

I'm thinking that I could make strings that are returned being caught in a special way, so the error doesn't include the Uncaught (in Promise)

**Comment by chrisguida** [comment]
Correction, this is not autoconfig, just the config rules checker in setConfig

**Comment by Blu-J** [comment]
Ok, I thought this was only for auto config, I'll expand the api to be a union on the return types, something like 
```ts
type KnownErrorMessage = {
  error: string
}
```
