### ISSUE TITLE
[feat]: Include docs in eOS

### ISSUE THREAD

**Issue by PLK2** [Start9Labs/embassy-os#1515]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Provide an option to download a copy of the Embassy manual, to be stored locally on the embassy.

### Describe the Use Case

For local troubleshooting purposes, in case internet is out or slow or whatever. Also just easier/faster to have it local.

**Comment by kn0wmad** [comment]
We have considered this, but it is quite large (or would need to be adapted to a skinnier version).  We would love to see a PR for this ;)

**Comment by PLK2** [comment]
Yeah, wasn't sure how large it would be. Not critical; I just like to keep manuals offline and adjacent to where they may be needed.

**Comment by kn0wmad** [comment]
Totally agree, it will be nice to have

**Comment by chrisguida** [comment]
We could put a link to this in the top left where the Start9 icon is

**Comment by kn0wmad** [comment]
The point of this issue is to have a *local* copy

**Comment by chrisguida** [comment]
Yes, I know....

**Comment by ProofOfKeags** [comment]
I think the better answer here is to cache a copy of the centralized manual every time you fetch it and then try to update it periodically. Centrally managed docs are going to be more up to date and caching them locally should alleviate concerns about accessibility without Start9's presence.

**Comment by elvece** [comment]
Fetch the latest compatible version of docs

**Comment by MattDHill** [comment]
Closing in favor of a "Docs" package

**Comment by kn0wmad** [comment]
Closed in favor of https://github.com/Start9Labs/documentation/issues/326
