### ISSUE TITLE
[bug]: Notifications toast shows "View" repeatedly

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1524]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

100

### Current Behavior

Notifications toast stacks the word "View" - so far witnessed up to 4-5x

### Expected Behavior

One view can cut it

### Steps to Reproduce

1. On any page, experience a notification
2. Toast shows bug

**Comment by elvece** [comment]
![image](https://user-images.githubusercontent.com/12953208/173436959-a92c5a27-9c35-47fa-94f0-214ba26ea6bc.png)

**Comment by elvece** [comment]
Fixed by: https://github.com/Start9Labs/embassy-os/pull/1464/commits/ddb9a11af9ba80e1c4dd699a661b392cf5ebe99a
