### ISSUE TITLE
[bug]: Database lock during a downgrade

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1529]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

100

### Current Behavior

![image](https://user-images.githubusercontent.com/39687477/173464606-a09a2124-545c-400a-bad5-a90dc6eda643.png)

### Expected Behavior

Don't lock

### Steps to Reproduce

1. Perform downgrade of a service
2. See db lock

### Anything else?

Resolved itself without action

**Comment by MattDHill** [comment]
Closing as duplicate of #1309
