### ISSUE TITLE
[feat]: Allow Tor interfaces to specify https

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1538]
In the interfaces menu, the tor URL always shows up as `http://` rather than `https://`. This is incorrect for some services, such as Synapse and CLN's C-Lightning-REST plugin, which both do SSL over Tor. There should be a way to specify `https://` in the manifest for Tor, possibly by adding an `ssl: bool` key to `tor-config`, just like we have on LAN config.

<img width="1231" alt="Screen Shot 2022-06-14 at 3 34 26 PM" src="https://user-images.githubusercontent.com/7445670/173683612-f98fe57f-234a-4be6-87aa-ac386af299a9.png">

**Comment by ProofOfKeags** [comment]
No. Tor addresses are *not supposed to use https*.

**Comment by chrisguida** [comment]
I disagree. We need to accommodate software such as c-lightning-REST and Synapse, which use https to communicate over clearnet. A side effect of requiring https when using clearnet is that connections over Tor then also use https. I don't think it is reasonable to require upstream services to be aware of when they are using Tor and deactivate https under those circumstances. And I don't think it's reasonable to provide a degraded experience to the user because we're waiting for upstream services to implement this, which probably will never happen.

See: https://github.com/Start9Labs/embassy-os/issues/1525

**Comment by dr-bonez** [comment]
@ProofOfKeags while this is technically the services fault, we may need to accommodate them, otherwise we may actually die on this hill.

**Comment by ProofOfKeags** [comment]
Point taken...what a man can do and what a man won't do.

**Comment by dr-bonez** [comment]
I think we should close this in favor of #1568
