### ISSUE TITLE
[bug]: `sudo -i` throws an error (but still works)

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1585]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.4

### Browser

Firefox

### Browser Version

101.0.1

### Current Behavior

```
sudo -i
sudo: unable to resolve host embassy-87fa5f10: Name or service not known
```
![image](https://user-images.githubusercontent.com/45926711/176508442-94d1b695-1763-47fa-bf8c-e43e96034f58.png)

### Expected Behavior

No error

### Steps to Reproduce

ssh in using `start9@xxx.local` and type `sudo -i`

### Anything else?

Feature request for ssh host keys to not change every reflash by @chrisguida edit: @dr-bonez says this is not desirable/doable

**Comment by kn0wmad** [comment]
Can you provide some context for this?  Is there a guide that asks for it, for example?

Also, I am unable to reproduce

**Comment by dr-bonez** [comment]
Disappointing that hostnamectl doesn't handle this

**Comment by k0gen** [comment]
Although I am more of a fan of `sudo -s` (I prefer to stay in the directory I'm in) I was not able to replicate this issue on 0.3.1 (244260e34a9152ddd9d8e864f162bc9d112dc178)

**Comment by gStart9** [comment]
I also was unable to reproduce this on 0.3.1 final.  @BitcoinMechanic is this still happening for you?

**Comment by BitcoinMechanic** [comment]
No, it seems to only happen the first time you do it on any particular build.
