### ISSUE TITLE
[feat]: Move system reverse proxy into the OS

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#1594]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Currently, NGINX modifies requests too much when proxying to containers. Really, all we need it for is muxing between domains, and adding ssl.

### Describe the Use Case

Currently, WebDAV is not possible on .local because of the reverse proxy.

### Describe Preferred Solution

EOS should stop using NGINX, and instead embassyd should bind to port 80 and 443, and manage the passthrough of requests itself.

### Describe Alternatives

some research into haproxy may be valuable

**Comment by MattDHill** [comment]
What about WebDAV over Tor?

**Comment by dr-bonez** [comment]
Should work fine if the client supports tor
