### ISSUE TITLE
[feat]: Hover over yellow exclamation point displays health check warning

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1611]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

In the services window, services will show a yellow exclamation point if something is wrong with a health check. You can then click on the service to see what the issue is. This feature would allow you to hover over the symbol and see a popup and not have to click through to the service.
![image](https://user-images.githubusercontent.com/45926711/177056652-5f21367f-ff82-40cf-b2cc-42fe922e5f02.png)

### Describe the Use Case

When health checks are issuing a warning, you can view it without going through to the service.

**Comment by elvece** [comment]
This might be too much information to display in a hover tooltip, as there can be multiple health check failures. I don't think it's too much trouble to navigate to the service page to view this information.

Is the main problem here that you would like a summary of the health checks for all services?

**Comment by chrisguida** [comment]
Maybe just hover to see *which* hck is failing, rather than the specific failure message?

**Comment by dr-bonez** [comment]
Without going into specifics of what exactly to show, I think there's value in showing a summary of what is wrong with the service on hover.

**Comment by MattDHill** [comment]
Maybe something high level like "health check failure" or "dependency issue"? Then if they want to know more, they can open the service

**Comment by BitcoinMechanic** [comment]
I like that. The instinct to hover over something that looks like a problem is well established imo.

**Comment by elvece** [comment]
Also there will be no direct corollary for mobile as hover events don't exist there.

**Comment by MattDHill** [comment]
Let's build this out for hover/desktop only, will just be ignored on mobile. If user needs to press on mobile anyway, they will just press to see the service.

**Comment by elvece** [comment]
Difficult to implement and obviated by future cool dashboard plans
