### ISSUE TITLE
[feat]: handle a config with nothing but pointers

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1625]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

When a service only has config pointers but needs to be configured, the config modal displays as empty. Handle this case with appropriate messaging.

### Describe the Use Case

It is an awkward user experience to have to configure a service and have no information as to what is being configured.

**Comment by dr-bonez** [comment]
This may need backend consideration as well. Ideally such a service should never go into needs config in the first place if there is nothing to configure.

**Comment by MattDHill** [comment]
The ticket will likely be obviated by a re-thinking of the system architecture as it relates to pointers and config.

**Comment by dr-bonez** [comment]
The ultimate goal is to get rid of config pointers. System and dependency information will be made available through the js api

**Comment by elvece** [comment]
Obviated by #2050
