### ISSUE TITLE
[feat]: Publish OS and Service Releases with SHA256 Hashes

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1629]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

A hash ought to be published with each published asset

### Describe the Use Case

This allows both the devs to verify they are looking at the same asset, as well as allowing a user to verify they have the asset that was published

### Describe Preferred Solution

SHA256 is fine

**Comment by dr-bonez** [comment]
ACK

**Comment by MattDHill** [comment]
What's LOE here?

**Comment by dr-bonez** [comment]
It just needs to be part of our release process. Run a sha256sum and a b3sum of eos.img, and update.img when cutting a tag.

same for s9pks

**Comment by NyamiDev** [comment]
At the moment your guides suggest simple downloading the latest OS image and checking against a checksum. There is no PGP verification process that is suggested. You find with much of the other privacy/security orientated software. Otherwise great! Thanks.

**Comment by elvece** [comment]
> It just needs to be part of our release process. Run a sha256sum and a b3sum of eos.img, and update.img when cutting a tag.
> 
> same for s9pks

@islandbitcoin @k0gen @chrisguida @Blu-J @elvece
