### ISSUE TITLE
[feat]: Add a clock displaying system time (UTC) (visible while looking at logs!)

### ISSUE THREAD

**Issue by JesseMarkowitz** [Start9Labs/embassy-os#1632]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Please consider adding a clock displaying the Embassy OS time.

I was initially thinking on the left hand side, but anywhere so it is visible while looking at logs would be helpful

This could be more useful for some folks than even the snake game.

### Describe the Use Case

A problem occurs at 10am local time and I open up the logs to see what the issue might be.  I see errors in the logs starting at 10am.  Did the errors occur just now, 4 hours ago? 1 hour ago?  It depends on my time zone vs. UTC.  Would be nice if I could just see the current system time in the same browser window that I see the log entries.

### Describe Preferred Solution

Add a clock in the left sidebar - perhaps between Snek and LogOut? or between Start9 and Services?  don't really care where...

### Describe Alternatives

Maybe just add it to the title bar on all Logs screens?    
replace "<-  Logs                                                                   "
with      "<-  Logs             Current Embassy time is: 18:43:05"

I can look up the time difference manually every time - but I don't spend a lot of time looking at logs or dealing with UTC and I do change locations / time zones from time to time, so it's a bit of a pain.

### Anything else?

Not very important, but it would be nice to have for me - so I thought particularly for less technical folks, it might be nice for them too.

**Comment by elvece** [comment]
@dr-bonez BE component: add endpoint to get server time

**Comment by elvece** [comment]
@JesseMarkowitz Thanks for the request! I totally see how this could be annoying 😅 Adding to our next milestone

**Comment by dr-bonez** [comment]
@elvece for a proper clock, we don't want to be spamming the backend. You can probably show the current UTC time pretty easily without any request to the backend, and let that update live. Only use case of the endpoint IMO is because it could show an issue with NTP, if it's too far off of what it should be.

**Comment by elvece** [comment]
> @elvece for a proper clock, we don't want to be spamming the backend. You can probably show the current UTC time pretty easily without any request to the backend, and let that update live. Only use case of the endpoint IMO is because it could show an issue with NTP, if it's too far off of what it should be.

Cool maybe we just call the endpoint on refresh or something, to make sure we're in sync? Perhaps that doesn't matter. Thanks for the insight.

**Comment by chrisguida** [comment]
Even lighter: just use the client clock and just sync the backend timezone?

**Comment by dr-bonez** [comment]
backend timezone is always UTC

**Comment by elvece** [comment]
Maybe a clock showing UTC and local time 🤔 ? @chrisguida are the log timestamps the same for every service (same format) from the BE endpoint?
