### ISSUE TITLE
[feat]: Better messaging / user flow around Services "Needs Config"

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/embassy-os#1634]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Upon upgrading Bitcoin Core to v23, Bitcoin goes into "Needs Config" state, which stops bitcoin from going up and points me to the new Bloom Filters (BIP137) option, which the UI recommends against turning on.

### Describe the Use Case

Services would relaunch without user intervention.

### Describe Preferred Solution

If new config options are defaulted to off and recommended against, they are nice to know but shouldn't be necessary for the user to manually look at and learn about before their service goes back up.

### Describe Alternatives

Service should just go up, at least if it the default for a new config option is off and it is not recommended to be turned on.

**Comment by elvece** [comment]
Think the best solution here is around messaging, indicating that there are new config options, they were populated with defaults, but no user action is required.

**Comment by dr-bonez** [comment]
It actually would be pretty easy to create the behavior George is looking for, but I don't think it's necessarily what we want. Do we really want to skip showing users new config options?
@MattDHill

**Comment by MattDHill** [comment]
This is a question of tradeoffs. I think the current behavior is acceptable. If there are new options, the service goes into needs config, where the user can explore them before accepting the defaults or making changes.

**Comment by chrisguida** [comment]
An alternative could be to show the new config options without going into needs config; just show them somewhere else on the screen in a list, or pop up a read-only config modal. Or something like that.

**Comment by chrisguida** [comment]
Possibly in this case the desired behavior is actually for bitcoind to have defaulted bloom filters to false and set configured to true. Then, the first time the user went to reconfigure the service, he or she could see the new flag.

**Comment by k0gen** [comment]
My logic and preferable user experience about this would be to see *Needs Config* only once during first install.
Updates should be experienced by simply clicking *Update* and waiting for embassyOS to do the best it can to update my service as fast as it can to make it active and running again.
It would be nice to see a yellow number indicator on the service advertising that new settings are waiting for users review.

**Comment by elvece** [comment]
> This is a question of tradeoffs. I think the current behavior is acceptable. If there are new options, the service goes into needs config, where the user can explore them before accepting the defaults or making changes.

My suggestion was to augment the "New Config Options!" message to say "New Config Options! Options are populated with recommended defaults", or something. This makes it explicit what occurred, and indicates that no action besides review is needed. 

@k0gen I like the direction of this suggestion, but there is a tradeoff of trust, where the user then has a service running with config options that they have not opt-ed into. This might be trivial, but should be considered.

**Comment by k0gen** [comment]
> @k0gen I like the direction of this suggestion, but there is a tradeoff of trust, where the user then has a service running with config options that they have not opt-ed into. This might be trivial, but should be considered.

Fair enough. This is also a question with:
Do new config settings should be defaulted to disabled and advertised or do we want to guide user that such and such new feature is worth enabling and this is the services suggested default setting from now?

**Comment by elvece** [comment]
[This PR](https://github.com/Start9Labs/embassy-os/pull/1569) has addressed updating this messaging as I suggested.

**Comment by chrisguida** [comment]
>It would be nice to see a yellow number indicator on the service advertising that new settings are waiting for users review.

I actually really like this suggestion. This could be implemented by augmenting the migration return type to include a boolean `new-config-options` as well as the current `configured` boolean. Then, when the user installs, the service automatically self-configures, but have a flag or bubble telling the user they should look at the config menu until they've looked at it. Best of both worlds.
