### ISSUE TITLE
[feat]: Ability to Sort Services Page by Status

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1635]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Sort by Running / Stopped for example

### Describe the Use Case

A user may wish to push all "Stopped" services to the bottom, as they are not in use, or perhaps vice versa, to see what is installed, but not in use

### Describe Alternatives

General sorting, such as alphabetical, or more complex, such as by resource usage

**Comment by elvece** [comment]
FYI you _can_ manually reorder, but will consider a sorting feature. I have been thinking about this more, especially as we grow in categories.

**Comment by MattDHill** [comment]
Can sort however you want in 040 + health widgets
