### ISSUE TITLE
[feat]: Add Postgres as system dependency

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1649]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Swap sqlite for postgres and allow services to access to this built in dependency. 

Research: see if postgres can handle each database having its own file system --> bind out each packages data into a volumes directory (can eventually place limits on storage, as well as different services on different drives) 

### Describe the Use Case

sqlite has proven problematic with regard to threading and database locking. Postgres fixes this. 

Several services use a postgres in their Docker containers. It would be a performance and development improvement if they could create a database with permissioned user.

**Comment by dr-bonez** [comment]
closed by #1763
