### ISSUE TITLE
[bug]: Occasional very slow downloads from registry.

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1650]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.4

### Browser

Firefox

### Browser Version

101.0.1

### Current Behavior

I started this download about an hour ago. This is alpha reg but it happens to me on beta too.

It took me over 24 hours to download an 0.3.1rc

Seems to happen to me about 50% of the time. Haven't managed to establish a pattern.

![image](https://user-images.githubusercontent.com/45926711/178883908-d9b6a0f8-87e0-4712-bdad-2674f2d9c298.png)

### Expected Behavior

Consistent and fast downloads

### Steps to Reproduce

I don't know how to repro.

**Comment by elvece** [comment]
Are other downloads on your network periodically slow?

Needs more information gathered. A capture of the network tab information would be useful.

**Comment by BitcoinMechanic** [comment]
Nothing else on my network is odd.

Just triggered it downloading cryptpad. Request and response tabs both empty, so this seems to not have even gotten a response.
![image](https://user-images.githubusercontent.com/45926711/184260257-a09c06b8-117a-4d54-994d-9b2529cb11c5.png)

**Comment by BitcoinMechanic** [comment]
It is actually downloading, but literally nothing in the network tab

**Comment by kn0wmad** [comment]
Is this still occurring?  Does it happen when moving networks?
