### ISSUE TITLE
[feat]: add localhost to system certs

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1651]
This is to fix `lncli` in the js properties version of LND: https://github.com/Start9Labs/lnd-wrapper/pull/68#issue-1304131298

**Comment by dr-bonez** [comment]
I guarantee this is not necessary

**Comment by chrisguida** [comment]
Why not?

**Comment by dr-bonez** [comment]
you can use the .embassy. It works just fine. The other error you were experiencing with .embassy was *downstream* of the cert error

**Comment by chrisguida** [comment]
I'm not following. 

We need users to be able to run `lncli getinfo` without errors. How do you propose that we do this without adding localhost to the cert?

```
~/.lnd # lncli getinfo
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for xxyoh5bbri6y572mc3frogaun6cy5txdpyq7xetikbn3vuteukncb2yd.local, *.xxyoh5bbri6y572mc3frogaun6cy5txdpyq7xetikbn3vuteukncb2yd.local, xxyoh5bbri6y572mc3frogaun6cy5txdpyq7xetikbn3vuteukncb2yd.onion, *.xxyoh5bbri6y572mc3frogaun6cy5txdpyq7xetikbn3vuteukncb2yd.onion, lnd.embassy, *.lnd.embassy, not localhost"
```

```
~/.lnd # lncli --rpcserver lnd.embassy getinfo
[lncli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

**Comment by elvece** [comment]
Figure out how to trust system cert, as whole chain is available in system mountpoint
