### ISSUE TITLE
[feat]: 🐋 Add start9 user to docker group

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#1652]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Elevate `start9` user rights to run `docker` command without `sudo`.

### Describe the Use Case

Transitioning from old habits working as root can be a painful experience. 

### Describe Preferred Solution

Lets make it bearable by simply adding start9 user to docker group.

`usermod -aG docker start9` will do

### Describe Alternatives

Listen to users asking about docker not working because:
```
Got permission denied while trying to connect to the Docker daemon socket
```

### Anything else?

If accepted just tell me at what stage you want this to happen?

**Comment by PLK2** [comment]
Ah, was about to add this but @k0gen beat me to it!
