### ISSUE TITLE
[feat] add "download" as backup option

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#1657]
Currently, user can select between physical drive and LAN Shared Folder for backup target. Might be nice to be able to download the backup instead. This would miss out on the incremental aspect of backups and would be infeasible for large data sets, but if someone just wants to quickly back up their device while away from home, this might be their only option. Could be huge for things like Vaultwarden, LND, or CLN.

**Comment by elvece** [comment]
Needs as much space on device as backup size.
