### ISSUE TITLE
[bug]: Close buttons in Config modal don't work

### ISSUE THREAD

**Issue by cryptoquick** [Start9Labs/embassy-os#1721]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Arch

### Browser

Chrome

### Browser Version

104.0.5112.79

### Current Behavior

I went to the File Browser app after upgrading, opened Config modal, and tried to close out of it, but the two GUI buttons didn't do anything other than the silly material ripples. Fortunately, ESC did work.

### Expected Behavior

Both the X button and the close button should close the modal.

### Steps to Reproduce

1. Go to https://embassy-xxx.local/#/services/filebrowser
2. Click "Config"
3. Try to click either button to exit the modal

### Anything else?

See:

https://user-images.githubusercontent.com/285690/183148099-fc9b4b55-59c3-455c-9d38-28ab92ab002b.mp4

**Comment by MattDHill** [comment]
Already fixed in master, thanks for reporting.

**Comment by cryptoquick** [comment]
Haha, awesome! Glad you're already on it.
