### ISSUE TITLE
[feat]: Marketplace tab to show only Installed apps

### ISSUE THREAD

**Issue by cryptoquick** [Start9Labs/embassy-os#1723]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

In the Marketplace, I'd like to have a tab that lets me see only the apps that are installed

### Describe the Use Case

The ALL list is pretty long, and it would be nice to avoid scrolling through all apps available as the marketplace grows

### Describe Preferred Solution

Maybe an INSTALLED tab next to ALL to show only installed apps, or maybe between FEATURED and UPDATES

### Describe Alternatives

Making the window really big and scrolling through the the ALL screen

### Anything else?

![Screenshot from 2022-08-05 13-52-31](https://user-images.githubusercontent.com/285690/183150840-be4b1506-db12-4cb3-8f4e-d452ba6dcf5a.png)

**Comment by MattDHill** [comment]
Why do you want to see your installed services in the marketplace? Installed services are listed in the services tab.

**Comment by cryptoquick** [comment]
Oh, good point. I hadn't thought of that. I guess it just seemed like there's some symmetry in the navigation UI that's lacking. If you've ever used a Synology NAS, they have an installed tab with a separate upgrades section, but that's in addition to the application menu. I can screenshot what I mean, if you like. Feel free to close if this seems unnecessary.

**Comment by MattDHill** [comment]
We have plans for the Marketplace ecosystem UX that will obsolete the current UI.
