### ISSUE TITLE
[feat]: Update Vaultwarden to 1.25.2

### ISSUE THREAD

**Issue by SoundMoneyWins** [Start9Labs/embassy-os#1725]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Current Embassy OS supported Vaultwarden version 1.22.2 is over 1 year old. Newest version of Vaultwarden is 1.25.2 and was released 11 days ago. Update to current version.

### Describe the Use Case

Multiple fixes with the current version of Vaultwarden versus the current outdated version supported in Embassy OS.

**Comment by MattDHill** [comment]
Thank you for the request. This repository is for issues related to EmbassyOS. Closing in favor of https://github.com/Start9Labs/vaultwarden-wrapper/issues/19.
