### ISSUE TITLE
[feat]: embassy container init 

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1735]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Given that we have the long running docker containers, we noticed that we didn't have the correct solution during the kill. Instead of know what procresses we created for the main exec, we just sent in the assasin that kills himself.

### Describe the Use Case

We would like to be able to know:
* [ ] What procresses where created/ ended
* [ ] Ability to end them

### Describe Preferred Solution

Something similar to any other init system. We need to start the exec on the long running container. We could send the command, and start it via a subprocess.
Then when it finishes we will need to know, or if it errored.
We need to track and store the logging.

**Comment by MattDHill** [comment]
dup #1785
