### ISSUE TITLE
Enable LAN for services

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#174]

**Comment by k0gen** [comment]
Easy and nice option would be to configure the same address as the v3 onion but in local suffix by default. For example.
Tor address:
`mova2j6ae17o2ija7g74pmtiwbwqbk3gjrrz52y7b7ujgh2ckn6zyeqd.onion`
Lan address:
`mova2j6ae17o2ija7g74pmtiwbwqbk3gjrrz52y7b7ujgh2ckn6zyeqd.local`

Or custom name presented as: **`servicename`**.start9-a12a66a6.local
