### ISSUE TITLE
[feat]: [cli]: Option to save defined `--host` to config file

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#1744]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

When installing from remote dev box by executing: `embassy-cli package install service.s9pk`
General error appears because embassy-cli defaults to localhost.
You then have to expand the command to: `embassy-cli --host https://embassy-q1w2e3r4.local package install service.s9pk` to succeed.

### Describe the Use Case

New package dev are not aware that they can define their Embassy address in: `~./embassy/config.yaml` file.

### Describe Preferred Solution

Add option to SDK like `embassy-sdk init --host https://embassy-q1w2e3r4.local` to generate proper config file and save specified host.

### Describe Alternatives

Config file would be generated during `embassy-sdk init` with interactive question about specifying the package installation target, informing that they can enter their Embassy http://embassy-q1w2e3r4.local address or press enter for default (localhost)

### Anything else?

n/a

**Comment by elvece** [comment]
The SDK should not be writing config values that are only cared about by the CLI. Need to think of a more intuitive UX for this in general.

**Comment by chrisguida** [comment]
Seems the sdk and the cli are part of a package deal, why not have them interoperate?

**Comment by chrisguida** [comment]
The usecase for this ticket is mostly for dev, the ability to install a service remotely using the cli is mostly useful to people who are actively using the sdk
