### ISSUE TITLE
[bug]: Copy failing on action response

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1747]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1@d5f7e15dfb140bcb7a54ff7f7b5bd6a6759cb853

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.15.7

### Browser

Firefox

### Browser Version

103.0.2

### Current Behavior

When an action response is copyable, the displayed result does not actually copy to your clipboard. The hover on copyable should also be fixed from a green plus to a pointer cursor.

(The console error here is actually a separate issue resolved in this PR: https://github.com/Start9Labs/embassy-os/pull/1738)

<img width="2553" alt="Screen Shot 2022-08-19 at 10 32 01 AM" src="https://user-images.githubusercontent.com/12953208/185665405-d3f26c3c-08d8-46aa-ae0e-0ca6d648b266.png">

### Expected Behavior

Copy button should copy to clipboard effectively. 

### Steps to Reproduce

1. Install and configure btcpay server
2. Navigate to actions
3. Execute "Enable Registrations" action
4. See result and attempt to copy

**Comment by MattDHill** [comment]
I am unable to reproduce this. My only guess is the unrelated error that we already solved is glitching the UI.

**Comment by elvece** [comment]
This is reproducible on 0.3.1.1, with the release hash of `d5f7e15dfb140bcb7a54ff7f7b5bd6a6759cb853`.

It is not reproducible on a version of eOS running on `89a95d09fc053480cef655ac6d04d73027c7dd4c`
