### ISSUE TITLE
[bug]: Error on config page when configure fails

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1749]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1@d5f7e15dfb140bcb7a54ff7f7b5bd6a6759cb853

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.15.7

### Browser

Firefox

### Browser Version

103.0.2

### Current Behavior

When a service config fails (ie. an error is thrown), an error also appears in the dev console. The page renders fine, but the modal cancel button does not work, and the only way to exit the modal is to refresh the page. 
<img width="1676" alt="Screen Shot 2022-08-15 at 3 33 42 PM" src="https://user-images.githubusercontent.com/12953208/185683551-2fe44946-57b4-46bb-bf88-15e37005a259.png">

### Expected Behavior

The issue stemming from the console should be handled appropriately, allowing the modal to properly close when a service configuration fails / displays an error.

### Steps to Reproduce

- install btcpay server at 1.4.7
- attempt to configure
- view error in developer console

**Comment by MattDHill** [comment]
Did this error throw after dryConfigure or configure?

**Comment by elvece** [comment]
Neither, it throws an error when getting the config:

Request:

<img width="1678" alt="Screen Shot 2022-08-22 at 10 21 53 AM" src="https://user-images.githubusercontent.com/12953208/185970481-75f32d8c-c3c2-4a05-9824-b514420b45c7.png">

Response:
<img width="1676" alt="Screen Shot 2022-08-22 at 10 19 33 AM" src="https://user-images.githubusercontent.com/12953208/185970265-cf239303-1dbb-42d0-b5c1-a0582c3b77d9.png">

**Comment by elvece** [comment]
Fixed as of 33d0a35d21ee6b5447b11d6098fa9916873d711f
