### ISSUE TITLE
[bug]: EmbassyOS crashed and unrecoverable with error msg in embassy logs

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/embassy-os#1755]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

15.2

### Browser

Firefox

### Browser Version

104.0

### Current Behavior

Stuck on initialization page. 
SSH works, but not all docker containers spin up. Error message seen in logs
```

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]:    0: embassy::manager::run_main
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]:       at src/manager/mod.rs:179
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]: Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]: Run with RUST_BACKTRACE=full to include source snippets., kind: Tor, revision: None }
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]: 2022-08-20T20:49:24.456310Z ERROR embassy::manager: failed to start service: Tor Daemon Error: interface main missing key
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]: 2022-08-20T20:49:24.456327Z DEBUG embassy::manager: Error { source:
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]:    0: interface main missing key
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]: Location:
Aug 20 20:49:25 embassy-f5fb24ed embassyd[1383]:    /home/rust/src/backend/src/manager/mod.rs:197
```

### Expected Behavior

Normal Operation

### Steps to Reproduce

Unclear.

### Anything else?

<img width="996" alt="Screen Shot 2022-08-19 at 8 25 24 PM" src="https://user-images.githubusercontent.com/34528298/185765885-d499726c-1bdf-4d2b-8098-fe86b9b2c5e6.png">

**Comment by chrisguida** [comment]
Can you clarify what you did before this happened? Where did you get this image? That might help narrow things down

**Comment by MattDHill** [comment]
Was this resolved @islandbitcoin ?

**Comment by kn0wmad** [comment]
@islandbitcoin is this reproducible?

**Comment by islandbitcoin** [comment]
This was resolved after a deep dive and surgery with @dr-bonez. closing issue.
