### ISSUE TITLE
[bug]: Time inconsistencies

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1757]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

It would seem that some minor R&D to establish a protocol for keeping uniform time on the Embassy is in order.  Lots of time inconsistencies have been brought to our attention by users, some of which can cause serious issues, such as the inability to install a service

### Expected Behavior

We may wish to use UTC for all time within Embassy devices.  Not sure if this would be in conflict with what shows in the UI, which we may want to be local time for a user, based on their client device's time.  

### Steps to Reproduce

1. Time appears and is used in many places in Embassy, such as in logs, and can affect various activities, such as network connections and installs

**Comment by MattDHill** [comment]
Time is stored in UTC and displayed in the UI according to the user's timezone.

Issues with time are likely coming from inability to sync with NTP, which is a whole can of worms. @dr-bonez thoughts?
