### ISSUE TITLE
[bug]: JS Procedure Logs in Wrong LogFile?

### ISSUE THREAD

**Issue by Blu-J** [Start9Labs/embassy-os#1760]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

NA

### Browser

Firefox

### Browser Version

NA

### Current Behavior

The logs are being put into the logs of the embassy logs (the systems) since they are coming from rust and therefore the system

### Expected Behavior

Would be nice to have the errors in the service?

### Steps to Reproduce

1. In a js service procedure, use the effects.error or effects.warn to create a log
2. Those logs are part of the embassy os logs and not the logs of the service.

**Comment by MattDHill** [comment]
Closed by #2103
