### ISSUE TITLE
[feat]: Indicate with Green Text when a Backup is "Current"

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1765]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Currently the "Last Backup" text appears in yellow at all times, this seems a prime opportunity to indicate to the user when they have a recent backup, or when they have a stale one

![image](https://user-images.githubusercontent.com/39687477/186964394-c55ae2d9-e39f-4435-abd0-423c89dfee70.png)

This would be a great MVP for encouraging backups

### Describe the Use Case

Better messaging to the user regarding backups

### Describe Preferred Solution

Turn the text to the color GREEN when the backup is less than X days old (perhaps 7?)
Turn the color to YELLOW when greater than X days old
Turn the color to RED when a back up has never been completed, or is greater than Y days old (perhaps 30?)

**Comment by kn0wmad** [comment]
I've just noticed that this is clocked at Zulu time, and would more ideally reflect the user's timezone.  This probably requires a separate ticket?  @MattDHill

**Comment by MattDHill** [comment]
Backup timestamp should be stored in UTC and displayed in user's timezone. Where are you getting Zulu time from?

**Comment by kn0wmad** [comment]
Zulu is UTC.  It is being both stored and displayed in UTC

**Comment by MattDHill** [comment]
Done
