### ISSUE TITLE
[feat]: Data Drive Migrations

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1767]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Ability for EOS to reproduce partitions and move data from an existing embassy data drive to a new one

### Describe the Use Case

This is most immediately relevant to those with an external drive, such as a Samsung T7, that would like to use an AIO case, which would require an internal SSD.

### Describe Preferred Solution

Probably the best would be to have no drives connected, boot into diagnostic mode, and have an option to "clone/copy data drive."  The flow would then guide the user to plug in drives, one at a time, and then perform the migration

**Comment by chrisguida** [comment]
Wouldn't a full system restore do this as well?

**Comment by kn0wmad** [comment]
Yes, this was discussed as an alternative for folks that will migrate from an external drive to an internal in order to use an AIO case.  It is TBD whether it is worth it.  If trivial, it would be very helpful for a subset of users, and if not trivial, it will be punted.

**Comment by MattDHill** [comment]
Closed by #1841
