### ISSUE TITLE
[bug]: Non A-Record requested for vaultwarden.embassy

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1768]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

n/a

### Browser

Firefox

### Browser Version

n/a

### Current Behavior

`WARN embassy::net::dns: Non A-Record requested for vaultwarden.embassy.`

Symptoms are unknown, but this often coincides with Tor unreliability.  Possibly unrelated

### Expected Behavior

n/a

### Steps to Reproduce

This seems to have been introduced in 0.3.1.1

**Comment by Mutrafulus** [comment]
Trying to troubleshoot why Electrs is crashing when broadcasting from Sparrow I came across this too In my instance the service in question would rotate scrolling through logs.

**Comment by kn0wmad** [comment]
> Trying to troubleshoot why Electrs is crashing when broadcasting from Sparrow I came across this too In my instance the service in question would rotate scrolling through logs.

This is unrelated and is a warning that I believe we will be suppressing in or around v0.3.4 - please contact us in a support channel for assistance with troubleshooting.  https://docs.start9.com/latest/support/contact
