### ISSUE TITLE
[bug]: Restored service Interfaces fail to launch

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1769]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

After restoring a service (individually, not as part of a full recovery), both the Tor and LAN interfaces become unavailable (unable to connect to server)

Health checks report success (UI available)

### Expected Behavior

Service UIs launch

### Steps to Reproduce

1. Do a backup of a service
2. Uninstall / Restore that service
3. Wait for service UI to be healthy
4. Launch UI
5. See bug

### Anything else?

A reboot fixes this

**Comment by MattDHill** [comment]
@kn0wmad can you test this on 032 please

**Comment by kn0wmad** [comment]
Unfortunately this bug remains
