### ISSUE TITLE
[feat]: tab key should jump from field to field in setup flow when creating password

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1770]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

The tab key currently jumps from the first password field to highlighting the "eyeball" button that reveals the text. Pressing it one more time moves it to the second password field.

### Describe the Use Case

Anyone who likes to never take their hands off the keyboard will like this.

**Comment by kn0wmad** [comment]
I believe this is considered the expected behavior, as someone who does not want to leave the keyboard would want to use that eyeball button by tabbing over to it

**Comment by BitcoinMechanic** [comment]
That'd be better. I know that I always expect it to jump from 1 to 2 as you have written above.

**Comment by MattDHill** [comment]
Nack on this. It would require effort to override the default behavior, especially f we wanted to be consistent with it. Plus I actually prefer it this way. Imagine a large form with 20 inputs, and I am unable to use a mouse. I would have to hit tab 20 times before I could choose to view the field in which I am currently typing. What you are suggesting is unconventional.

**Comment by chrisguida** [comment]
I'm kind of skeptical that people with a tab key but no mouse are very common

**Comment by MattDHill** [comment]
https://www.csun.edu/universal-design-center/web-accessibility-criteria-tab-order

Aside from this being the standard, I also disagree with the ask here. 💀
