### ISSUE TITLE
[bug]: "Close" and "X" button don't work to close the config window of services that have no config settings

### ISSUE THREAD

**Issue by Rearden21M** [Start9Labs/embassy-os#1776]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.1~1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.1

### Browser

Firefox

### Browser Version

103.0.2 (64-bit)

### Current Behavior

For services that do not have any config parameters to tweak (e.g. File Browser, Photoview), the "X" and "Close" buttons that are supposed to close the config window do not do anything. You can however close the window by pressing the escape key or by clicking outside the config window. 

### Expected Behavior

The "X" and "Close" buttons should close the window. 

### Steps to Reproduce

Open File Browser or Photoview.
Press the config button.
Try pressing the "X" and "Close" buttons.

**Comment by MattDHill** [comment]
Thanks for the report. This is already fixed in the latest code and will be part of the upcoming release.
