### ISSUE TITLE
[feat]: Open All External Links in New Tabs

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1778]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

External links in instructions, release notes, etc, should always open in a new tab by default

### Describe the Use Case

Sanity

**Comment by MattDHill** [comment]
This is the convention. Which links are not opening in new tabs?

**Comment by kn0wmad** [comment]
Marketplace listing "New in version" release notes for any service in my testing

**Comment by MattDHill** [comment]
Done
