### ISSUE TITLE
[feat]: Switch marketplace in marketplace tab

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#1817]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Currently you have to go into the Embassy tab then click "marketplace settings"

To me a more natural place is within the martketplace itself or to at least have it there in addition.

### Describe the Use Case

Switch marketplace easily when you realized you clicked on marketplace and were on the wrong marketplace.

**Comment by elvece** [comment]
Copy is "switch marketplaces" as opposed to "settings"
