### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1818]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### EmbassyOS Version

0.3.2

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

ERROR A thread failed with error: Could not prepare an sqlite statement.

This occurs when importing drive (add drive) on initial setup

### Expected Behavior

No errors on setup

### Steps to Reproduce

1. On initial setup
2. Recover
3. Attach drive

**Comment by MattDHill** [comment]
Believe this is something we have to deal with via restart.

**Comment by kn0wmad** [comment]
There is no possible solution here?

**Comment by MattDHill** [comment]
Perhaps I'm misunderstanding the issue. I'm under the impression this happens when updating from 0311 to 032. If so, then no, there is nothing we can do because this is an issue with sqlite, switching to postgres solves

**Comment by kn0wmad** [comment]
Sorry, that would be a non-issue then.  @dr-bonez and I spoke about making the messaging a bit more clear, which he may have already done.  Regardless, we'll be ready support-side
