### ISSUE TITLE
[feat]: 0.3.2 Upgrade from 0.2.x "Restore From Backup" option needs more inclusive description

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/embassy-os#1838]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

![upgrade_from_02x-step2-should_mention_upgrading_migration](https://user-images.githubusercontent.com/106188942/192696599-5187af21-6bd2-4145-9655-1663bbdc1e1b.jpg)

^In the upgrade-from-0.2.x flow we should probably mention something on this screen to indicate that they will find their Embassy 0.2.x microsd card by selecting the first option.

### Describe the Use Case

When the user is upgrading from 0.2.x, they are presented with "Restore From Backup" or "Use Existing Drive".  Might be kinda confusing since they never actually made a backup.

### Describe Preferred Solution

Perhaps "Recover an Embassy from an encrypted backup"
could change to:
"Recover an Embassy from an encrypted backup or Upgrade from 0.2.x"

**Comment by MattDHill** [comment]
I don't want to pollute the Setup Wizard with 02x messaging. There are very few remaining 02x users. We can include a screenshot of which button to click in the upgrade guide.
