### ISSUE TITLE
[bug]: LAN Interfaces limited to ~20

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1862]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.2

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.19

### Browser

Firefox

### Browser Version

102

### Current Behavior

Running more than ~20 LAN interfaces breaks Avahi:

Could not add CNAME record to Avahi entry group: "Too many entries"
thread 'main' panicked at 'Failed to load Avahi services', src/bin/avahi-alias.rs:98:17

### Expected Behavior

Can run at least as many LAN interfaces as are available on prod market

### Steps to Reproduce

1. Run 20+ LAN interfaces
2. All LAN interfaces go down

**Comment by tinysound464** [comment]
Please check [here](https://manpages.debian.org/testing/avahi-daemon/avahi-daemon.conf.5.en.html).

If I am reading this correctly, I believe you may be able to utilize the following to adjust the maximum mdns records per client:
`objects-per-client-max= Takes an unsigned integer. The maximum number of objects (entry groups, browsers, resolvers) that may be registered per D-Bus client at a time. If the maximum number is reached further object creation will be refused until at least one object is freed.`

**Comment by chrisguida** [comment]
Was this fixed by https://github.com/Start9Labs/embassy-os/pull/1869?

**Comment by MattDHill** [comment]
Yes
