### ISSUE TITLE
[bug]: Tor not self-healing properly

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1872]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

032

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.19

### Browser

Firefox

### Browser Version

102

### Current Behavior

See internal dev discussion for details.  @redragonx has a box in this state currently

### Expected Behavior

Tor self-heals

### Steps to Reproduce

@redragonx

**Comment by redragonx** [comment]
![image](https://user-images.githubusercontent.com/3073252/200922217-89bafa49-45f6-4a14-9db8-5ecef5827b84.png)

**Comment by redragonx** [comment]
my pr should work like this below,

![image](https://user-images.githubusercontent.com/3073252/200970587-17ee2769-15a4-4300-beb7-f513b1b336f6.png)

**Comment by redragonx** [comment]
PR merge done
