### ISSUE TITLE
Testing Plan

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1883]
# PI

- [x] Fresh Setup (Matt)

### Attach
- [x] 0321 - ensure DB migrations worked as expected (Lucy - rc9)
- [x] 033 (Lucy - rc9)

### Transfer
- [x] 0321 -> 033 (Matt)
- [ ] 033 -> 033 

### Restore from backup (full system)
- [x] cifs Mac (with a backup from 0321 or 033) (Lucy rc-10)
- [ ] cifs Windows (with a backup from 0321 or 033)
- [x] cifs Linux (with a backup from 0321 or 033) (BLUJ)
- [x] cifs 0321 -> 033 (on any machine) (Lucy - rc10)
- [x] cifs from 033 -> 033 (on any machine) (Lucy - rc10)
- [x] physical from 0321 -> 033 (Lucy - rc10)
- [x] physical from 033 -> 033 (Lucy - rc9 - no bad services)
- [x] from pro -> pi (Lex)

### Restore from backup (services only)
- [x] cifs Mac (Lucy rc-9)
- [ ] cifs Windows
- [x] cifs Linux (George)
- [x] cifs 0321 (George)
- [x] cifs 033 (Lucy - rc9)
- [x] physical 0321 (Lucy - rc9)
- [x] physical 033 (Lucy - rc9)

# PRO

- [x] Fresh Setup (Matt)
- [x] Update OTA (Matt)

### Attach
- [x] 033 (Dave)

### Transfer
- [x] 0321 (Matt)
- [ ] 033 (Dave)

### Restore from backup (full system)
- [ ] cifs Mac (with a backup from 0321 or 033) - (Lucy)
- [x] cifs Windows (with a backup from 0321 or 033) - (Dave 0321)
- [x] cifs Linux (with a backup from 0321 or 033) - (George 0321)
- [x] cifs 0321 -> 033 (on any machine) (George)
- [x] cifs from 033 -> 033 (on any machine) (Dave)
- [x] physical 0321 from pi -> 033 pro (George)
- [ ] physical 033 from pi to pro

### Restore from backup (services only)
- [x] cifs Mac (Mariusz)
- [x] cifs Windows (Dave)
- [x] cifs Linux (George)
- [x] cifs 0321 (George)
- [x] cifs 033 (Dave)
- [x] physical 0321 (George)
- [x] physical 033 (Mariusz)

**Comment by kn0wmad** [comment]
ACK, standing by

**Comment by kn0wmad** [comment]
Beginning testing on an array of hardware

**Comment by kn0wmad** [comment]
I'm realizing this may need to wait until a more finalized image?  I will test all these functionalities, but they should probably not receive a checkmark until tested on a feature-complete RC
