### ISSUE TITLE
[bug]: Cannot curl my Embassy A from the SSH of my Embassy B

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/embassy-os#1889]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.2.1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Monterey

### Browser

Other

### Browser Version

tmux

### Current Behavior

```

MacMax:Repos dread$ ssh start9@embassy-scarce-yawns.local

Welcome to
          |                        ,---.,---.
,---.,-.-.|---.,---.,---.,---.,   .|   |`---.
|---'| | ||   |,---|`---.`---.|   ||   |    |
`---'` ' '`---'`---^`---'`---'`---|`---'`---'
                              `---'
   GNU/Linux (5.10.92-v8+ aarch64)
   embassyOS v0.3.2.1 - 2f8a25ae2679a11161c7f3cc70be04ecedfbea1b

 * Documentation:  https://start9.com
 * Management:     https://embassy-scarce-yawns.local
 * Support:        https://t.me/start9_labs

start9@embassy-scarce-yawns:~ $ curl faded-soaps.local
curl: (6) Could not resolve host: faded-soaps.local
```

### Expected Behavior

```
curl faded-soaps.local
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

### Steps to Reproduce

1. Start Embassy A
2. SSH into Embassy A
3. `curl embassy-b.local`

**Comment by islandbitcoin** [comment]
Additional information: the curl was working before I started the migration process. tried a system rebuild, no luck.

```
start9@embassy-f5fb24ed:~ $ curl faded-soaps.local
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
start9@embassy-f5fb24ed:~ $ sudo -i
root@embassy-f5fb24ed:~# mkdir -p .ssh
root@embassy-f5fb24ed:~# ssh-keygen -t ed25519 -N '' -f .ssh/embassy2.key
Generating public/private ed25519 key pair.
Your identification has been saved in .ssh/embassy2.key
Your public key has been saved in .ssh/embassy2.key.pub
The key fingerprint is:
[REDACTED] root@embassy-f5fb24ed
The key's randomart image is:
+--[ED25519 256]--+
|.E==o.           |
| *+oo            |
|..oo             |
|  o      o o     |
| . .  . S = .    |
| ....+ . . =     |
|. ==+.o o * o    |
|.+oO=  . * +     |
|..=oo. o= .      |
+----[SHA256]-----+
root@embassy-f5fb24ed:~# chmod 600 .ssh/embassy2.key*
root@embassy-f5fb24ed:~# cat .ssh/embassy2.key.pub
ssh-ed25519 [REDACTED] root@embassy-f5fb24ed
root@embassy-f5fb24ed:~# cd /embassy-data/package-data/volumes/bitcoind/data/main/
root@embassy-f5fb24ed:/embassy-data/package-data/volumes/bitcoind/data/main# rsync -e "ssh -i ~/.ssh/embassy2.key" -povgr --append-verify --rsync-path="sudo mkdir -p /embassy-data/package-data/volumes/bitcoind/data/main ; sudo rsync" ./{blocks,chainstate} start9@faded-soaps.local:/embassy-data/package-data/volumes/bitcoind/data/main/
ssh: Could not resolve hostname faded-soaps.local: Temporary failure in name resolution
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(228) [sender=3.2.3]
root@embassy-f5fb24ed:/embassy-data/package-data/volumes/bitcoind/data/main# curl faded-soaps.local
curl: (6) Could not resolve host: faded-soaps.local
root@embassy-f5fb24ed:/embassy-data/package-data/volumes/bitcoind/data/main#

```

**Comment by dr-bonez** [comment]
unable to reproduce

**Comment by islandbitcoin** [comment]
I just recreated it again on my 0.3.3
![Screenshot 2022-11-27 at 6 45 03 PM](https://user-images.githubusercontent.com/34528298/204166181-790be71e-5545-44d1-9f11-10d32ac265f1.png)

**Comment by kn0wmad** [comment]
> I just recreated it again on my 0.3.3 ![Screenshot 2022-11-27 at 6 45 03 PM](https://user-images.githubusercontent.com/34528298/204166181-790be71e-5545-44d1-9f11-10d32ac265f1.png)

What did you do to repro?

**Comment by islandbitcoin** [comment]
> 

nothing more than what's in the screenshot.

I have the crime scene if you want to dig in

**Comment by kn0wmad** [comment]
I was hoping you had reproduced since this is the only instance we have - have you gone through avahi to make sure it's healthy?  Can you curl by IP?

**Comment by MattDHill** [comment]
Please reopen if you can reproduce and demo

**Comment by islandbitcoin** [comment]
I can reproduce and demo, and have many times, which is what the screenshot is above.
Let me know what other steps are needed.

**Comment by k0gen** [comment]
@islandbitcoin it is not working because you are missing `embassy-` the proper command is:
```
curl embassy-faded-soaps.local
```

**Comment by islandbitcoin** [comment]
no, my box was made when we didn't have `embassy` as the prefix, so the name is correct.

**Comment by islandbitcoin** [comment]
I've also tried this between two boxes that have the name `embassy-xxxx-xxxx` and `embassy-xxxx-xxxx`

**Comment by kn0wmad** [comment]
@islandbitcoin reproduce means on systems that don't currently have this problem - not just recreating on the existing problem systems.  Have you been able to repro on other systems besides the first ones?

**Comment by islandbitcoin** [comment]
understood. I'll leave this alone, it looks like it's specific to my network.
