### ISSUE TITLE
[bug]: Selecting Autoscroll on Logs does not persist

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1902]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.2.1

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

6.0

### Browser

Other

### Browser Version

99

### Current Behavior

1. Turn on "Autoscroll" feature in service Logs
2. Leave logs page
3. Return to logs page
4. See bug

### Expected Behavior

Autoscroll selection persists across page visits

### Steps to Reproduce

1. Turn on "Autoscroll" feature in service Logs
2. Leave logs page
3. Return to logs page
4. See bug

### Anything else?

This is very annoying when trying to troubleshoot / debug

**Comment by MattDHill** [comment]
Please state what the bug is. Suspense is killing me.
