### ISSUE TITLE
[bug] graceful websockets closures displays as errors

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1916]
![image](https://user-images.githubusercontent.com/39687477/200689192-d4cf6905-3608-462d-ac84-1c001d180a2e.png)

No symptoms during this occurrence 
v033, Embassy Pro

Don't log as an error if websocket closed in an unexpected way?

**Comment by MattDHill** [comment]
This ticket is less about the frequency of closing websockets and more about the closures logging as errors. If a websocket closes gracefully, it should not display as an error.
