### ISSUE TITLE
[bug]: Marketplace icons are not displaying 

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#1936]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

next

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

all of them

### Browser

Firefox

### Browser Version

1

### Current Behavior

![Screenshot from 2022-11-10 17 23 56](https://user-images.githubusercontent.com/3606313/201156074-db7c8d1e-125b-4004-b000-11c6a533fa8c.png)

### Expected Behavior

a

### Steps to Reproduce

a

### Anything else?

a

**Comment by MattDHill** [comment]
This is actually not a problem. Those icons can be expected to always be there once the registry is updated.
