### ISSUE TITLE
Service Actions

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#194]
On AIS, there will be a new property called `actions` which is an object of the following structure:
```typescript
interface Actions {
    [id: string]: Action
}

interface Action {
    name: string
    description: string
    allowedStatuses: AppStatus[]
}
```

Below Properties, there should be a button called "Actions".

When clicked, it should show a list of available actions, showing the `name` attribute of each action on the `actions` object.

If the app is not in one of the `allowedStatuses` grey the action out.

If one of those actions is selected, show a confirmation dialog with the `description` of the action.

If they select ok, POST to `/v0/apps/${appId}/actions` with a [JSON RPC 2.0](https://www.jsonrpc.org/specification) request:

request:
```js
{
    "jsonrpc": "2.0",
    "id": 0, // can be anything
    "method": "reset-password" // the key associated with the action
}
```

respose:
```js
{
    "jsonrpc": "2.0",
    "id": 0, // same id as in request
    "result": "Your new password is: \"abcdefg\"" // a response to show in an alert
}
```
OR
```js
{
    "jsonrpc": "2.0",
    "id": 0, // same id as in request
    "error": {
        code: 1,
        message: "Password could not be reset."
    }
}
```

**Comment by MattDHill** [comment]
I think it might be better to have a tool tip (question mark) to explain the action before clicking it. Then a confirm dialog after click, (ie "are you sure you want to <action>")

**Comment by dr-bonez** [comment]
Sure, but I want to make sure the description gets read if they perform the action. It could have important information. I'm fine with also adding the tooltip though.

**Comment by afg419** [comment]
Can we flatten the types?

I don't see any reason for the FE to be doing id lookups, but a list is convenient for how we're displaying

Actions = Action[]
Action {
    id: string,
    name: string,
    description: string,
    allowedStatuses: AppStatus[]
}

**Comment by dr-bonez** [comment]
yeah, happy to do that
