### ISSUE TITLE
[bug]: Service persists in stuck state when uninstall/installing

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1947]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

v0.3.3@b885022a17b80c63c04e452a622e3b3987aa8bc9

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

### Browser

Firefox

### Browser Version

106.0.5

### Current Behavior

This problem manifests in a two scenarios. When either (1) uninstalling or (2) installing a service, the service will freeze in either (1) "removing" state or (2) "installing...finalizing" state. A restart of embassyd fixes. Relevant logs added below. 

### Expected Behavior

Both processes should complete in a reasonable timeframe. 

### Steps to Reproduce

Attempt to uninstall a service
See it gets permanently stuck in "Removing" state. 
Fix by restarting embassyd (`systemctl restart embassyd`)

### Anything else?

Relevant eOS logs:

```
Nov 15 17:06:28 embassy-butch-ribs embassyd[22151]: 2022-11-15T17:06:28.200195Z ERROR embassy::procedure::docker: The docker pipe is closed?
Nov 15 17:06:28 embassy-butch-ribs embassyd[28589]: AvahiCallback: ClientState = AVAHI_CLIENT_S_RUNNING
Nov 15 17:06:28 embassy-butch-ribs embassyd[28589]: AvahiCallback: EntryGroupState = AVAHI_ENTRY_GROUP_UNCOMMITED
Nov 15 17:06:28 embassy-butch-ribs embassyd[28589]: Published "embassy-butch-ribs.local"
Nov 15 17:06:28 embassy-butch-ribs embassyd[28589]: Published "l3jl3qqdgjki5iwar442smc4sxacv4tkui6wbtuiwmtvy2uq2m2wkgad.local"
Nov 15 17:06:28 embassy-butch-ribs embassyd[28589]: Published "ttko7aojv7gezkv5iby2j3cgy3qwonvl2avi7zbjl6zbbmxcpxcqa3qd.local"

**Comment by elvece** [comment]
Similar but different: https://github.com/Start9Labs/embassy-os/issues/1928

**Comment by dr-bonez** [comment]
This is for lonng-running. Punting to 0.3.3.1

**Comment by MattDHill** [comment]
related #2052

**Comment by MattDHill** [comment]
Should be fixed
