### ISSUE TITLE
[bug]: Logs Do Not Always Stay Defaulted to "Autoscroll"

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1972]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

6.0

### Browser

Firefox

### Browser Version

102

### Current Behavior

Possibly related to the speed of logs created.  Seems to happen more often on heavy pages, such as OS or Bitcoin logs.  Not so much on Kernel logs for example.

### Expected Behavior

Autoscroll stays on 

### Steps to Reproduce

1. Click OS logs
2. Autoscroll disables

**Comment by MattDHill** [comment]
dup of #1902
