### ISSUE TITLE
[bug]: marketplace search bug

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1973]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

033

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Uwiwiw

### Browser

Firefox

### Browser Version

Ueieiw

### Current Behavior

happening now on alpha

1) click marketplace, it takes you to "featured"
2) search for "jet"
3) everything disappears
4) click on "all"
5) now i can see jet

### Expected Behavior

Services should show up regardless of what category I'm in 

### Steps to Reproduce

1) click marketplace, it takes you to "featured"
2) search for "jet"
3) everything disappears
4) click on "all"
5) now i can see jet

**Comment by waterplea** [comment]
Do we want to «deselect» category, while there is something in search field, kinda like we're in a pseudo category of search results?
