### ISSUE TITLE
[feat]: Multi-select services and be able to run actions on multiple services

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/embassy-os#1994]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

I want to be able to select 2 or more services, and then have the option to run all actions with the same name on those services. The uninstall action would be the minimum action that can be used, since all services have an uninstall action.

An "update if available" action would be helpful too.

### Describe the Use Case

going one by one to uninstall services can be time consuming. 
selecting multiple services and then uninstalling them all at once would save time, allowing the OS to control the sequence of uninstalling.

### Describe Preferred Solution

Multi-select mode can be enabled on services page
Dynamic drop-down on services page appears once multi-select mode is enabled

**Comment by MattDHill** [comment]
This is most useful for devs and only really safe for uninstall. Script from CLI seems best

**Comment by islandbitcoin** [comment]
agreed, CLI script would be useful alternative.
