### ISSUE TITLE
[feat]: Ability to generate config from spec on BE

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#2015]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

When the package dev writes a "configured: true" (or possibly some variation of this) migration, automatically fill in the defaults for new config fields instead of failing the install.

### Describe the Use Case

Currently, when a new version contains new config fields and the package dev returns "configured: true" from the migration, the install will fail with a message like this:

`Install of sphinx-relay@2.2.10 Failed: Config Generation Error: No Match: password: Field Is Not Nullable`

Where the field looks like this in the config spec:

```
  "password": {
    "type": "string",
    "name": "Password",
    "nullable": false,
    "copyable": true,
    "masked": true,
    "default": {
        "len": 22,
        "charset": "a-z,A-Z,0-9"
    }
  }
```

It's onerous to write a migration for this, when the spec for generating a random password exists right there in the spec. Why not just generate a default password on install and save the user from needing to hit "save" on the config? This saves work for the package developer *and* the user. It also prevents the service from stopping, when the only reason we stopped the service in the first place was to direct the user to the new fields. #1708 solves this, so we might want to implement that first.

### Describe Alternatives

maybe something explicit, like `configured: default`

### Anything else?

Maybe this isn't a good idea. The error message can prevent the developer from adding new unnecessary keys accidentally

**Comment by MattDHill** [comment]
Doing the opposite, it's in SDK

**Comment by chrisguida** [comment]
This is solved by removing the `config.yaml` intermediate representation
