### ISSUE TITLE
[feat]: UI Note for SSH access

### ISSUE THREAD

**Issue by crc32** [Start9Labs/embassy-os#2073]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Hey, one UI note I just noticed. On the SSH page (under System), it may be nice to have a copy field which pre-populates with the SSH command.

Or at least put a note there that the SSH login user is `start9`. I found it easily in the linked instructions, but assumed it would be `root` since when adding a key it says "Enter the SSH public key you would like to authorize for root access to your Embassy."

But I’m thinking maybe a copy field that contains:
`ssh start9@<embassy-name.local> -i ~/.ssh/<your SSH private key>`
or something?

### Describe the Use Case

Just something to make SSH access a little more frictionless for those that know how/why they want it. I assume if someone knows enough to add a key to the SSH setup they will know how to use SSH properly.

**Comment by crc32** [comment]
You could even include `torify ssh start9@<SSH Onion Address> -i ~/.ssh/<private key>` for someone who wants to use SSH over TOR, but that could be a potential security hole...

**Comment by MattDHill** [comment]
The isntructions have improved since this ticket was created. I prefer to keep them separate from the UI for the time being. That way they can be updated out of band from embassyOS updates.
