### ISSUE TITLE
[feat]: Support EFI Boot

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#2080]
Some BIOS will not allow Legacy boot media - this will open up the range of DIY hardware available

**Comment by fp** [comment]
Isn't this as simply as changing the default installation partition table type?

**Comment by chrisguida** [comment]
@fp It would be great if you could test your solution and report back

**Comment by kn0wmad** [comment]
> Isn't this as simply as changing the default installation partition table type?

No, it is not this simple.  To be clear (and I've edited the issue title to reflect this), this is for OS boot, not boot media.
