### ISSUE TITLE
[feat] eOS ought to recognize requests for `0.0.0.0` and redirect them to `https://service.embassy`

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#2081]
This is a problem in some services, such as IPFS for example

**Comment by chrisguida** [comment]
I don't think this is something eOS can intercept, 0.0.0.0 goes to localhost

**Comment by dr-bonez** [comment]
We're not rewriting page uis in the os. this is a service specific problem

**Comment by chrisguida** [comment]
I don't think there is anything eOS can do about this anyway. The request goes to localhost, not to the embassy.
