### ISSUE TITLE
[bug]: Don't allow clicking the update button when an ongoing update is running.

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#2088]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

macOS Ventura

### Browser

Firefox

### Browser Version

any

### Current Behavior

When updating many services at the same time it might happen that a user simply forgets that the update is already running under the hood and click update again.

It will end up displaying:
```
RPC ERROR: Invalid Request Cannot install over a package in a transient state
```
<img width="1004" alt="Screenshot 2022-12-22 at 11 59 13" src="https://user-images.githubusercontent.com/3606313/209120021-9b7b64f1-0ad6-44d9-89f7-055dc9dc9450.png">

### Expected Behavior

This error should be handled more gracefully, like making the Update button gray (un-clickable) or making it display: updating...

### Steps to Reproduce

1. Start a bigger service update (like Mastodon)
2. Forget about what you just did in step 1 :)
3. Click Update again

**Comment by MattDHill** [comment]
Already fixed on master
