### ISSUE TITLE
[bug] Error during DIY initiallization: WiFi internal error

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#2092]
RPC Error: wifi internal error wlx200db0214b2f: ERROR while getting interface flags: No such device Restart Embassy to try again.

Lenovo 710q tiny

**Comment by dr-bonez** [comment]
We currently commit to wifi interface names during os install. evidently the interface name is changing on this device. I don't think we should prioritize fixing this for 0.3.3.1, but we will put this in the backlog

**Comment by kn0wmad** [comment]
This problem ended up being a wifi dongle - its removal lead to a successful install.  I would be in favor of closing this in favor of #2078, but need concept ACK
