### ISSUE TITLE
[feat]: Option to remove a marketplace you no longer want

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#2095]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Self explanatory. Please delete if this is already possible in the GUI. If it's possible via CLI/webtools I suggest making it possible in the GUI too.

### Describe the Use Case

If you have a marketplace you no longer want. It might bug you about updates you're not interested in until they reach prod for example.

**Comment by k0gen** [comment]
<img width="519" alt="Screenshot 2022-12-29 at 13 26 34" src="https://user-images.githubusercontent.com/3606313/209951005-7518c771-ab6c-455a-9fda-2f27bbc1901d.png">
Do you mean this? 👆

Obviously, you are not allowed to remove Start9 official marketplace, but it might be less obvious that you are also not allowed to remove the marketplace you are currently connected to.
Switch to the official marketplace -> then click the marketplace you want to delete.

**Comment by kn0wmad** [comment]
Closing as invalid
