### ISSUE TITLE
[bug]: embassyOS Setup's Password confirmation field is not length restricted

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/embassy-os#2097]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

v0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5

### Browser

Firefox

### Browser Version

108

### Current Behavior

A user wrote us:

> when making a password during setup the first text box limits the maximum # of characters and the second does not. Wasn’t sure why my pasted password wasn’t matching at first until I revealed and inspected. 
>

### Expected Behavior

Both password and password confirmation text boxes should limit the # of chars.  We should probably also have a tooltip about the password length (and any complexity) constraints.

### Steps to Reproduce

Setup embassy OS
Proceed to Set Password screen
Paste a very long password into both fields

**Comment by kn0wmad** [comment]
Tooltip regarding password constraints is a great feature - this will be useful to users that like to max out passwords
