### ISSUE TITLE
[bug]: Pro (prod box) weird issues after a backup, service stuck in paused state

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#2126]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

12.5

### Browser

Firefox

### Browser Version

108.0.2

### Current Behavior

Here is a rough list of what happened - I didn't collect the most helpful info as my priority was to try and get my CLN back online as quickly as possible:

Backup everything
Notification said it completed successfully
RTL was showing broken webUI health check
Restarted RTL to fix it as UI actually wouldn't load
Restart hung forever in the UI
Soft restarted Embassy (clicked restart in system tab)
RTL state remained
ssh in -> docker ps showed RTL in paused state
Restarted embassyd from CLI
docker ps showed no containers at all EXCEPT rtl - no interfaces would load at all
tried to manually kill RTL container - just hung
did system rebuild - probably didn't do anything
yanked power, it did the rebuild and now everything seems to work, but RTL is "stopped" and I'm scared to start it again

### Expected Behavior

.

### Steps to Reproduce

.

**Comment by MattDHill** [comment]
Adding to 0331 but I believe this has already been identified and fixed last week.
