### ISSUE TITLE
Iso doesn't boot on mini pc with a Celeron cpu

### ISSUE THREAD

**Issue by greenart7c3** [Start9Labs/embassy-os#2136]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

Other

### Device OS Version

Embassy os 0.3.3

### Browser

Firefox

### Browser Version

1

### Current Behavior

When booting in a Celeron n5105 cpu I have to add this to the boot params to work

I915.force_probe=4e61

### Expected Behavior

Boot without having to add params to the bootloader

### Steps to Reproduce

Write embassy to USB drive
Try booting it with a n5105 cpu

**Comment by kn0wmad** [comment]
You may wish to post [here](https://community.start9.com/c/troubleshooting) to see if anyone else in the DIY community has run into this issue

**Comment by greenart7c3** [comment]
> You may wish to post [here](https://community.start9.com/c/troubleshooting) to see if anyone else in the DIY community has run into this issue

I'll post there too. I think this mini pc needs a newer kernel, I had the same problem on [Debian](https://forums.debian.net/viewtopic.php?t=152124)

**Comment by kn0wmad** [comment]
Thinking back on this, it is not possible to support all possible hardware configurations.  This ticket probably ought to be closed in favor of Community or Docs posts / guides for dealing with boot issues, such as adding bootloader params.

@greenart7c3 - can you post your hardware to [this list](https://community.start9.com/t/known-good-hardware-master-list-hardware-capable-of-running-embassyos-v0-3-3) and I'll add it as "known good" with the caveat.

**Comment by greenart7c3** [comment]
https://community.start9.com/t/known-good-hardware-master-list-hardware-capable-of-running-embassyos-v0-3-3/66/27?u=greenart7c3

**Comment by kn0wmad** [comment]
Thanks, closing
