### ISSUE TITLE
[feat]: enable kiosk mode on raspi4

### ISSUE THREAD

**Issue by AndySchroder** [Start9Labs/embassy-os#2143]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Would like the option to enable kiosk mode on the raspi4. Why is this not enabled by default? Is there some hardware limitation?

### Describe the Use Case

I'd like to use my bitcoin node build: http://andyschroder.com/DistributedCharge/news/2022.06.04-RaspiBlitzOnTheTOFU/ . Currently I'm running raspiblitz, but I'd like to demonstrate it with embassy. The built in screen in my build is a perfect use case for kiosk mode.

**Comment by chrisguida** [comment]
The reason this isn't implemented is because we were not able to quickly find a reliable way to detect when the monitor is attached and when it is detached. This causes Firefox to sometimes run, taking a large a mount of RAM, even when the monitor is not plugged in.

This is not to say that there are no reliable detection methods, just that the ones we considered were not trivial.

**Comment by AndySchroder** [comment]
Thanks for the clarity. A few options that would be acceptable to me:

- Manual activation and deactivation of kiosk mode via a config file.
- Require the user to log in after each boot in order to start up firefox.
- Have a lightweight text based kiosk instead of firefox that doesn't use much RAM.

**Comment by dr-bonez** [comment]
ssh in, then run
```
sudo -i # escalate to root
/usr/lib/embassy/scripts/chroot-and-upgrade # chroot into RW filesystem
/usr/lib/embassy/scripts/enable-kiosk # enable kiosk
echo '#!/bin/sh' > /usr/lib/embassy/scripts/check-monitor # hardcode monitor presence to true
```

happy hacking

**Comment by AndySchroder** [comment]
This works, but with the following caveats:

- You need to remotely go through the web based UI completely first, otherwise it will just give a blank screen.
- Monitor still goes into power save mode after a while.
- Can't log in to a shell via the console anymore, only via ssh. Seems to me like there should be a new username for the kiosk mode.

**Comment by chrisguida** [comment]
@AndySchroder feel free to make some feature requests

**Comment by AndySchroder** [comment]
Also, after getting start9 up and running, it looks like the 800x480 screen in the build shown at http://andyschroder.com/DistributedCharge/news/2022.06.04-RaspiBlitzOnTheTOFU/ is too small with the way your web GUI is currently layed out. So, unfortunately none of the web pages are compact enough to show a meaningful status page.

**Comment by kn0wmad** [comment]
> Also, after getting start9 up and running, it looks like the 800x480 screen in the build shown at http://andyschroder.com/DistributedCharge/news/2022.06.04-RaspiBlitzOnTheTOFU/ is too small with the way your web GUI is currently layed out. So, unfortunately none of the web pages are compact enough to show a meaningful status page.

Can you screenshot this?  The UI should adapt to any screen size (although it may not look very good on some sizes).

**Comment by AndySchroder** [comment]
Here's the default view. It works, but not a very high density amount of information.
![image](https://user-images.githubusercontent.com/4065710/223328983-e2589d2d-dd1a-4e16-8137-9e52d839617b.png)

I can zoom out and it shows a bit more.
![image](https://user-images.githubusercontent.com/4065710/223329355-3a1bbb44-58c4-47c7-9b08-6cfbb51f7cb0.png)

However, something much higher density like this layout might be super useful (ignore the actual fields here, we'd want to see all kinds off stuff about your node summarized, but I'm just trying to show the layout).
![image](https://user-images.githubusercontent.com/4065710/223329472-abffe5cc-a7f0-480f-8b56-bd676ddc2b65.png)


Note, all of these examples are taken from a desktop computer and not the actual embassy, just because it's easier to screenshot, so there will be a few more pixels because of the window decorator not existing on the embassy in kiosk mode.

**Comment by kn0wmad** [comment]
Okay, so to clarify, rather than a bug report this is in regard to excessive empty space.  We are aware of this and a complete redesign of the UI is underway.  Keep an eye out later this year for that update.

**Comment by AndySchroder** [comment]
Yes, my last comment was more a visual observation than a bug report.
