### ISSUE TITLE
[feat]: Provide a way (in Bitcoin/Actions) to manually add peers/nodes (for potentially quicker IBD)

### ISSUE THREAD

**Issue by smartsourcefreak** [Start9Labs/embassy-os#2160]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

In Services/Bitcoin Core/Actions provide an entry "Add Peer". Clicking it opens another page similar to the "SSH Keys" page where it's possible to "+ Add New Peer". A Textbox pops up demanding the [Address:Port] of a listening Bitcoin fullnode. The feature is already impemented within Bitcoin Core "addnode [IP:Port] add" and "just" needed to be implemented in the Embassy WebGui.

### Describe the Use Case

When running another fullnode on the same Local Network - or with the knowledge of a another fullnode with high upload bandwidth a much faster Initial Blockchain Download would be possible.

### Describe Alternatives

Alternatively/Additionally provide a way implemented in the WebGui to set Embassy "Listening" for a rsync copy process from another server in the local network _before_ having Bitcoin Core started the first time. In Services/Bitcoin Core/Actions provide an entry "Copy Blockchain via SSH" to set Embassy in "Listening for copy" state and a "Done" Button. A textfield showing the folowing hint:

**On your source machine SSH into your bitcoin directory and start the copy process by executing 

sudo rsync -avhW --progress ./chainstate ./blocks [Your.Embassy.Address]:/mnt/hdd/bitcoin

in your CLI. Once the process is finished hit the "Done" Button.**

The actual Bitcoin IBD would sync onto the already copied/verified Blockchain-data.

**Comment by MattDHill** [comment]
This is already possible inside Config.

Go to Advanced -> Peers -> Add Nodes
