### ISSUE TITLE
[feat] Give Dowloaded LAN Cert Files Unique Names

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#2179]
Everyone that sets up more than one Embassy will thank you.

Low Priority.

Stretch goal - name certs (including subsequent Intermediates, etc) with unique Embassy name such that they can be found in the Authorities list in browsers

**Comment by chrisguida** [comment]
Yes please!

**Comment by chrisguida** [comment]
The certs themselves are named uniquely, but the *filenames* are named `embassy.crt`
