### ISSUE TITLE
[bug]: Updates page: updating services lose their processing state on refresh and navigation

### ISSUE THREAD

**Issue by spencerflagg** [Start9Labs/embassy-os#2180]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Pop!_OS 22.04 LTS

### Browser

Brave

### Browser Version

Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)

### Current Behavior

On the Updates page, on services that are currently processing an update, the **update** button becomes a spinner. However when the page is refreshed and/or when the user leaves and returns to the page, the spinner is gone and the **update** button is back. (During which time, the update is still processing - as evidenced by the blue installation label by the service on the Services page.)

If the user clicks the **update** button while the update is still processing, an `RPC Error` will be thrown in the service's card.

### Expected Behavior

The _processing_ state of the update should persist across pages.

### Steps to Reproduce

1. On the Updates page
2. Update a service by clicking the white **update** button, and notice the spinner in the service's card
3. refresh the page and/or navigate to another page and return to the Updates page
4. Notice the spinner in the service's card is hidden and the **update** button is visible.

**Comment by kn0wmad** [comment]
I believe this is fixed in the upcoming release - @MattDHill can confirm.

**Comment by MattDHill** [comment]
It is
