### ISSUE TITLE
[bug]: Skeleton Screens with "Request failed" show on Updates page (possible old beta services?)

### ISSUE THREAD

**Issue by spencerflagg** [Start9Labs/embassy-os#2181]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.3

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Pop!_OS 22.04 LTS

### Browser

Brave

### Browser Version

Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (64-bit)

### Current Behavior

Two skeleton screens with the text "Request Failed" and house icons are showing up on my Updates page. (image below)

My guess is these were beta marketplace services that broke during the last update.

![image](https://user-images.githubusercontent.com/5099192/223526042-b43ba7bf-95d8-4bb6-b4e1-d4ca6c15d402.png)

### Expected Behavior

If these are indeed relics of obsolete services, then they should be automatically cleared or the user should be given the option to clear them.

### Steps to Reproduce

(maybe)
1. Start on v0.3.1 or v0.3.2
2. Change marketplace to alpha or beta
3. Add an alpha or beta service
4. Change the marketplace back to the Start9 Registry
5. Upgrade to v0.3.3
6. Return to Updates page
7. See the skeleton :skull: ?

**Comment by kn0wmad** [comment]
Yes, you need to remove the old alt market URLs as they are no longer valid.  Closing as invalid

**Comment by spencerflagg** [comment]
@kn0wmad :+1: Ahh, thanks, that got rid of the skeletons.
