### ISSUE TITLE
[bug]: Safari opens service UIs in new windows instead of new tabs

### ISSUE THREAD

**Issue by sugarjig** [Start9Labs/embassy-os#2243]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem.

### embassyOS Version

0.3.4~1

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

13.2.1

### Browser

Safari

### Browser Version

16.3 (18614.4.6.1.6)

### Current Behavior

When clicking on the link to open a service's UI, the browser opens a new window and loads the UI.

### Expected Behavior

I expect the browser to open a new tab in the same window as the Embassy OS UI.

### Steps to Reproduce

1. Log in to Embassy OS
2. Go to Services
3. Click on any service's UI link
4. Observe that the UI is loaded in a new browser window

### Anything else?

I tested in Firefox and saw that it opened a new tab for service UIs. I tried multiple services in both Safari and Firefox. Safari consistently opens new windows. Firefox consistently opens new tabs.

**Comment by kn0wmad** [comment]
We engineer mainly for (and highly recommend) Firefox.  We'll take a look at this and see if it's something we can fix.

**Comment by MattDHill** [comment]
The code to govern this is simply `target="_blank"` which tells the browser to open the link elsewhere. The default for most (if not all browsers) is a new tab. However, I believe you can override this behavior in browser settings, such that links are opened in new windows as opposed to new tabs. In other words, check your Safari settings. Either Safari defaults to opening links in new windows or you changed it to behave that way. Either way, there is nothing we can do in code to change the behavior. It's a browser thing.
