### ISSUE TITLE
[feat] Launch Icons in Properties

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#2251]
Like so:

![image](https://user-images.githubusercontent.com/39687477/232571182-4324ef3d-1fcc-4892-8f61-2e9c58dea6e8.png)

**Comment by MattDHill** [comment]
This is largely made irrelevant with the interfaces refactor, but it would still be nice if properties had an optional launch icon.

**Comment by MattDHill** [comment]
This is made completely irrelevant by the death of properties in favor of interfaces for addresses
