### ISSUE TITLE
[feat]: Enable Monero on BTCPay Server

### ISSUE THREAD

**Issue by brainchainz** [Start9Labs/embassy-os#2267]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.

### Describe the Feature Request

Now that Embassy has a Monero node wrapper, we need to enable XMR payments on BTCPay Server

### Describe the Use Case

Ability to accept XMR and BTC in BTCPay Server

**Comment by MattDHill** [comment]
Closing as this repository is for embassy-os issues. Please open an issue in https://github.com/Start9Labs/btcpayserver-wrapper for features specific to BTCPay
