### ISSUE TITLE
Clear All Notifications button

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#253]
Done: Can clear all
Effort: 1 hr (Matt), 2 hr (Keagan)

Clearing a long list of notifications one-at-a-time is a bit tedious.  Would be great to have a 'clear all' button

**Comment by ProofOfKeags** [comment]
This was implemented in the agent but the agent is being retired in 0.3.0.

**Comment by dr-bonez** [comment]
@ProofOfKeags this is done yea?

**Comment by ProofOfKeags** [comment]
Yes
