### ISSUE TITLE
Lists of Enums in config page cannot shrink the allowed calls list safely

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#275]
Done: Can successfully shrink the allowed calls list safely 
Test: Use BTC RPC proxy to remove "generate" call
Effort: 2 Hours (Aiden)
Dependency: New Manifest FOrmat

From version to version it is not safe for a package to shrink the set of enum strings that are allowed. If you do, and that enum entry was in the config.yaml for that application, it will be unable to open the config page in the subsequent version with an enum set that is not a superset.

@dr-bonez believes that the solution here is to deprecate lists of enums altogether as part of 0.3.0. However, this has compatibility and "forced-upgrade" implications that perhaps exceed what we were already planning for 0.3.0

**Comment by dr-bonez** [comment]
can be subverted by migrations. removing from this release
