### ISSUE TITLE
Application Logic Needs to be moved from Agent to Appmgr

### ISSUE THREAD

**Issue by KiaraStart9** [Start9Labs/embassy-os#283]
Done: 

- Move "Last Backup" to service data, should not persist across uninstall
- Transient states - installing, stopping, restarting, updating, backing up, restoring back up
-  Needs Restart logic 

Effort: 2.5 days (Aiden)
Dependency: appmgrd

**Comment by ProofOfKeags** [comment]
Agent being deprecated by 0.3.0. Reassigning to @dr-bonez

**Comment by dr-bonez** [comment]
Closing in favor of #330 #331 #332 #333 #334 #335 & #336
