### ISSUE TITLE
Retain state of Services After Update (except if configuration is required)

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#29]
Done: State of service is retained after update (if possible)
Effort: 2 days (Aiden)
Dependency: appmgrd

If a service is running when an update is requested it should be running after the update. This is impossible if it requires new config acceptance after the update, but should be possible in all other scenarios.

**Comment by ProofOfKeags** [comment]
testing blocked on #846

**Comment by ProofOfKeags** [comment]
This *sort of* works. Do we still want to autostart a service that was running prior to update if it goes into `Needs Config`? The behavior I observed was

1. install
2. start
3. update (puts into needs config)
4. configure (immediately puts it into running without start action)

I understand why this might be the behavior though I'm questioning whether this is desirable if the service needs to be configured.

@MattDHill any input on desired UX?

**Comment by MattDHill** [comment]
I personally would be surprised if the service started on its own after configuration.

**Comment by ProofOfKeags** [comment]
I was surprised myself as well so I think it's reasonable to expect users will be as well. Given that I'm kicking this back to do with a note where if we detect that an app needs configuration then its manager state should be set to stopped regardless of the state prior to update.
