### ISSUE TITLE
Prevent post-navigation autoscrolling

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#296]
When a service has a dependency issue, where the dependency isn't running, hitting "fix" brings the user to the dependency's page, but scrolls to the bottom instead of just showing the user the "start" button. The user then has to scroll back to the top of the page to actually fix the dependency issue.

**Comment by MattDHill** [comment]
This is not unique to the example above. Angular appears to be autoscrolling for all navigation if the previous page was scrolled down.
