### ISSUE TITLE
Return array of multiple release notes instead of string

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#303]
If I am on 0.2.2, upgrading to 0.2.12, the release notes should be a hashmap (or array) that includes all intermediary release notes, ie:

`
{
    0.2.3: "notes",
    0.2.4: "more notes",
    0.2.5: "even more notes",
     ....
}
`

**Comment by elvece** [comment]
User story: should see all release notes of every version of OS when requesting an update.

- Client will optionally provide version user is currently on. If current version not included, assume on the version before the one asking for. Thus, client will provide version asking to update to.

- Create a new registry endpoint to return all pertinent release notes. New endpoint necessary to maintain backwards compatibility with other client versions.

**Comment by MattDHill** [comment]
This does not need to be a new endpoint, since we are switching to a new registry entirely. Breaking backwards compat is OK.

**Comment by MattDHill** [comment]
Also, this applies to services release-notes as well, not just EmbassyOS
