### ISSUE TITLE
Improve discoverability of service instructions

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#309]
Problem: Users don't read the directions...why?

Hypothesis: current layout puts instructions behind an innocuous button that blends in with other options in that menu. This does not attract the user to click on it simply because it is interesting.

Suggested solution: Change instructions to accordion that is open by default. This means that it will render at least partially above the fold (on desktop) without the user having to take action. This could get annoying to users who are already aware of how to use a particular service, or are aware that they could easily look at the instructions if they wanted to. This could be defeated by a global setting that is open/closed by default, reducing it to where we were should a user set it to closed by default. @MattDHill has other ideas about what could be done to deal with this such as a tabbed view.

**Comment by MattDHill** [comment]
Given the new and rapidly changing UI design, I don't accordion instructions will work.

Instead, perhaps we could track whether or not the user has ever viewed the Show page of a newly-installed service. Then, on first visit, we could display a prompt, welcoming them to the service and encouraging them to view the instructions. If we do this, the user should have the ability to prevent future similar prompts in the future.

Furthermore, we could give the "Instructions" button a badge or highlight, indicating that is has never been viewed, attracting the user's attention to that button.

Both of these suggestions would require persistence using the new patch-db; specifically, the `ui` section. The frontend can persist arbitrary data using the setDbValue() method in api service, then read from patch-db.

If done well, this is not a trivial story. Perhaps only the highlighted "Instructions" button would get us most of the way there.
