### ISSUE TITLE
Samourai Wallet Dojo

### ISSUE THREAD

**Issue by searsaw** [Start9Labs/embassy-os#342]
This is not an issue and more of a feature request. It'd be awesome to be able to deploy [a Samourai Dojo server](https://code.samourai.io/dojo/samourai-dojo) that is connected to a running BTC server on the Embassy

**Comment by MattDHill** [comment]
Thank you for the request. We have definitely consider Dojo already. Please add your support for Dojo to the list of community requests for new features and services. https://s9.altweb.me/.
