### ISSUE TITLE
Ensure all external links in EmbassyOS point to appropriate documentation.

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#363]
app component 145-165

EDIT by @ProofOfKeags:

There are several places in the Embassy UI that presently render "broken links" to documentation. This is because the appropriate documentation hasn't been written yet (Start9Labs/documentation#39). However, upon that work being completed we need to make sure that the link targets provide sensible explanations for the situations that create these links to begin with.

**Comment by kn0wmad** [comment]
Blocked by docs versioning - https://github.com/Start9Labs/documentation/issues/39
