### ISSUE TITLE
Add restart button to service details page

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#368]
Add a restart button so that it is no longer necessary to first Stop and then Start a service again in order to restart it

**Comment by elvece** [comment]
Add an RPC command on the backend for `restart` which will:

- preform a stop without changing sync status
- waits for stop to successfully complete
- then run start

Call this new rpc command from the front end.

**Comment by MattDHill** [comment]
Adding Aiden for BE portion
