### ISSUE TITLE
Build Guide: Errors at step "Building the .img"

### ISSUE THREAD

**Issue by 43rozopher** [Start9Labs/embassy-os#370]
Hey,

I was following your guide as a noob with help from a friend (your guide really is not that noob-friendly btw)
https://github.com/Start9Labs/embassy-os/blob/master/BuildGuide.md
and pretty much everything went well until to the point where I was building the image ( Step 7 ii ). It did start the process, but then somewhere in the process the error shown in the image appeared. No idea how to go on from here.
![end of make](https://user-images.githubusercontent.com/85967208/126081984-f8d91dec-e5c0-41ae-bb4b-79b37261fe58.jpg)

Thanks for the help in advance,

**Comment by 43rozopher** [comment]
Oh and another maybe interesting part of the log:
![from the log](https://user-images.githubusercontent.com/85967208/126083829-e4d63bfd-1a0a-4035-8441-0b7a4a72e3df.jpg)

Also emerging after the "make" command, somewhere in the middle. everything else looks good.

**Comment by ChuckNorrison** [comment]
Nobody wants to help here? Anyone here who tried to build this software?

**Comment by BitcoinMechanic** [comment]
Sorry your build isn't working. We aren't going to have enough time troubleshoot this guide and update it between now and the release of 0.3.0 which will have an entirely new build process - also much simpler. My advice is to wait for that if you do not want to purchase an image.

**Comment by 43rozopher** [comment]
When will be the estimated release of 0.3.0 ?

**Comment by ProofOfKeags** [comment]
We're hoping in the next few weeks. Currently all of our development resources are working on the release of 0.3.0 which should reduce the complexity of the build process. It should be noted, however, that the build process itself is intended for experts and making it noob friendly has never been something we have put effort into. It isn't that we are opposed to making it noob friendly, it's just that we can't justify allocating resources to making it so, especially at this time when there are numerous people eagerly awaiting the 0.3.0 upgrade.

The original error you are running into seems very strongly like it is an error with your build environment and your node dependencies. Can you please specify what branch/commit you were building off of?

**Comment by ProofOfKeags** [comment]
This is fixed by #381. If you are impatient and do not wish to wait for it to be merged you are free to try and build off of that commit directly. Otherwise you can wait for it to be merged and build off of master.
