### ISSUE TITLE
Raspberry Pi 400 ARM64 v8 BCM2835 Build IMG Error with Docker

### ISSUE THREAD

**Issue by csharpee** [Start9Labs/embassy-os#397]
I am building an image for a Raspberry Pi 400. Embassy should work, but I won't have same speaker or same ethernet. How do I get this to work on RPI 400? 

specs: 
```
Broadcom BCM2835 quad-core Cortex-A72 (ARM v8) 64-bit SoC @ 1.8GHz
```

The error is: 

```
docker: Error respons from daemon: failed to create endpoint kind_chatelet on network bridge: failed to add the host (veth378ff68) <=> sand box (vethf82caeb) pair interfaces: operation not supported. 

make *** {Makefile:47: appmgr/ptarget/armv7-unknown-linux-gneuabihf/release/appmgr **Error 125**
```
Furthermore, I have a working crypto currency daemon working on this arm64 arch. 
I am installing embassy because I want to add our daemon to the application list, do I need to install embassy to add the app to the approval process? 

I figure, the reason it isn't working because of a few different hardware pieces like the network bridge. If I could simply **ignore** these deps, it should build on raspberry pi 400.

**Comment by csharpee** [comment]
If you all have a docker image I am able to test the daemon in, this would be sublime.

**Comment by csharpee** [comment]
also note, i had to build with sudo make because I didn't have docker setup with root privileges.

**Comment by kn0wmad** [comment]
ARM64 is not currently supported, although you may be able to get it to work.  After 0.3.0, we will have support for 64-bit, as well as an improved building process.  For now, I am closing this ticket as it is an unsupported build method.  Please consider joining our Community Dev Matrix (#community-dev:matrix.privacy34kn4ez3y3nijweec6w4g54i3g54sdv7r5mr6soma3w4begyd.onion
 on Tor, or #community-dev:matrix.start9labs.com on clearnet) if you want to continue experimenting with this as others may have tried it before.  Otherwise, please try with a RasPi 4

**Comment by kn0wmad** [comment]
If you are wanting to build your daemon for EOS, I highly recommend waiting for our upcoming 0.3.0 release.  In addition, we will have improved development documentation, and the package would have to be redone for v0.3.0 in any case.

**Comment by ProofOfKeags** [comment]
EmbassyOS is a system for managing docker containers, so containerizing it is impossible. Given that we use the GPIO interface as part of EmbassyOS, I'm concerned that it won't run on the RPi400, but it might work. I have a strong suspicion that what you're running into is a quirk of your particular setup as opposed to EmbassyOS.

You may wish to look into issues with your docker installation.

**Comment by ProofOfKeags** [comment]
Closing this as I'm not sure what is needed. Feel free to reopen with a more specific request.
