### ISSUE TITLE
Cloud backups

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#436]

**Comment by dr-bonez** [comment]
@MattDHill 

```typescript
export type BackupTarget = DiskBackupTarget | CifsBackupTarget | FtpBackupTarget

// physical disk, DiskInfo previously defined
export type DiskBackupTarget = { type: 'disk' } & DiskInfo

// Windows shared folder
export interface CifsBackupTarget {
    type: 'cifs'
    hostname: string
    path: string
    username: string
}

// FTP server
export interface FtpBackupTarget {
    type: 'ftp'
    hostname: string
    path: string
    username: string
}
```

`backup.list-targets` :: `{} -> BackupTarget[]`
`backup.create` :: `{ target: BackupTarget, target-password: string | null, old-password: string | null, password: string } -> WithRevision<null>`
`package.backup.restore` :: `{ ids: string[], target: BackupTarget, target-password: string | null, old-password: string | null, password: string } -> WithRevision<null>`
`setup.execute` :: `{ embassy-logicalname: string, embassy-password: string, recovery-location: BackupTarget, recovery-location-password: string | null, recovery-password: string } -> SetupResult`

**Comment by MattDHill** [comment]
`disk.backup-info` should be eliminated in favor of `backup.target.info`, which takes in a target-id instead of a logicalname.

**Comment by ProofOfKeags** [comment]
afaik, Matt your role on this ticket is complete and it is entirely waiting on the `embassyd` side at this point right?

**Comment by MattDHill** [comment]
Minus testing on live BE, correct.
