### ISSUE TITLE
Uptime monitoring

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#437]

**Comment by MattDHill** [comment]
This is necessarily external, probably an aspect of Diplomat protocol/service.

**Comment by ProofOfKeags** [comment]
The next question is whether or not both sides of the protocol happen on the Embassy or not. There's no obvious reason I can think of for why not unless there is zero opportunity to send a message to someone from the Embassy. This seems like it might be contingent on email support or something if we want it to be totally Embassy compatible. Would be really nice if we had a native way to send messages to Web2. Telegram will definitely work but I'm slightly dissatisfied with the centralized nature of it.

**Comment by elvece** [comment]
Hours I've been alive, not "since when". Return in server metrics response @dr-bonez

**Comment by MattDHill** [comment]
> Hours I've been alive, not "since when". Return in server metrics response @dr-bonez

This ticket is about one Embassy monitoring the liveness/availability of your Embassy in the background. For example, one Embassy pinging another Embassy as a health check buddy system.

**Comment by elvece** [comment]
> > Hours I've been alive, not "since when". Return in server metrics response @dr-bonez
> 
> You are looking for #1153
> 
> This ticket is about one Embassy monitoring the liveness/availability of your Embassy in the background. For example, one Embassy pinging another Embassy as a health check buddy system.

Yup I did indeed comment on the incorrect ticket. Commented [here](https://github.com/Start9Labs/embassy-os/issues/1153)
