### ISSUE TITLE
Get notifications adjustment

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/embassy-os#496]
Set unread count to zero in getNotifications when before variable is undefined.  Send revision back to ui

**Comment by ProofOfKeags** [comment]
Are we still doing this or am I giving you a separate endpoint for it.

**Comment by ProofOfKeags** [comment]
OK, this needs to include revision numbers.

**Comment by DrewAns** [comment]
this is still how were doing it.  It will need a revision.

{
    id: number;
    patch: Operation[];
    expireId: string | null;
};

**Comment by ProofOfKeags** [comment]
I'll address this first thing this morning.
