### ISSUE TITLE
Refactor the Config Spec code to use a Pointer Map

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#504]
Currently the way that Pointer dereferencing happens is through the `update` method on ValueSpec. This repeats a bunch of work that can be avoided and does not take advantage of maximum concurrency. Secondly it muddles the code by coalescing the environmental generation from the config hydration.

Preliminary plan for doing this:
1. Create a new type around Value that allows for the possibility of a pointer
2. Create a new method that accepts this new Value+ type as well as a mapping from pointers to their dereferenced values
3. Traverse the config spec to obtain a set of pointers
4. Traverse the set of pointers to concurrently dereference them, turning them into a mapping
5. Plug this new mapping into the Value+ type to get a final config

If only we had recursion schemes available to us...

**Comment by elvece** [comment]
Pointers are being replaced with polling this info in JS effects sytem
