### ISSUE TITLE
Ubuntu `shutdown now` doesn't immediately shutdown

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#518]
BUG: `shutdown now` sometimes doesn't immediately shut off the device. Only remedy is to unplug.

Reported by @chrisguida

**Comment by ProofOfKeags** [comment]
Are you completely sure about this? this seems to be outside the scope of EmbassyOS so I'm not sure what could cause it.

**Comment by chrisguida** [comment]
This particular time I waited about a minute. This may be acceptable.
