### ISSUE TITLE
Update Compatibilty Matrix for Service version.

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#52]
Done: 
Effort: 3 days (Lucy)
Dependency: New Manifest Format

A service should be able to specify which versions it should be downgraded or upgraded too - and include the migrations to those services

Downgrading is an operation that is not necessarily supported *in general* by applications.

**Comment by elvece** [comment]
index which dependencies each service has
field for adding max versions on registry
cli or some way to formalize an app submission process

**Comment by MattDHill** [comment]
No longer makes sense
