### ISSUE TITLE
Permit actions when service in needs config state

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#536]
Reported by @chrisguida

**Comment by chrisguida** [comment]
Can confirm this works. Shall we enforce on the server as well?

**Comment by MattDHill** [comment]
It likely already is?

**Comment by ProofOfKeags** [comment]
@chrisguida Can you please provide repro steps so that we aren't in a standoff?

**Comment by chrisguida** [comment]
What happened to this ticket?

**Comment by MattDHill** [comment]
Pretty sure it's done, just wasn't closed

**Comment by chrisguida** [comment]
Does this mean we've decided not to enforce this on the backend?

**Comment by chrisguida** [comment]
Also the title changed to the opposite of what the original intention was...?

**Comment by dr-bonez** [comment]
yeah, we want to allow actions while a service is in needs config

**Comment by chrisguida** [comment]
@dr-bonez can you explain the rationale?

**Comment by chrisguida** [comment]
And does that apply to both frontend and backend?

**Comment by dr-bonez** [comment]
A service may need actions to be performed in order to clear bad state. Such a bad state might prevent it from being configured. If an action needs the embassy to be configured in order to run, it should simply throw an error stating that.

**Comment by chrisguida** [comment]
Ok, thanks for the explanation.

**Comment by chrisguida** [comment]
For future reference, the disconnect happened here:

>@MattDHill MattDHill changed the title Prohibit actions from running when package is in "needs config" state Permit actions when service in needs config state 28 days ago 

The ticket was renamed to mean the opposite of its original meaning, with no comment explaining why
