### ISSUE TITLE
Speed up Config/Properties Units to <500ms

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#537]
Compat docker actions all take anywhere from 10s to 60s to complete, ideally should be ~instant

Reported by @chrisguida

EDIT:

We need a way to speed up configuration times (save user time). Currently we load a separate docker image (compat) during config/properties: stop doing this. ~~The easiest way to accomplish this may be to port actions to WASM.~~

- [x] Add JS interpreter to OS, specify a pair of host functions that read/write a JS object to a file in a variety of formats.
- [x] Create typescript types for all of the io formats.
- [x] Single js file that "exports" an object with fixed rows that are functions to call for the appropriate unit
- [x] manifest type is "embassy-script", no other configuration required.

**Comment by ProofOfKeags** [comment]
From @dr-bonez 

The solution to this to port the compat image to web assembly so that docker container loads are not part of this problem.

**Comment by ProofOfKeags** [comment]
Since porting to web assembly is squarely outside of the scope of the 0.3.0 release I'm going to move this to 0.3.x and probably deescalate to P3. If there is anything short of a WASM port that can improve this situation we should do that instead for now.

**Comment by ProofOfKeags** [comment]
![Screenshot from 2022-05-11 15-54-41](https://user-images.githubusercontent.com/4033651/167954206-2f65a164-43d0-473d-99c9-051139d366d2.png)

**Comment by Blu-J** [comment]
All of features seem to be in so far to master, so going close.

**Comment by chrisguida** [comment]
🚀🚀🚀🚀🚀🚀🚀🚀🚀
