### ISSUE TITLE
Test backups on packages

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#570]
- [x] synapse
- [x] mastodon
- [x] bitcoind
- [x] ride-the-lightning
- [x] thunderhub
- [x] c-lightning
- [x] filebrowser
- [x] pages
- [x] lnd
- [x] btcpay
- [x] photoview
- [x] proxy
- [x] spark
- [x] bar
- [x] cups
- [x] sphinx
- [x] vaultwarden

**Comment by ProofOfKeags** [comment]
ok I officially hate this ticket. Why are there 4 people assigned to it and why hasn't it been updated in 6 weeks?

**Comment by elvece** [comment]
Backups on physical hard drive completed successfully without error. 

Restore test pending.

**Comment by elvece** [comment]
Restore tracking:

- [x] synapse
- [x] mastodon
- [x] bitcoind
- [x] ride-the-lightning
- [x] thunderhub
- [x] c-lightning
- [x] filebrowser
- [x] pages
- [x] lnd
- [x] btcpay
- [x] photoview
- [x] proxy
- [x] spark
- [x] bar
- [x] cups
- [x] sphinx
- [x] vaultwarden
