### ISSUE TITLE
Suppress docker home env var missing warnings

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#625]
"WARNING: Error loading config file: .dockercfg: $HOME is not defined "

this message is showing up in stderr whenever a docker call exits with a failure code.

Reported by: @chrisguida

**Comment by chrisguida** [comment]
See synapse action to recreate

**Comment by ProofOfKeags** [comment]
As far as I can tell this issue isn't observable to the end user, correct?
