### ISSUE TITLE
Uninstall for services with no dependent's installed shows an uninstall warning

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#628]
bitcoind's manifest _does_ have an uninstall alert that should be displayed, but if it is the only service installed, it should not display the below warning.

**Comment by ProofOfKeags** [comment]
It appears that the linked PR has been merged. Has this been tested or not? If so, who is testing it?

**Comment by elvece** [comment]
PR is merged, testing is currently in progress by me.
