### ISSUE TITLE
Docker timeout error on package uninstall via UI 

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#629]
- `ERROR - Uninstall of bitcoind Failed: Docker Error: Timeout error`
- bitcoind stuck in `"state": "removing"`
- does not appear to be in a deadlock state
- can still access journalctl/embasy-cli

**Comment by ProofOfKeags** [comment]
We probably need a ticket documenting the total set of times that notifications should be issued. While the system is functioning correctly, its usage is rather sparse throughout the application. I will cut one. If you have input on the types of events you'd like to have notifications for, add checkboxes to it.
