### ISSUE TITLE
handle server status `updated`

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#633]
after update is complete, db.server-info.status will become `"updated"`. In this scenario prompt the user to restart their embassy to apply changes.

**Comment by ProofOfKeags** [comment]
Is this for the 0.2.x -> 0.3.0 migration or the 0.3.0 -> 0.3.x migration?

How should this be tested?

**Comment by ProofOfKeags** [comment]
If the update bricks the box, how does the `updated` status manifest? I don't think we can mark this as tested unless the `updated` status itself is properly handled on the FE. If everything else is broken after that update that's fine, but if we can't isolate the behavior we can't test it.

**Comment by ProofOfKeags** [comment]
There are issues in the update process still, but I have detailed the new issues in #668. The scope of this ticket has been confirmed to work.
