### ISSUE TITLE
Include footer with git hash and version information

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#657]
This will be useful for users reporting errors.

**Comment by MattDHill** [comment]
Version is easy. Just let me know how to get the git hash. Implementing in UI should take a few minutes.

**Comment by ProofOfKeags** [comment]
Turns out this is being improperly rendered

![Screenshot from 2021-10-19 16-07-34](https://user-images.githubusercontent.com/4033651/137997523-07c200a9-aa22-4072-9396-50b74baddbaf.png)
