### ISSUE TITLE
set query param for registry-side filtering of updates

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#661]
@ProofOfKeags @elvece need to know structure,

https://github.com/Start9Labs/registry/issues/63

**Comment by ProofOfKeags** [comment]
Looks like the 0.3 implementation does not currently actually filter based off of user agent headers.

But the parser is `EmbassyOS/<EMVER>` where the emver parser expects all `.` separators, and no `~`'s

**Comment by elvece** [comment]
Is there something additional that needs to be done here that was not resolved in [this](Start9Labs/registry#63)? Otherwise I think this ticket can be marked as Done and closed.

**Comment by ProofOfKeags** [comment]
This is for the client side setting of the parameter not the registry supporting the query param.

**Comment by dr-bonez** [comment]
reopening because it should be `eos-version-compat` not `eos-version`

**Comment by ProofOfKeags** [comment]
Requires changing registry parameter.

**Comment by ProofOfKeags** [comment]
Closing in favor of Start9Labs/registry#71
