### ISSUE TITLE
Better UX around OS Updates (0.3.x -> 0.3.y)

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#667]
- [ ] Add progress indicator that displays the progress of the download, there are already websocket events that will give you this information.
- [ ] Add a status indicating that the embassy is currently updating, disabling appropriate actions in the UI.
- [ ] Allow users to dismiss the modal without cancelling the update progress OR make it clear that the 'X' button for the modal not only dismisses the modal but will outright cancel the update

Current view:

![Screenshot from 2021-10-12 17-47-45](https://user-images.githubusercontent.com/4033651/137044330-30f85248-268d-4755-9c6c-ec7ae7bcb650.png)

**Comment by MattDHill** [comment]
There might be a misunderstanding here. Please call.

**Comment by ProofOfKeags** [comment]
Closing as invalid, this appears to result from embassyd never responding acknowledging that an update has been requested.
