### ISSUE TITLE
OS Update RPC Call does not return until the download is complete

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#668]
Presently the RPC call that tells embassy-os to update itself remains pending until the entire download completes. This causes the UI to never dismiss the update modal and consequently the remaining experience around download progress or knowing that the OS is currently updating to a new version.

All other parts of the update process appear to work normally.

**Comment by ProofOfKeags** [comment]
Confirmed that the hanging issue no longer happens. However there is still an issue with the api contract, I think. The global footer showing download progress never actually shows up. So one of two things is true:

1. The return type from the update OS RPC Call is different from what the FE is expecting
2. The code that causes the global footer to show up doesn't work properly

I am currently getting websocket events for download progress.

**Comment by MattDHill** [comment]
That's sounds viable. Why would size be null though? Isn't it needed to calculate percentage? @DrewAns built this out, so he should be able to weigh in.

**Comment by ProofOfKeags** [comment]
Good chance it was an oversight by @dr-bonez and @Blu-J. Alternatively the registry is not serving Content-Length headers. I'll take a look and verify on the registry side but my guess is that they just aren't being inspected.

**Comment by dr-bonez** [comment]
Correct there is no size because there is no content length header

**Comment by ProofOfKeags** [comment]
Shits working yo

![Screenshot from 2021-10-14 13-59-36](https://user-images.githubusercontent.com/4033651/137387177-3b91bbf8-c2e8-4a99-9d84-a2f5db3ca496.png)
