### ISSUE TITLE
Only start metrics daemons when user is on page

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#671]
Right now we are always running the metrics daemons regardless of whether the user is paying attention to them. This is needlessly wasteful.

**Comment by MattDHill** [comment]
No longer the case.

**Comment by ProofOfKeags** [comment]
How did you determine this, did you read the metrics daemon code in embassyd? I'm pretty sure this runs for the entire duration of embassyd..

**Comment by MattDHill** [comment]
I thought this was referring to the FE Metrics daemon.

**Comment by elvece** [comment]
Keeping daemon for new widgets metrics
