### ISSUE TITLE
Don't tear down embassy.local/setup wizard until the first authenticated request to embassyd

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#680]
Right now if a user walks away during the wait for the setup process, it is possible that the success page gets invalidated and causes a dead web browsing screen in that instance.

Recommended UX:
Keep setup UI alive until user authenticates for the first time to embassyd. This means that we are 100% sure they have established normal contact with their embassy before we remove their ability to find it with `embassy.local`

**Comment by MattDHill** [comment]
To be clear, it will _also_ serve on embassy-[id].local, correct? Since this is an avenue by which a user may first log in.

**Comment by ProofOfKeags** [comment]
Yes. It will serve in both places to start. Though I must ask just because of something you just implied. As of this moment, the LAN address is `start9-xxxxxxxx.local` NOT `embassy-xxxxxxxx.local`. This is probably confusing and should be changed to `embassy-xxxxxxxx.local`. I'm assuming this is your belief as well.

**Comment by MattDHill** [comment]
Tearing down embassy.local after setup (before initial login) has not proven to be an issue. I do not believe we have had a single support inquiry related to it. Also, given that they automatically download an HTML file containing their unique LAN and Tor addresses, along with instructions on how to access them, the user should always have recourse for regaining access. Closing.
