### ISSUE TITLE
SSL Manager is not Transaction Safe

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#692]
Currently the SSL Manager does not make changes to the root and intermediate certificates in SQL transactions and it probably ought to.

**Comment by ProofOfKeags** [comment]
I don't plan to work on this until we figure out the cause of #593

**Comment by ProofOfKeags** [comment]
@dr-bonez can you give any input on what you think the severity of this issue is? For me I think the issue is more theoretical than an actual issue since the only transactional component is making sure the root cert and the int cert are saved atomically.

**Comment by dr-bonez** [comment]
as long as the function is idempotent wrt partial completion I don't care. But transactions are good to use and should be trivial to implement
