### ISSUE TITLE
Dependencies section not displaying after service with dependencies configured 

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#705]
After a service with dependencies is configured, the "dependencies" section does not display with any dependency errors until the page is refreshed despite the information being accurate in the the dependency-errors data object. 

Discovered in embassy-pages.

<img width="1675" alt="Screen Shot 2021-10-19 at 4 45 48 PM" src="https://user-images.githubusercontent.com/12953208/138001158-4f4ba755-4a02-4ec4-81d9-6893b907479f.png">

Desired after configured is this display:

![Screen Shot 2021-10-19 at 4 50 02 PM](https://user-images.githubusercontent.com/12953208/138001270-7c76c1e3-d712-4e99-994c-e59598ce2d29.png)

**Comment by ProofOfKeags** [comment]
What commit was this supposedly fixed in?

**Comment by MattDHill** [comment]
#674 was the issue

**Comment by MattDHill** [comment]
The code that governs this behavior has been refactored since this issue was resolved. My guess is that this is not a unique case and your previous example would also produce this behavior. Very difficult to test this with mocks, so will need to address in the office tomorrow.
