### ISSUE TITLE
Capture and persist dmesg logs

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#706]
In trying to debug #593 the current suspicion is that there are IO faults in the SSD that are causing the database to go inaccessible meaning that blocking on connection acquisition isn't necessarily a resource leak.

One way to confirm this would be to persist the dmesg logs so we can look for IO faults if we run into this again.

~~We will want to remove this capture by release most likely.~~

**Comment by ProofOfKeags** [comment]
The move to LVM/LUKS seems to be fixing things here and it's no longer a priority to do this.

**Comment by dr-bonez** [comment]
will be including this in supporting #1319
