### ISSUE TITLE
Bitcoin IBD resulted in a decrease in disk usage while Embassy Metrics added 2G

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#715]
Disk is filling much faster than reported in Properties.  Percentage may also be incorrect

Reported by: @kn0wmad

**Comment by ProofOfKeags** [comment]
Can you describe the two different measurements you are taking? I'm not sure what is meant by "reported in properties" since I'm pretty sure properties only measures chainstate which doesn't include block data. Similarly, what measurement method are you using to ascertain that it is filling more quickly than reported?

**Comment by ProofOfKeags** [comment]
So this is the current source of data:
```
# docker exec -it bitcoind.embassy bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 252684,
  "headers": 706028,
  "bestblockhash": "000000000000003c7bddce5c82c524962831c753b5dbfe7778e6eda3f5c1b426",
  "difficulty": 50810339.04827648,
  "mediantime": 1376763175,
  "verificationprogress": 0.03222140327778335,
  "initialblockdownload": true,
  "chainwork": "00000000000000000000000000000000000000000000009a95e9285b7594c4f9",
  "size_on_disk": 435864625,
  "pruned": true,
  "pruneheight": 249707,
  "automatic_pruning": true,
  "prune_target_size": 576716800,
  "softforks": {
    "bip34": {
      "type": "buried",
      "active": true,
      "height": 227931
    },
    "bip66": {
      "type": "buried",
      "active": false,
      "height": 363725
    },
    "bip65": {
      "type": "buried",
      "active": false,
      "height": 388381
    },
    "csv": {
      "type": "buried",
      "active": false,
      "height": 419328
    },
    "segwit": {
      "type": "buried",
      "active": false,
      "height": 481824
    },
    "taproot": {
      "type": "bip9",
      "bip9": {
        "status": "defined",
        "start_time": 1619222400,
        "timeout": 1628640000,
        "since": 0,
        "min_activation_height": 709632
      },
      "active": false
    }
  },
  "warnings": ""
}
```

Specifically `size_on_disk`. According to the [Bitcoin Core Docs](https://developer.bitcoin.org/reference/rpc/getblockchaininfo.html), this references just the block and undo data, which actually excludes chainstate. Furthermore all embassy data is stored to the external disk, including logs of various sorts. When you say it is filling "much faster" can you include some numbers?

**Comment by chrisguida** [comment]
Renamed to reflect the problem, which is that the disk appears to be filling up with stuff that isn't bitcoin blocks, while nothing besides IBD is running

**Comment by dr-bonez** [comment]
@kn0wmad please reevaluate now that disk metrics code has been rewritten

**Comment by kn0wmad** [comment]
> @kn0wmad please reevaluate now that disk metrics code has been rewritten

Okay, was this a recent PR?  This is still occurring on my build from 2 days ago.  Embassy metric shows disk usage growing much faster than Bitcoin Properties, which has even decreased.

**Comment by kn0wmad** [comment]
Overnight approx. 2.5gb were added to Embassy disk metrics, while Bitcoin Properties went up to 0.85gb, before dropping back down to 0.53gb.  Looking at the Pruning config, this is actually expected behavior, as it is set to 500mb pruned size.  So either the Embassy metrics are incorrect, or the disk is being filled with data from something else.  Please advise

**Comment by ProofOfKeags** [comment]
Logs take disk space. That’s the first place I’d look. But maybe an ncdu on
the disk would be good to look at. Remember also that the Bitcoin disk
metrics don’t include the size of the utxo set which at full sync is ~4-5GB

**Comment by kn0wmad** [comment]
Okay, that might explain.  Which logs should I check?  Here's the ncdu

![image](https://user-images.githubusercontent.com/39687477/140955710-f0909203-15a1-44f9-a861-2bc5f9e5a803.png)

![image](https://user-images.githubusercontent.com/39687477/140955784-94cd1a47-e33f-45b5-9837-87a11f74c5b1.png)

**Comment by ProofOfKeags** [comment]
Yeah that definitely doesn't add up to 8.3 GB. @elvece how did you have to change disk metrics when you changed it? It is possible that there may be a bug there, or maybe we're just not clear about what we are measuring.

**Comment by elvece** [comment]
I changed it from using the zpool commands to using `df`. Essentially grab used, percentage, and available for package data and os data and aggregate them. It could be possible that what we think we are measuring is inaccurate. @ProofOfKeags we can review the code.

**Comment by chrisguida** [comment]
The extra stuff is probably chainstate. We are taking the number from `getblockchaininfo` and putting that in properties. But, that number only reports the size of the blocks. A pruned node is like 4.5G chainstate and .5G actual blocks

**Comment by ProofOfKeags** [comment]
Not sure df is going to be a good idea, we probably need to query LVM. I'd be surprised if `df` is the correct way to do that.

**Comment by elvece** [comment]
`df` is what @dr-bonez recommended at the time. Are the metrics in "Disk Usage" supposed to be solely for package data? We could break it down into sections, HDD/SDD metrics and SD card metrics.

**Comment by ProofOfKeags** [comment]
hmm. @dr-bonez is df the lowest level access we can get to volume data? We currently read the other metrics from /proc and so doing disk usage via Command invocation annoys my sense of consistency but that doesn't mean it's the wrong call necessarily.

**Comment by dr-bonez** [comment]
`df` is the recommended way according to cursory research I have done

**Comment by ProofOfKeags** [comment]
I am leaning towards closing this as invalid. I don't think we have any reason to believe the metrics are wrong solely based on the claim that Bitcoin's disk reporting is different (it's measuring something different).

**Comment by kn0wmad** [comment]
Agreed, I'm closing for now, will keep an eye on disk metrics for any further anomalies.  Thanks guys
