### ISSUE TITLE
System-generated SSL Certs: generate certs even if the user hasn't set up LAN

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#725]
so things like Synapse can use the system-generated certs even if the user is only using Tor

**Comment by ProofOfKeags** [comment]
I'm not sure what the ask is here. There isn't really anything special to do around here. The LAN stuff functions even if the user hasn't downloaded the cert and installed it.

**Comment by ProofOfKeags** [comment]
@chrisguida the code implementing this has been merged to `integration/0.3.0` Please test it as you're in the best position to do so.

**Comment by chrisguida** [comment]
Works
