### ISSUE TITLE
[feat]: SMTP server

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#734]
- [ ] PGP email encryptions
- [ ] Do we need STARTTLS to get past spam filters
- [ ] Define and exclude sensitive information from the emails
- [ ] Communicate any privacy weakening that happens as a result of enabling this feature

**Comment by MattDHill** [comment]
This is not just an extension of the notification system. EOS should be able to send emails without issuing a notification. An example of this would be a service wanting to send a verification email.

**Comment by elvece** [comment]
See https://github.com/Start9Labs/embassy-os/issues/1783
