### ISSUE TITLE
README

### ISSUE THREAD

**Issue by DrewAns** [Start9Labs/embassy-os#741]
Add instructions for what someone would have to do to start writing code on the backend in the readme

**Comment by ProofOfKeags** [comment]
I don't think P1 is proper. We can absolutely ship the product without those instructions. Moving to P2.

**Comment by chrisguida** [comment]
Is this like CONTRIBUTING.md?

For instance: https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md

**Comment by ProofOfKeags** [comment]
> Is this like CONTRIBUTING.md?

Yes. Though it should at the bare minimum be linked in the main README as it will be easier to find there.
