### ISSUE TITLE
Can't visit embassy via HTTP at IP address in browser

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#742]
![image](https://user-images.githubusercontent.com/7445670/139342209-2faa7572-7871-45d4-9624-cc90257471dd.png)

**Comment by ProofOfKeags** [comment]
@MattDHill is this a product requirement? It's not clear that it should be, and if it is it will require some rethinking about how credentialling and nginx routing is dealt with here.

**Comment by MattDHill** [comment]
Main use cases are for LANs that don't support mDNS (rare) and being able to use Android on LAN. Can wait for 0.3.x
