### ISSUE TITLE
determine why ifupdown is eating 30% of the cpu

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#746]
timebox: 2h
if we can't figure out why, remove in favor of `ifconfig up`

**Comment by ProofOfKeags** [comment]
`ifconfig up` only enables the interface. We currently have to solve the problem where we need to, on an ongoing basis, negotiate ip addresses with dhcp.

**Comment by ProofOfKeags** [comment]
looks like `dhclient` will do the trick as it runs as a daemon.
