### ISSUE TITLE
Update frontend messaging to reflect when uncritical parent dependencies will not stop their child services

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#752]
More generally, there may be a bug with cascading stops in 0.3.0

reported by @chrisguida

**Comment by dr-bonez** [comment]
Expected behavior. Proxy does not have a critical dependency on bitcoind and can continue to run while it is stopped.

**Comment by chrisguida** [comment]
Should we change proxy to have a critical dependency on bitcoin then?

**Comment by chrisguida** [comment]
Also the messaging in the UI suggests that proxy should stop

**Comment by chrisguida** [comment]
<img width="773" alt="Screen Shot 2021-11-02 at 7 22 09 AM" src="https://user-images.githubusercontent.com/7445670/139855117-2334decf-4255-4a74-ac15-b5841e933168.png">

**Comment by ProofOfKeags** [comment]
OK is this a UI bug then or is this an issue with how the OS is reporting stop cascades?

**Comment by ProofOfKeags** [comment]
I guess what is unclear is what the desired behavior *is* and why.

**Comment by chrisguida** [comment]
Created an issue to update proxy https://github.com/Start9Labs/btc-rpc-proxy-wrapper/issues/9

For embassy-os, seems like the front end needs to be updated to reflect that sometimes services won't stop when their parents are stopped

**Comment by ProofOfKeags** [comment]
At minimum this should be changed to not state that the services will stop. Additionally the BE provides a report on how the services will break, which can be rendered to the user.
