### ISSUE TITLE
Fix URLs in setup wizard file download

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#753]
URLs have double `https://` / `http://` for both TOR and LAN addresses in the downloaded file resulting from the setup wizard. See screenshot:

<img width="1206" alt="Screen Shot 2021-11-01 at 12 12 29 PM" src="https://user-images.githubusercontent.com/12953208/139720403-3716a5e3-37fd-40a8-8953-40538151d62d.png">

**Comment by ProofOfKeags** [comment]
This is a consequence of us returning a URL *and* the UI prefixing it with a protocol. My preference would be to remove the UI prefixing.
