### ISSUE TITLE
Removing a service without stopping it keeps it in "removing" state forever.

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#754]
Logs indicate:

```
ERROR run_main: embassy::manager: Failed to run health check for embassy-pages: Database Error: Node Does Not Exist: /package-data/embassy-pages/installed
```

**Comment by ProofOfKeags** [comment]
Is this actually blocking? If so, it needs to be prioritized.

**Comment by elvece** [comment]
Technically not blocking, just annoying if you forget in development, as you have to nuke the db to remove it. I have not tested again to see if this has been resolved in latest code because I did not want to get in that state.

**Comment by ProofOfKeags** [comment]
Observed as working.
