### ISSUE TITLE
UI Bug - Reorder doesn't

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#760]
Click reorder, change order, click done, order does not change.  

Reported by @kn0wmad - reach out for more detail

**Comment by MattDHill** [comment]
I am unable to reproduce this. Please try again and capture any errors in the console. My best guess is another error caused the UI to glitch.

**Comment by ProofOfKeags** [comment]
This could be because of the unintuitive mapping from a single list edit to a dual list render. I am presently able to observe order changes when I try this, but it is definitely not intuitive how things shake out.

**Comment by ProofOfKeags** [comment]
The render ordering appears to be horizontal left to right, with a text wrap effect to create multiple rows

**Comment by kn0wmad** [comment]
> The render ordering appears to be horizontal left to right, with a text wrap effect to create multiple rows

This was my understanding.  I am unable to produce with the newer code.  Closing for now
