### ISSUE TITLE
Setup does not recognize compatible external drive

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#768]
When refreshing an image, the previously used external drive should be recognized, as it could have service data.

Unsure if FE or BE issue presently. Needs further investigation. 

Expected behavior:
- if a GUID comes back from external drive, notify user, ask if want to reattach
- If select no, and opt to create with a selected drive that has a GUID, we should warn the user that data will be deleted

**Comment by dr-bonez** [comment]
Confirmed this is a frontend issue. Assigning to @DrewAns

**Comment by ProofOfKeags** [comment]
Has this been tested @DrewAns?
