### ISSUE TITLE
FE BUG: Downgrade modal not rendering

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#788]

**Comment by ProofOfKeags** [comment]
@chrisguida Please provide details.

**Comment by MattDHill** [comment]
@chrisguida did you reproduce this after your issues this morning. Because most likely this was due to existing bad state from failure to uninstall prior.

**Comment by chrisguida** [comment]
Whoops, could have sworn i attached this screenshot:

<img width="1086" alt="Screen Shot 2021-11-11 at 7 24 24 AM" src="https://user-images.githubusercontent.com/7445670/141387004-11de1bf2-0755-4491-a38e-053db02d551c.png">

**Comment by chrisguida** [comment]
@MattDHill no, everything was fine at this point

**Comment by chrisguida** [comment]
For more details, I was trying to downgrade from 0.10.1 to 0.10.0.1, which is actually an upgrade

**Comment by MattDHill** [comment]
Something is fishy here. In your original post on Matrix, you sight an error in the JS console of `t.pkg['dependency-metadata'][e.key] is undefined`. This error can only be produced on the Marketplace Show page, not the upgrade/downgrade modal. This means there was an issue before you even attempted to open the modal, which might explain why the modal failed to open properly. We need to reproduce this from a clean state and capture any console errors as you go.

**Comment by chrisguida** [comment]
This happens every time i hit downgrade, have you tried doing that?

**Comment by MattDHill** [comment]
No, I cannot reproduce in mocks, no live environment. But that's great. What's the error?

**Comment by chrisguida** [comment]
Hm, well the c-lightning version i was seeing the error on got deleted, so i tried with synapse, but that's a different error

<img width="1107" alt="Screen Shot 2021-11-12 at 7 18 57 PM" src="https://user-images.githubusercontent.com/7445670/141600376-165764de-d9c9-4a82-932e-94f2374c04f5.png">

**Comment by MattDHill** [comment]
That looks like a BE error. Clearly something wrong here. Logs on both FE and BE would go a long way.

**Comment by chrisguida** [comment]
Hit the blank modal again. Had to re-upload c-lightning 0.10.0.1 to recreate. There is no other error than the one I posted above.

Steps to recreate: install c-lightning 0.10.1. Go back to marketplace, hit "other versions", select "0.10.0.1", then hit "downgrade". Hits the bug every time for me.

**Comment by MattDHill** [comment]
What does the network tab show? Is the correct data coming back from the BE?

**Comment by chrisguida** [comment]
Is this fixed?

**Comment by ProofOfKeags** [comment]
It was moved to done. Like everything else I'd presume that if the ticket is marked as done, then the code is in integration and has been observed to work. My choice to close it was a direct result of the movement to the Done column

**Comment by chrisguida** [comment]
Ok. A simple "fixed" or "won't fix" from whomever moved it to Done would be great next time.

**Comment by ProofOfKeags** [comment]
since there is a tag for `wontfix` It should be assumed that the person who moved it to done is attesting to it being fixed. As long as there is no ambiguity, I am very resistant to requiring someone say "fixed" on every ticket they fix. It has not been practice to do this for any tickets.

**Comment by chrisguida** [comment]
Ok, I'm fine with this as long as we actually use the "won't fix" label when things won't be fixed. This hasn't happened historically, so I'm just worried it's still happening. It would still be helpful to have a commit hash or pr of the fix, but I guess I can go fishing for it if I know it exists somewhere.
