### ISSUE TITLE
Add optional `placeholder` to certain ValueSpecs

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#796]
**Describe the solution you'd like**
add optional `placeholder` attribute to to VlaueSpec for string and numbers only, including the list varieties.

**Additional context**
This gives devs the ability to customize the placeholder text for inputs in config.

FYI, for the docs. If absent, the default placeholder will be `'Enter ' + spec.name`.

**Comment by dr-bonez** [comment]
assigning to @MattDHill to test

**Comment by MattDHill** [comment]
Reassigning to @DrewAns. I'm not set up for this.

**Comment by ProofOfKeags** [comment]
Do we have any services that make use of this @chrisguida @elvece

**Comment by MattDHill** [comment]
Probably not, since the spec was just augmented to support it. If there are config fields that could benefit from a placeholder, feel free to add them. This has been "tested" using mocks. No reason it wouldn't work if the key is present.

**Comment by chrisguida** [comment]
I can add it to any services we need

**Comment by MattDHill** [comment]
It's your call. If you are aware of any config items that could benefit from a placeholder, go ahead and add it. Same for you @elvece

**Comment by ProofOfKeags** [comment]
I have observed this working correctly on c-lightning as of yesterday.
