### ISSUE TITLE
Add "reset tor guard node" as a button in the UI.

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#798]
service tor stop && rm /var/lib/tor/state && service tor start

Reported by: @chrisguida

**Comment by DrewAns** [comment]
@ProofOfKeags would this make sense as an "action" for all services?  What endpoint would this hit, what are the types?  Does the user need to see anything displayed on success?

**Comment by MattDHill** [comment]
Seems a bit late in the game to be adding features to 0.3.0, especially full stack ones with networking implications...How necessary is this?

**Comment by ProofOfKeags** [comment]
Honestly I don't even think we should do this... not just in 0.3.0 but ever. At the bare minimum it should be ejected from the 0.3.0 work.

**Comment by chrisguida** [comment]
@ProofOfKeags Why not ever?

**Comment by kn0wmad** [comment]
I agree it's not an 0.3.0 goal, but since it is sometimes successfully used it would be a nice feature (even if buried in some advanced section of Embassy tab or something), unless 0.3 fixes this is in some other way I'm unaware of.

**Comment by kn0wmad** [comment]
Agreed.

**Comment by dr-bonez** [comment]
this happens automatically on reboot
