### ISSUE TITLE
FE BUG: bitcoind advanced rpc settings not displaying

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#800]
<img width="799" alt="Screen Shot 2021-11-15 at 9 04 36 AM" src="https://user-images.githubusercontent.com/7445670/141807070-3cc85c89-d4e6-49f1-8c4a-ec7d9ad845dc.png">

**Comment by MattDHill** [comment]
@chrisguida as always, JS console errors are essential for debugging.

**Comment by chrisguida** [comment]
Updated to latest code, still broken, no errors in the console

**Comment by chrisguida** [comment]
Nvm, now it's working. Guess I had a cached version of the frontend? Closing
