### ISSUE TITLE
Update via cli failing for filebrowser

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#801]
Since filebrowser has no config, an update via the cli is failing to update the service.

command ran: `embassy-cli package install filebrowser`

log error: `ERROR embassy::install: Install of filebrowser@2.14.1.1 Failed: Not Found: filebrowser has no config`

**Comment by ProofOfKeags** [comment]
reassigning to @chrisguida for UAT since he has capacity.

**Comment by chrisguida** [comment]
Tested, works
