### ISSUE TITLE
Redact sensitive information from config

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#802]
In the browser console, you can see sensitive information such as passwords. The plain text is necessary to populate the config, but should these items be encrypted? Can this information be redacted?

<img width="1673" alt="Screen Shot 2021-11-15 at 2 17 17 PM" src="https://user-images.githubusercontent.com/12953208/141855644-696c63c6-7528-4d91-be08-c77760f8ef77.png">

**Comment by dr-bonez** [comment]
all requests are encrypted over the transport layer. If you want to not send back passwords to the FE during configuration, a custom config.get is needed that sends back `null` as the password, and treats `null` as no change. ideally, the password could also be kept hashed on the package data volume in these scenarios. This method is *not* compatible with the current `compat` system.
