### ISSUE TITLE
Cert not ingestible by Mac Keychain

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#809]
At the end of setup, the the downloaded cert (can't remember if it was from the endpoint or the Base32 encoded one) could not be used by the Mac Keychain. Unable to test or provide more detail atm due to travel.

**Comment by ProofOfKeags** [comment]
@elvece Can you please confirm which cert download points fail on the Mac?

**Comment by elvece** [comment]
The cert works _as expected_ when downloaded from the downloaded `embassy-info.html` page - it can be imported into the MacOS Keychain, verified, and added to the Certificate Manager in Firefox. When the Embassy is accessed from it's .local address, it loads securely without the security warning. 👍 

Environment:
MacOS Catalina 10.15.7
Firefox

Commit hash: b18de9d3987ad3d44e58bd916321d413d8121fb1

The cert *does not even download* when attempted from the final page of the setup wizard. Error thrown: 

<img width="1676" alt="Screen Shot 2021-11-22 at 4 38 21 PM" src="https://user-images.githubusercontent.com/12953208/142950974-2d9672e4-0117-4594-9b31-3ba9782d7aa7.png">

**Comment by ProofOfKeags** [comment]
OK that's actually expected. There's no way you'd have the auth material to be able to download that thing...The download root CA button shouldn't be linking to the normal root CA download endpoint. It needs to come from the base64 data.

**Comment by ProofOfKeags** [comment]
@DrewAns do you have a PR number that this was fixed in?

**Comment by elvece** [comment]
@ProofOfKeags do you know offhand where the base64 data comes from for @DrewAns ? Is it in the success response type?

**Comment by ProofOfKeags** [comment]
https://github.com/Start9Labs/embassy-os/blob/integration/0.3.0/appmgr/src/setup.rs#L92

**Comment by DrewAns** [comment]
@elvece i have a pr for this fix up currently

**Comment by elvece** [comment]
Cool I can test

**Comment by BitcoinMechanic** [comment]
I can also test with different version of Mac OS - 10.14.6

**Comment by elvece** [comment]
Confirmed that cert now works when downloaded from the button on the final page of the setup wizard! 🥳 

Steps to repro were:
- Imported into the MacOS Keychain, double click on Embassy Local Root CA, expand "Trust" and select "Always Trust" from "When using this certificate".
- Navigate to Firefox settings > Privacy & Security > View Certificates > Import > select the downloaded `embassy.crt` > OK
- Navigate to the Embassy's LAN address located on the final page of the setup wizard
- It loads securely without the security warning - yay 🎉
