### ISSUE TITLE
LAN addrs for services initially resolving Embassy UI

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#810]
Reproduction steps:

1. Install service
2. Configure and start
3. Visit LAN address

If you visit the address quickly enough (no idea how quick is quick enough) Embassy UI will load instead of the service UI. This is not an acceptable experience and will likely result in added support load. Either we need to fix this behavior on the BE, or we need to message for it or black against it on the FE.

**Comment by ProofOfKeags** [comment]
@dr-bonez you had said that one of the ways for this to be resolved is that there is a "starting" status for when the container has been started but the net controller hasn't yet been updated?

**Comment by dr-bonez** [comment]
I would have to create one. It doesn't exist yet

**Comment by ProofOfKeags** [comment]
Is that the approach we are going with though? I'm trying to clean out all the scoping requirements here.

**Comment by dr-bonez** [comment]
yeah a starting state seems like the correct route to go here.

**Comment by ProofOfKeags** [comment]
OK should this still be a joint assignment or is the entirety of the work on embassyd?

**Comment by ProofOfKeags** [comment]
@DrewAns The FE component that needs to be handled by this ticket is as follows.

1. A new status will be introduced: `starting`
2. If an app is currently in the `starting` state, then the launch UI button should be greyed out or otherwise unclickable.

**Comment by DrewAns** [comment]
@dr-bonez 
is "starting" a package status in the installed object, or a state at the top level of the package?

**Comment by ProofOfKeags** [comment]
This should not be closed until the full fix is in. So far only the FE portion has been merged
