### ISSUE TITLE
Show alternative messge to 99% for service install

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#811]
Currently, services can remain at 99% for a long time, resulting in user confusion or frustration. Instead of showing 99%, we should show a message such as "finalizing install. This could take a minute..."

**Comment by ProofOfKeags** [comment]
This issue is in the code review column but has no linked PR. What does that mean?

**Comment by ProofOfKeags** [comment]
It seems that a PR was merged that references this issue, but this issue is still in the code review column. Where should it be moved?
