### ISSUE TITLE
Names and descriptions for health checks

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#817]
Reported by: @chrisguida

**Comment by dr-bonez** [comment]
@chrisguida please provide more info

**Comment by chrisguida** [comment]
I pictured this feature working exactly like names and descriptions on any other manifest/config spec key. The package dev would put a name and a description into the manifest under the health check's key, then on the front end would display a name and description for the health check. Currently the only information the user has is the health check's key name, which doesn't provide much info. @MattDHill is actually the one who requested this feature, but I agree that we need it.

**Comment by dr-bonez** [comment]
Will remove Needs Scoping label when new types are documented. These will likely be required fields which will break every existing package on the registry :(

@elvece

**Comment by elvece** [comment]
It's fine, maybe I'll finally write an update manifest script 😅 

This would be good to have and create a better UX.

**Comment by ProofOfKeags** [comment]
Scope of Work:

1. Manifest format needs to be updated to have 2 new required fields: `name` and `description`
2. `embassyd` needs to extend the manifest type to include this for the purposes of plumbing to the FE
3. UI needs to render the name and description in an appropriate way

This has implications on service packaging @chrisguida @elvece

**Comment by DrewAns** [comment]
@ProofOfKeags 
The manifest needs those fields, or each health check needs those fields?

**Comment by ProofOfKeags** [comment]
each health check needs those fields

**Comment by chrisguida** [comment]
Tracking package mass-updating here https://github.com/Start9Labs/embassy-os/issues/832#issuecomment-980141784

**Comment by chrisguida** [comment]
Names and descriptions looking good, I think this one is good to close

**Comment by chrisguida** [comment]
@DrewAns this is done, right?
