### ISSUE TITLE
Display better error messaging when a pointer volume is dropped.

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#819]
Right now we just do this
```
            if tokio::fs::metadata(&src).await.is_err() {
                continue;
            }
```
Reported by: @chrisguida

**Comment by dr-bonez** [comment]
Happy to add a log statement here. Is that sufficient?

**Comment by chrisguida** [comment]
Yes, thanks

**Comment by dr-bonez** [comment]
to test: install a package that has a pointer volume (without the pointer target installed) and look for a warning in the logs

**Comment by ProofOfKeags** [comment]
confirmed working.
