### ISSUE TITLE
tell user which services failed to backup on the backup page.

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#821]
currently they have to click into the notification that happens once the backup process completes to see which backups failed

Or at least warn the user to check the report to see if anything failed. Don't want people making failed backups for months without noticing

Reported by: @chrisguida

**Comment by dr-bonez** [comment]
I propose changing the notification level from `Success` to `Warning` for backups that contain failed apps. Is this sufficient?

**Comment by chrisguida** [comment]
@dr-bonez yes, that sounds fine for now. we can revisit in a different ticket if people need more.

**Comment by dr-bonez** [comment]
assigning to @chrisguida to test

**Comment by chrisguida** [comment]
Looking good!

<img width="1196" alt="Screen Shot 2021-11-27 at 1 31 57 PM" src="https://user-images.githubusercontent.com/7445670/143719864-65c087ef-c7f2-4b35-a9e8-adfd6f6dade6.png">

Closing.
