### ISSUE TITLE
[feat]: extend backup restore api to allow service developers to indicate the service is already configured

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#823]
Reported by: @chrisguida

**Comment by dr-bonez** [comment]
this seems like a dangerous thing to do unilaterally. there's no guarantee it was configured before it was backed up. I can amend the return type of the restore action to be similar to that of migration, but that will require being diligent about stdout for that action.

**Comment by chrisguida** [comment]
It's just that 0.2.x worked this way. I haven't tried restoring a service that was still in needs config when it was backed up.

**Comment by dr-bonez** [comment]
in 0.2.x, the system was able to determine if it was configured based on the presence of a config.yaml file. Its not as simple anymore.

**Comment by chrisguida** [comment]
How does 030 determine this?
