### ISSUE TITLE
Check for embassy-12qw34er.local address on the Setup Complete page

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#824]
Making the Setup Complete page even more simple it would be cool to use os-level health check on the Setup Complete page
and display LAN Instructions only if embassy-12qw34er.local address is available for the local network.
![Screenshot from 2021-11-19 22-13-22](https://user-images.githubusercontent.com/3606313/142694779-16306c84-43b0-4c18-8194-c59003277b6f.png)

**Comment by MattDHill** [comment]
The reason we display the `Initializing Embassy` page with loading indicator is to buy time for both the Tor and LAN services to broadcast. If the final success page is reached, and the LAN service is not yet broadcasting, perhaps we need to remain on the Init page longer. If this is an intractable problem, meaning there is no predictable amount of time we can wait to display success, then another solution is needed. Possibly something like what @k0gen suggests, but I'm also not convinced this will be clear enough to the user. At minimum, we would also need to display messaging alongside the spinner: ie "waiting for LAN connection...", but it does feel a little weird to go from the "Initializing Embassy..." page to a success page that is clearly still initializing something. Might it be better to leave them on the "Initializing Embassy" page until we detect the LAN service, then send them to the static success page?

**Comment by k0gen** [comment]
> Might it be better to leave them on the "Initializing Embassy" page until we detect the LAN service, then send them to the static success page?

If by this you mean waiting for the LAN service at the "Initializing Embassy" page _(spinner and timeout timer would be cool)_ and if LAN service is available redirect to embassy-12qw34er.local address and display "Setup Complete!" page?
Then yes that would be the most desirable and user friendly solution.

**Comment by MattDHill** [comment]
We cannot redirect because of certificate constraints. The browser will not trust start9-abcdefgh.local. and we can't redirect to the .onion site either because most likely their browser does not support Tor. For 0.3.0, I think we'll stick with the current flow but perhaps spend more time on the "initializing Embassy" page in order to ensure the .local site is accessible.

**Comment by ProofOfKeags** [comment]
Assigning to @dr-bonez and @MattDHill for future scoping

**Comment by dr-bonez** [comment]
In recent builds, the time until the .local is initialized is almost instant. It may be best to poll the .local (on port 80 without following redirects to avoid cert errors) to see if it's up.

**Comment by dr-bonez** [comment]
closing for reasons above
