### ISSUE TITLE
Affected Services modal does not list any services

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#829]
**Describe the bug**
When stopping bitcoind, Affected Services modal does not list any services 

**To Reproduce**
I have bitcoind, bwt, and btc-rpc-proxy installed, bitcoind and bwt are running. I hit "stop" on bitcoind, and the modal below pops up:

**Expected behavior**
The modal either should not pop up, or it should tell me which services may be affected. At absolute minimum I should still be able to stop the service.

**Actual behavior**
A modal pops up with no affected services listed, and no way to stop the service.

**Screenshots**
![Screenshot from 2021-11-22 12-40-13](https://user-images.githubusercontent.com/7445670/142917115-37fbad95-202a-4e17-a9bf-024a4a872cfa.png)

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 20.04
 - Browser and version [e.g. Firefox

**Additional context**
Interestingly, this did not present on my Mac with the embassy in the same state. I cleared the cache on my Ubuntu box and the issue went away.

**Comment by ProofOfKeags** [comment]
Do you know which of the two options was correct? Should it have a non-empty list or should it not have rendered?

**Comment by chrisguida** [comment]
Proxy was listed once I got it working. So, looks like it should have displayed Proxy

**Comment by ProofOfKeags** [comment]
Were you able to grab the console logs/network tab?

**Comment by DrewAns** [comment]
Presumed fixed, will open if it comes up again.  Caching issue most likely.

**Comment by chrisguida** [comment]
@DrewAns found this message in the testing chat: 

>got this in the console TypeError: n.patch.data['package-data'][t.key] is undefined

**Comment by chrisguida** [comment]
Also for more context: I'd just edited the bwt manifest, made me think maybe it had something to do with bwt

https://github.com/chrisguida/bwt-wrapper/blob/7416586857cd4ff591181175539aa08ada8a699f/manifest.yaml
