### ISSUE TITLE
Invalid Request on setup before chime

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#830]
If you visit `embassy.local` before the device chimes and attempt to enter the product key, the POST request to submit the product key returns a 200 code, but the response contains an error. I am 100% certain that the product key is correct for the image flashed. There are no errors in the console, just the following network information:

<img width="1674" alt="Screen Shot 2021-11-22 at 1 12 39 PM" src="https://user-images.githubusercontent.com/12953208/142937441-e13d7476-3ffd-4eba-bd31-b69cc1f18f83.png">

Environment:
MacOS Catalina 10.15.7
Firefox

Commit hash: `b18de9d3987ad3d44e58bd916321d413d8121fb1 `

**Comment by ProofOfKeags** [comment]
Are you 100% sure that this embassy.local is the right one?

**Comment by ProofOfKeags** [comment]
I would be rather surprised if this was not caused by mdns conflicts between multiple fresh embassies and you happened to get dialed into the wrong one.

**Comment by elvece** [comment]
I am not 100% certain. I can re-confirm.

**Comment by elvece** [comment]
> I would be rather surprised if this was not caused by mdns conflicts between multiple fresh embassies and you happened to get dialed into the wrong one.

This seems to have been the case as I cannot reproduce. Closing.
