### ISSUE TITLE
Selecting a recovery drive failing

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#834]
There are two issues here:

1) A drive is plugged in with previous data and "recover" is selected during the setup process. The drive is not displayed in the UI, despite the it seeming like the proper information is being returned. See screenshot below. Also included is the screenshot of the error thrown in the console. 

<img width="1675" alt="Screen Shot 2021-11-22 at 2 10 13 PM" src="https://user-images.githubusercontent.com/12953208/142938820-2d4be8bd-b26f-4eb6-84f6-98cc313e5ac2.png">

<img width="1675" alt="Screen Shot 2021-11-22 at 2 09 41 PM" src="https://user-images.githubusercontent.com/12953208/142938837-bbaa74ca-9d20-449d-8844-7da4b95e0fad.png">

2) Not a typical flow, but an `exFAT` formatted empty drive is plugged in and "recover" is selected during the setup process. It's correctly displayed as unselectable, but it's confusing to the user why they might be in the wrong place. Perhaps display a message/modal saying "an Embassy cannot be recovered from this drive as no previous data found", or something alike. Following screenshot displays the denoted view:

<img width="1675" alt="Screen Shot 2021-11-22 at 2 12 00 PM" src="https://user-images.githubusercontent.com/12953208/142939185-18520f84-f7e5-4c57-b5e9-45bf9d3582bb.png">

Environment:
MacOS Catalina 10.15.7
Firefox

Commit hash: b18de9d3987ad3d44e58bd916321d413d8121fb1

Related Issue: https://github.com/Start9Labs/embassy-os/issues/768

**Comment by elvece** [comment]
Regarding issue (1):

On a fresh setup, if I navigate to "Recover" and select "use drive" from the modal, I now get this error:
<img width="1673" alt="Screen Shot 2021-11-23 at 4 52 00 PM" src="https://user-images.githubusercontent.com/12953208/143147114-dec62585-8d3a-4763-af32-3a44975e7921.png">

Commit hash: `6e6fe9296e60d23c149e5417d1160823d84c085e`

**Comment by DrewAns** [comment]
@elvece this is expected behavior as the attach function is not yet implemented on the backend

**Comment by ProofOfKeags** [comment]
@dr-bonez is there a ticket number tracking what @DrewAns is talking about? or does this ticket need to be reassigned to reflect needed work in `embassyd`?

**Comment by dr-bonez** [comment]
There is not a ticket for it already

**Comment by dr-bonez** [comment]
I noticed on the frontend you are calling `setup.execute` for this, instead you should be calling `setup.attach`

@DrewAns should be a 1 line change
