### ISSUE TITLE
when starting up new Embassy 0.2.x , no sounds, and 4 blinking green lights repeat sequence

### ISSUE THREAD

**Issue by cryptodread** [Start9Labs/embassy-os#837]
Please fill out as much detail as possible:

Plugging in a new embassy 0.2.x, it will not beep on startup, and has a repeating sequence of 4 green lights. 
The Red light is on solid and constant. 
There are no external hard drives plugged into this unit.

**Comment by ProofOfKeags** [comment]
Card was cracked in half.
