### ISSUE TITLE
Add "severity" attr to dependencies and health checks

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#848]
**Is your feature request related to a problem? Please describe.**
In the future, we want to provide more specific messaging to the user when a service has a dependency error or health check error, depending on its severity.

The binary (critical vs non-critical) UX is acceptable for 0.3.0 launch, but it would be preferable to switch to an enum implementation now for a smoother transition and backwards compatibility later.

**Describe the solution you'd like**
`critical` bool should be removed from dependencies and health checks. A _optional_ `severity` enum will be added in its place. Options are currently limited to "warning" and "critical", with "warning" being the default.

**Comment by ProofOfKeags** [comment]
what are the desired semantics of each label? We should be clear on what each designation means if we are going to expand it like this. If we are not it will create more confusion which is what I think this ticket was cut to avoid. The questions I would like answered are:

1. What constitutes warning?
2. What constitutes critical?
3. What is an example of a 3rd label? All 2 point enums are isomorphic to booleans (which is the current implementation). This means that this hypothetical third label must exist in order for any benefit to be observable from this change.
4. How do we intend to communicate the semantics of each label to the user?

**Comment by MattDHill** [comment]
This is all about messaging to the user and enabling or preventing functionality. The ones we discussed were "info", "warning", "error", and "critical".

Info: benign in nature, expected
Warning: may experience issues, fine to run
Error: will not work as expected, recommended not to run
Critical: likely to cause harm, cannot run

This is just a rough hypothesis. Doesn't need to be decided now because we have the ability to easily extend later.

**Comment by chrisguida** [comment]
Should this be moved to 0.3.1?

**Comment by MattDHill** [comment]
No, because then every service would have to migrate or we would have to acquire tech debt to build in backwards compatibility. It's an investment. A few minutes now will save us a few hours later. And it actually is a few minutes, I think.

**Comment by ProofOfKeags** [comment]
> Info: benign in nature, expected
> Warning: may experience issues, fine to run
> Error: will not work as expected, recommended not to run
> Critical: likely to cause harm, cannot run

I'm satisfied with this as a demonstration of hypotheticals, however it does not solve the need for building in tech debt as a result of backwards compatibility. We would need to handle the case (somewhere, be it os, sdk, etc.) where a package specifies a value that is not recognized by the current version of embassy-sdk.

**Comment by MattDHill** [comment]
This is only the case if a value is removed from the enum. Also, is your comment specific to this issue to or the idea of backwards compatibility in general?

**Comment by chrisguida** [comment]
This is (at least) a few minutes of work *per service*

**Comment by MattDHill** [comment]
That sounds about right.

**Comment by ProofOfKeags** [comment]
Swapping myself in-place of @dr-bonez since this is very close to the names/descriptions feature I am already on.

**Comment by chrisguida** [comment]
Tracking service update progress here https://github.com/Start9Labs/embassy-os/issues/832#issuecomment-980141784
