### ISSUE TITLE
Pages flashes an error briefly after save+exit config

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#854]
This happens when saving to exit config within pages for about 2 seconds. Doesn't matter if no change is made.

"Error response from daemon: Container ac6114a6c4186ae83af9ecb6da24092451cd0fa3675a792737e743f4b4d5ab74 is not running"

![Screen Shot 2021-11-24 at 3 18 21 PM](https://user-images.githubusercontent.com/45926711/143327172-c8acf7d1-c969-4e68-847e-96e58e21512d.png)

**Comment by dr-bonez** [comment]
answer is to pause health checks while the container is being bounced.

**Comment by ProofOfKeags** [comment]
Looks like the approach here is to not commit the results of the health check if the container has exited for a "good reason". Good reasons defined by stop control action, or when a container is sent a signal.

**Comment by ProofOfKeags** [comment]
@BitcoinMechanic can you test this on the branch `bugfix/invalid-health-check-results`. It seems to be fixed now but I never repro'ed the issue before.

**Comment by BitcoinMechanic** [comment]
Working for me now.
