### ISSUE TITLE
Descriptions in union tags not displaying on the FE

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#859]
**Describe the bug**
Bitcoind has a description in its union tag for the `pruning` key, and this description is being passed to the frontend, but is not being displayed anywhere on the frontend. This is also happening on 02x.

**To Reproduce**
1. Hit configure on bitcoind
2. Expand "advanced", then "pruning", then click on the dropdown

**Expected behavior**
The union tag description for pruning, defined in the config spec as 

`- Disabled: Disable pruning\n- Automatic: Limit blockchain size on disk to a certain number of megabytes\n- Manual: Prune blockchain with the \"pruneblockchain\" RPC\n`

should display somewhere, probably in the modal that allows the user to choose one of the variants.

**Actual behavior**
The description is not visible anywhere

**Screenshots**
<img width="891" alt="Screen Shot 2021-11-26 at 3 08 37 PM" src="https://user-images.githubusercontent.com/7445670/143652873-7962c733-66e1-480c-9cd6-0e7659b1ec2a.png">

**Desktop (please complete the following information):**
 - OS and version: M1 MacOS Big Sur 11.2.3
 - Browser and version: Firefox 94.0.1

**Additional context**
See these comments for the config spec and what's being passed to the FE: https://github.com/Start9Labs/embassy-os/issues/832#issuecomment-978021827

**Comment by ProofOfKeags** [comment]
Assigning to @MattDHill for triage purposes: please mark this with the appropriate P tag and then unassign yourself.
