### ISSUE TITLE
"Finalizing install" not showing in the mktplace

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#861]
**Describe the bug**
"Finalizing Install" shows on services after they are 99% installed in the rest of the UI, except on the Marketplace list and details pages, which still have the old "hanging on 99%" behavior.

**To Reproduce**
1. Install a service
2. Go to the marketplace details or list pages
3. Wait until 99% install progress
4. "Finalizing Install" does not show

**Expected behavior**
"Finalizing Install" should display, in the same situations that it shows on the other pages.

**Actual behavior**
"Finalizing install" does not show

**Screenshots**
<img width="782" alt="Screen Shot 2021-11-27 at 1 17 11 PM" src="https://user-images.githubusercontent.com/7445670/143720516-9d2d7eac-2860-4df4-9198-acfcb8ff26e5.png">

**Desktop (please complete the following information):**
 - OS and version: MacOS Big Sur 11.2.3
 - Browser and version: FF 94

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ProofOfKeags** [comment]
This is a staleness issue. Confirmed this works on the latest commit.
