### ISSUE TITLE
Disable bluetooth service

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#862]
**Is your feature request related to a problem? Please describe.**
If we are not using Bluetooth why not disabling it? This would be one less element that uses power and heats up. Not to mention less services in system during boot.

**Describe the solution you'd like**
Editing boot `config.txt` file and adding: 
```
# Disable Bluetooth
dtoverlay=disable-bt
```

**Comment by ProofOfKeags** [comment]
Speculatively putting into the 0.3.0 SOW. @dr-bonez if you feel this should wait, go ahead and kick it from the 0.3.0 project.

**Comment by k0gen** [comment]
Just did: `sudo service --status-all | grep +` and I saw that bluetooth service is still running.

**Comment by kn0wmad** [comment]
CC @dr-bonez

**Comment by dr-bonez** [comment]
something is reactivating it. the service is disabled in the systemd config

**Comment by k0gen** [comment]
> something is reactivating it. the service is disabled in the systemd config

It seems we need to disable hciuart service as well witch initialises the modem, so it does not connect to the UART.
