### ISSUE TITLE
Too many services running 

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#865]
**Is your feature request related to a problem? Please describe.**
When I disabled bluetooth (mentioned in #862) I have checked if the service is running to later find out how many other services are there by default.
```
service --status-all | grep "[ + ]"
 [ + ]  apparmor
 [ + ]  apport
 [ + ]  avahi-daemon
 [ + ]  bluetooth
 [ - ]  console-setup.sh
 [ + ]  cron
 [ - ]  cryptdisks
 [ - ]  cryptdisks-early
 [ + ]  dbus
 [ - ]  hwclock.sh
 [ + ]  irqbalance
 [ - ]  iscsid
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ - ]  lvm2
 [ - ]  lvm2-lvmpolld
 [ + ]  multipath-tools
 [ + ]  nginx
 [ - ]  open-iscsi
 [ + ]  plymouth
 [ + ]  plymouth-log
 [ + ]  procps
 [ - ]  rsync
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ + ]  ssh
 [ + ]  tor
 [ + ]  ubuntu-fan
 [ + ]  udev
 [ + ]  ufw
 [ + ]  unattended-upgrades
 [ - ]  uuidd
```
Te idea is to leave only essential services but do we need all those other services?

**Comment by dr-bonez** [comment]
I'll see how many services we can get rid of just by basing off of Ubuntu core instead of Ubuntu server.

**Comment by k0gen** [comment]
> I'll see how many services we can get rid of just by basing off of Ubuntu core instead of Ubuntu server.

Too bad they do not ship preinstalled images 
https://cdimage.ubuntu.com/ubuntu-core/20/stable/current/

**Comment by chrisguida** [comment]
@k0gen They do, I read that wrong the first time too. They have a prebuilt image for raspi

**Comment by k0gen** [comment]
> @k0gen They do, I read that wrong the first time too. They have a prebuilt image for raspi

I won't believe until I see one 😛

**Comment by chrisguida** [comment]
Is this not it?

<img width="960" alt="Screen Shot 2021-12-09 at 9 25 44 AM" src="https://user-images.githubusercontent.com/7445670/145424922-ff830be6-87a4-410a-8617-053b85dffcd5.png">
