### ISSUE TITLE
in-app back button has unexpected behavior

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#866]
Please fill out as much detail as possible:

**Describe the bug**
The back button on the Service Details Page can navigate you away from the EmbassyOS app entirely. The expected behavior would be to move from the Service Details Page to the Service List Page.

**To Reproduce**
1. Install a service
2. Close the tab
3. paste into your url bar `https://<embassy-local-address>/#/services/<service-id>`
4. Hit the in-app back arrow

**Expected behavior**
Go to Service List Page

**Actual behavior**
Go to browser home page

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 21.04
 - Browser and version: Brave 1.19.92

**Comment by MattDHill** [comment]
Closed by #7485b746dbdbb8d114099da3fa315a9d0f370806. We will now hide in-app back buttons when there is no history.
