### ISSUE TITLE
Add timeouts to healthchecks

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#867]
This process was running for approximately 30hrs

Reported by: @kn0wmad

**Comment by dr-bonez** [comment]
also adding @chrisguida to look into the specific health check. I will look into fixing the timeouts.

**Comment by ProofOfKeags** [comment]
which health check was running for 30hrs? Need that info to carve the work off.

**Comment by chrisguida** [comment]
vaultwarden

**Comment by dr-bonez** [comment]
are we 100% sure this is an embassy os health check? perhaps this is the built in `healthcheck` directive in the container for vaultwarden

@elvece

**Comment by dr-bonez** [comment]
f70e96cec9227ab8c9c9931ac613a7d2303ee796 might fix this.

**Comment by chrisguida** [comment]
>https://github.com/Start9Labs/embassy-os/issues/867#issuecomment-990163802

IIRC `htop` indicated `healthcheck.sh` which only exists in `vaultwarden`. @kn0wmad ?

**Comment by kn0wmad** [comment]
> > [#867 (comment)](https://github.com/Start9Labs/embassy-os/issues/867#issuecomment-990163802)
> 
> IIRC `htop` indicated `healthcheck.sh` which only exists in `vaultwarden`. @kn0wmad ?

That's all I've got.  Again, this issue has not resurfaced and I have tested approximately 4 builds since last witnessing it.

**Comment by dr-bonez** [comment]
I'm inclined to close. We can reopen if this is found again

**Comment by ProofOfKeags** [comment]
I feel like we should definitely be timing health checks out...otherwise we will have issues with unbounded resource usage.

**Comment by chrisguida** [comment]
We could add a P2/P3 to add a configurable-per-service timeout
