### ISSUE TITLE
Dependency Errors not repaired when service is started

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#868]
Please fill out as much detail as possible:

**Describe the bug**
When I start bitcoind, btc-rpc-proxy still reports a dependency error in the ui

**To Reproduce**
1. Install btc-rpc-proxy
2. Start btc-rpc-proxy
3. Install bitcoind
4. Configure bitcoind
5. start bitcoind

**Expected behavior**
btc-rpc-proxy shows no dependency errors

**Actual behavior**
btc-rpc-proxy shows dependency errors

**Screenshots**

![Screenshot from 2021-11-29 15-14-46](https://user-images.githubusercontent.com/4033651/143951271-e57f403d-49c8-41ff-9de3-174ac8718caf.png)

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 21.04
 - Browser and version: Brave 1.19.92

**Additional Context**
- Restarting embassyd doesn't fix this
- error is in patch-db state, not in UI

**Comment by elvece** [comment]
This should be escalated to P0 IMO, its very difficult to assert what is actually an issue with this bug while testing services, UI operations don't work as expected as a result as well.

**Comment by dr-bonez** [comment]
It seems like an easy fix. I'll prioritize it. Theory is that we just aren't accounting for the `starting` status properly.

**Comment by elvece** [comment]
Ok, if you want to give me direction I can try to figure it out. 

[related](https://github.com/Start9Labs/embassy-os/issues/869)

**Comment by dr-bonez** [comment]
fixed in fc221b81256c784fc3a4e9f1c0888ee06c3cd8d4
