### ISSUE TITLE
Transitive dependency errors not being reported

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#869]
Please fill out as much detail as possible:

**Describe the bug**
Services that should have transitive dependency errors do not have any indication of such even in patch-db

**To Reproduce**
1. install bitcoind
2. install proxy
3. install c-lightning
4. configure all
5. start all
6. stop bitcoind

**Expected behavior**
c-lightning should get a dependency error of transitive

**Actual behavior**
there is no dependency error at all

**Comment by elvece** [comment]
@ProofOfKeags This should be escalated to P0 IMO, its very difficult to assert what is actually an issue with this bug while testing services, UI operations don't work as expected as a result as well. 

 @dr-bonez This was not previously a problem so did something change wrt patch-db that caused this? If you can give me direction I can try to solve if others are busy.

**Comment by chrisguida** [comment]
I thought this was expected behavior when a dependency isn't critical? What exactly is the behavior you're expecting @ProofOfKeags ?

**Comment by chrisguida** [comment]
Does changing c-lightning to have a critical dependency on proxy fix this?

**Comment by dr-bonez** [comment]
`critical` is being removed as an idea

**Comment by chrisguida** [comment]
@dr-bonez what is the preferred fix for this? or is it expected behavior?

**Comment by dr-bonez** [comment]
This is an os bug. Will identify and fix.
