### ISSUE TITLE
Disable UAS Kernel Module

### ISSUE THREAD

**Issue by MattDHill** [Start9Labs/embassy-os#871]
Recommendation:

Expand current blacklist of drives known to implement UASP inadequately.

Create whitelist of drives known to implement UASP adequately.

During setup, if we detect an external drive that is not present in the blacklist or whitelist, (1) add it to the blacklist, (2) alert the user, (3) and reboot.

**Comment by ProofOfKeags** [comment]
Am I to understand that there are two blacklists then? One static, shipped with the base image of EmbassyOS, as well as a dynamic one that is generated by the user's interaction with a drive of their choice.

Secondly, is there a sensible way to feed this information back in such a way that future releases of the software can learn from the discoveries made by users? This definitely has privacy implications, and introduces some weak dependence on S9 core infrastructure. The benefits would be that we would not have to subject the user to a reboot if we already know their drive is incompatible with UAS, the drawbacks are that the infrastructure is centralized (though not single point of failure).

**Comment by dr-bonez** [comment]
Good news! UAS can be disabled globally by disabling the kernel module instead of setting a quirk on a device-by-device basis. Renaming the ticket to reflect this.

https://askubuntu.com/questions/1266804/blacklist-uas-drivers-in-kernel

**Comment by BitcoinMechanic** [comment]
Different issue now - not sure if related. (Sorry wrote this in wrong location initially)
![Screen Shot 2021-11-30 at 1 30 29 PM](https://user-images.githubusercontent.com/45926711/144133001-ebd60c4c-d6fe-4162-8101-05aee210b0b2.png)
.

**Comment by ProofOfKeags** [comment]
Apparently disabling UAS globally just makes the drives more obviously unusable, rather than fixing the issue. It looks like the way that storage quirks work is by enabling USBStorage rather than disabling UAS. This is how @dr-bonez intends to fix this
