### ISSUE TITLE
PhotoView not getting latest state from File Browser

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#881]
When PV is running, and FB is uninstalled out from under it, and then re-installed and started, PV does not see that FB is running.  

![image](https://user-images.githubusercontent.com/39687477/144267131-09c6be54-13ba-4cf3-bd84-b33388386474.png)

A re-install of PV fixes as a workaround.

Reported by @kn0wmad

**Comment by ProofOfKeags** [comment]
this is originally reported in #868 the problem is pervasive, closing as duplicate.
