### ISSUE TITLE
[feat]: Don't send all of stderr to the body of a notification on unclean exit

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#888]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Right now if a service periodically sends certain warnings to stderr and it's up for a while, if it ever uncleanly exits, we can get notifications of unbounded size, which is far from ideal.

We should have a better story around what stuff gets captured from stderr and put into the notification, or we should change how we render notifications such that it prioritizes rendering the end of the notification and allows an expanded view if the user wants to scroll back.

### Describe the Use Case

This was inspired by the problem found [here](https://github.com/Start9Labs/embassy-os/issues/860#issuecomment-984718201)

Sometimes information is sent to stderr that is uncorrelated with the reason that a service does not exit cleanly.

### Describe Preferred Solution

The preferable solution would be to have a structured output at the end of the log stream that we can parse, or possibly having a limit on the size we capture from the end of stderr so that we know exactly the relevant information needed to be reported on the error.

### Describe Alternatives

It's unclear what the solution should be. However, capturing all of stderr when a service can run for an unlimited amount of time, and then choosing to render all of it in the UI is certainly not behavior we want to have long term.

The simplest way to deal with this is to prioritizing the end of the stderr stream in the notification render, however that still requires us to save all of it to the db and transfer all of it over the wire.

**Comment by MattDHill** [comment]
Yes, at minimum, the FE should be grabbing the last ~1,000 chars from the string? But better solution is to only send what's relevant in the first place.

**Comment by ProofOfKeags** [comment]
Yeah the problem is that assessing relevance in the current design is not tractable. So we have to come up with global heuristics or design some structured output. It's definitely out of scope for 0.3.0 though. If you want to fix the rendering problem for 0.3.0 that's fine as the fix is somewhat straight forward but any more well designed fix is going to take longer than we can afford right now, hence the P2 designator.

**Comment by ProofOfKeags** [comment]
![image](https://user-images.githubusercontent.com/4033651/144666781-25b9ec4f-0cf2-47b8-9abb-7a70a6dd7611.png)

**Comment by MattDHill** [comment]
Closes for completion of FE fix.

**Comment by chrisguida** [comment]
Can we maybe do beginning and end, and cut out the middle? This isn't really better, doesn't even the exit code now or any useful information now:

![image](https://user-images.githubusercontent.com/7445670/144759306-7cb0760e-91a7-4a2d-9e42-aee4557a26a2.png)

**Comment by chrisguida** [comment]
Also I'm guessing this issue is needed to track the "real" fix, which is not high priority?

**Comment by ProofOfKeags** [comment]
we can reappropriate this ticket, but the "real fix" is probably not going into 0.3.0.

**Comment by DrewAns** [comment]
@chrisguida seeing as this ticket was always meant as a temporary fix, do you think we should close it, or would you rather see a different temporary fix.  If so can you be more specific about a solution you'd like to see?

**Comment by chrisguida** [comment]
> we can reappropriate this ticket, but the "real fix" is probably not going into 0.3.0. 

@ProofOfKeags ok, shall I create a new ticket that we can put on 0.3.1? I just didn't want the need for a "real" fix to be lost, and it seems like you put a lot of work into creating the original ticket for such a real fix.

**Comment by chrisguida** [comment]
> @chrisguida seeing as this ticket was always meant as a temporary fix, do you think we should close it, or would you rather see a different temporary fix.

@DrewAns I think this ticket was originally intended as backend feature request, but perhaps my interpretation was incorrect, @ProofOfKeags can clarify.

>If so can you be more specific about a solution you'd like to see?

I think a better temporary fix would be, say, 500 chars from the beginning, some ellipses, and 500 chars from the end. This is because we don't know whether the relevant information will be at the beginning or the end. For some reason, the 137 exit code appears at the *beginning* of the notification, even though it happens last, and so one would assume that the most relevant info would be at the end of stderr. This is how the errors look in bitcoind at least, and potentially most or all of the other services. 

It might actually be the case that the errors *always* contain irrelevant information at the end, in which case we could simply switch to the *first* 1000 chars. But in the interest of not having to exhaustively search all possible error messages, I think my 500/500 suggestion works best for now. I'm not gonna die on this hill though.

**Comment by ProofOfKeags** [comment]
Is the notification currently expandable? can you get at the exit code *at all*? If so, then I think it's fine to proceed without changes for 0.3, otherwise we should make it expandable until we can come up with a reasonable way to assess "relevance"

**Comment by chrisguida** [comment]
Oh, sure, making it expandable would be great. I don't see a way to expand the error message currently.

**Comment by MattDHill** [comment]
I'm fine with making error messages expandable.

**Comment by ProofOfKeags** [comment]
@DrewAns please make the error message expandable, leave the preview as the end of the message.

**Comment by DrewAns** [comment]
Added "View Full Message" clickable text under the truncated message. Clicking on it opens a modal with the full message.

**Comment by chrisguida** [comment]
@DrewAns this is not working

<img width="1235" alt="Screen Shot 2021-12-14 at 12 27 19 PM" src="https://user-images.githubusercontent.com/7445670/146058023-edf0d2fe-b7a2-4894-9f51-ae67e5b3b521.png">

**Comment by DrewAns** [comment]
Know issue.  Thanks Chris

**Comment by DrewAns** [comment]
Here's the commit that fixes this issue

https://github.com/Start9Labs/embassy-os/commit/a7633b7cb2cae49a662f91e3c764756e1ef2c14c
