### ISSUE TITLE
[bug]: bugs ui 

### ISSUE THREAD

**Issue by Rj100k** [Start9Labs/embassy-os#890]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

Big Sur M1 chip

### Browser

Tor Browser

### Browser Version

91.3.0esr

### Current Behavior

Under embassy menu once an option such as about or monitor are selected and open then back button is hit you are not able to open another option again. It does not open and have to navigate to a different menu such as marketplace etc. then go back to embassy to open. 

### Expected Behavior

The menu opens correctly 

### Steps to Reproduce

1. Hit embassy 2. Open about or monitor etc 3. Hit back 4. Try to open those options again 5. Navigate to any other menu 6. Go back to embassy to open about or monitor

**Comment by Rj100k** [comment]
This is only happening on tor browser. Works fine w Firefox for both local and .onion

**Comment by MattDHill** [comment]
@kn0wmad can you test this on a live device please and grab some console logs?

**Comment by kn0wmad** [comment]
Unable to repro on Tor or FF.  Checking with @Rj100k on security settings or if a refresh fixes, will update.

**Comment by ProofOfKeags** [comment]
Possible that the nav stack behaves differently in tor due to privacy considerations. @Rj100k can you also disclose what your tor browser's "security settings" (looks like a shield) are?

**Comment by kn0wmad** [comment]
This seems to have been a caching issue.  User was on standard settings, but also able to remedy with a refresh.  Closing for now until we globally solve issues with caching in all software
