### ISSUE TITLE
[feat]: Logs color blue unreadable 

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#893]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Blue color for DEBUG is very hard to read.
(I actually had to highlight it to read it)
![Screenshot from 2021-12-03 20-54-05](https://user-images.githubusercontent.com/3606313/144667726-c68810f3-9728-466b-bba1-69536333f23d.png)

### Describe the Use Case

Make it easy on eyes

### Describe Preferred Solution

Make it brighter

### Anything else?

Color for WARN could be a bit more yellow

**Comment by elvece** [comment]
Note to self: alter colors according to [lib configuration ](https://github.com/rburns/ansi-to-html#options)
