### ISSUE TITLE
[bug]: UI Copy for dependency warnings 

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#897]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0@dc93a03c1f8e452d176b50975e36ab353f588204

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.15.7

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

Copy around dependencies would be better worded as "dependency" instead of "dependencies". This happens on warning modals when trying to start a service when its dependencies are not met.

### Expected Behavior

Warning modals should read more clearly around dependency errors. 

### Steps to Reproduce

1. install bitcoin core
2. install bitcoin proxy
3. configure bitcoin core
4. configure bitcoin proxy
5. try to start bitcoin proxy without starting bitcoin core

### Anything else?

<img width="1672" alt="Screen Shot 2021-12-03 at 4 12 05 PM" src="https://user-images.githubusercontent.com/12953208/144686634-25aabdf6-55fd-44f8-ac14-76f4229b443f.png">

**Comment by DrewAns** [comment]
@elvece I just saw a git blame for the copy being this.

`${this.pkg.manifest.title} has unmet dependencies. It will not work as expected.`

It changed 8 days ago in the integration/0.3.0 branch.  Is this a possible caching or stale code issue?

**Comment by elvece** [comment]
> @elvece I just saw a git blame for the copy being this.
> 
> `${this.pkg.manifest.title} has unmet dependencies. It will not work as expected.`
> 
> It changed 8 days ago in the integration/0.3.0 branch. Is this a possible caching or stale code issue?

Welp, something must have been off in my state, because I cannot recreate on 9c1840b0e9e3bcb192e878d51ec51e5c54792536. Closing.
