### ISSUE TITLE
[feat]: consistent finalize message

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#898]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

EOS 0.3.0@dc93a03c1f8e452d176b50975e36ab353f588204

### Describe the Feature Request

It would be nice to see the "finalizing install" message on the marketplace page as well as on the list page. The services in the marketplace page show the install at 99% whereas it says "finalizing" on the list show page. The screenshots show the disparity. 

### Describe the Use Case

For clarity around long install times, it would be nice to have consistent messaging in the various places this information is displayed in the application.

### Anything else?
<img width="1673" alt="Screen Shot 2021-12-03 at 3 58 34 PM" src="https://user-images.githubusercontent.com/12953208/144687103-46d158e6-8b2c-48a4-9b23-31bea2b87376.png">
<img width="1671" alt="Screen Shot 2021-12-03 at 3 58 26 PM" src="https://user-images.githubusercontent.com/12953208/144687107-848e42a0-ce17-4694-906b-c68becc95fef.png">

**Comment by ProofOfKeags** [comment]
I thought this was fixed.

**Comment by elvece** [comment]
There were some UI changes an hour ago that I did not update with yet, @DrewAns was this encapsulated in those?
I am on dc93a03c1f8e452d176b50975e36ab353f588204

**Comment by chrisguida** [comment]
I too was confused as to the outcome of this issue: https://github.com/Start9Labs/embassy-os/issues/861

**Comment by ProofOfKeags** [comment]
It was done as part of #874

**Comment by ProofOfKeags** [comment]
I just reopened #861 and am closing this as a duplicate.
