### ISSUE TITLE
[bug]: Confiure/Start eventually hangs when all services installed 

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#906]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.15.7

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

There are several inconsistent issues going on that appear to be related.

When all services are installed:

(1) Configuring some services do not resolve after ~10minutes. I can not definitely say that they never resolve, as I have noticed cases where they eventually did finish after an extremely long time. However, this is not the case for every service, and it seems to only happen as you continue to configure additional services. In other words, the time to configure a service increases with each additional configuration. This hanging behavior only expresses with config.set, config.get works quickly as expected. 

(2) Some services hang on the "starting" spinner. I noticed this specifically with proxy. Bitcoind was able to be configured and started, proxy could be configured, but would never start. Repeating the same behavior for embassy-pages <> filebrowser (another dependency situation) worked as expected. Services without dependencies seem to start fine (bitcoind, filebrowser, vaultwarden), although this has been difficult to assert as completely true since I have been unable to have configuration for other services resolve to complete comprehensive testing.

Stopping the services I have been able to start worked fine in testing previously. However, I just experienced this error:
```
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]: Dec 05 15:42:55.749 ERROR embassy::manager::sync: Synchronizer for vaultwarden@1.22.2 failed: Docker Error: Timeout error
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]: Dec 05 15:42:55.749 DEBUG embassy::manager::sync: Error { source:
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]:    0: Timeout error
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]: Location:
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]:    /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/convert/mod.rs:540
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]:   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]:    0: embassy::manager::stop
Dec 05 15:42:55 embassy-7fed63b1 embassyd[45123]:       at src/manager/mod.rs:437
```

### Expected Behavior

When all services are installed, configuring services should take the expected amount of time and all services should be able to be started.

### Steps to Reproduce

1. Install all services
2. Start to configure them
3. Notice as you continue to configure, load times increase, potentially never resolving.

1. Install all services.
2. Configure all services
3. Start bitcoind, proxy, pages, filebrowser
4. Try to start LND (hangs in starting spinner)

### Anything else?

I have turned on trace logs for embassyd, embassy, and patchdb. There does not seem to be a deadlock as patchdb continues to log. There are no IO errors in dmesg logs. There is nothing significant in journalctl logs for embassyd. 

I did not notice this behavior when running on commit hash 8c1adae00a629b7a131e3fa7cce53538ba04dc0c. However, I only had about half of services installed at that time. 

I have noticed it since running dc93a03c1f8e452d176b50975e36ab353f588204, and it continues to happen up to 9c1840b0e9e3bcb192e878d51ec51e5c54792536. 

Only by restarting embassyd via `systemctl restart embassyd` can I get a "fresh slate" and continue to configure / start services. Ultimately, I get back to a state when actions hang, though.

Might be [related](https://github.com/Start9Labs/embassy-os/issues/905)

**Comment by elvece** [comment]
Update: with a restart of embasyd, I have been able to configure all services. Services without dependencies start fine. Services with dependencies hang on "starting" spinner.

**Comment by ProofOfKeags** [comment]
Do you have any commit in the history of 0.3.0 where you know this works?

**Comment by ProofOfKeags** [comment]
OK so here's what I've been able to figure out

This is reproducible in the following scenario:

1. Install bitcoind, proxy, c-lightning, lnd
2. Configure/start bitcoind
3. Configure proxy
4. Configure LND
5. Configure C-Lightning
6. Autoconf LND -> Proxy
7. Attempt to start Proxy
8. Proxy hangs

Variations of this process that work correctly
1. CL->Proxy: ConfigUnsat AND LND->Proxy: ConfigUnsat
2. CL->Proxy: NotRunning AND LND->Proxy: NotRunning
3. CL->Proxy: NotRunning AND LND->Proxy: ConfigUnsat

IMPORTANT: in every case, C-lightning is healed before LND. However the hanging always occurs in the try_heal call to LND (the second one). It is very strange but it appears that the ConfigUnsat from C-Lightning *causes* the try_heal on LND to deadlock.

I can take this no further on the current information I have.

**Comment by ProofOfKeags** [comment]
blocked on Start9Labs/patch-db#16
