### ISSUE TITLE
[Typo]: Temparature Typo in the web GUI

### ISSUE THREAD

**Issue by lvlouro** [Start9Labs/embassy-os#907]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0 - Git hash dc93a03c1f8e452d176b50975e36ab353f588204

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 20.04 LTS

### Browser

Firefox

### Browser Version

94.0

### Current Behavior

In the web GUI under Embassy --> Monitor --> Temperature monitor reads "Temparature"

### Expected Behavior

Should read "Temperature"

### Steps to Reproduce

In the web GUI go to Embassy --> Monitor --> read the word "Temparature"

**Comment by DrewAns** [comment]
@ProofOfKeags all keys and values on the Monitor page are dynamic based off what's coming from the back end.  On top of that, a global search for "Temparature" in the UI code base produces no results.  Therefor i have reason to believe the misspelling is coming from the back end.

**Comment by ProofOfKeags** [comment]
fixed by 9bc07b0
