### ISSUE TITLE
[bug]: Embassyd does not recognize preexisting containers on startup

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#909]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

144c0ce0b96c1ea23a79c2a35afd1c44354ee955

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Ubuntu 21.04

### Browser

Brave

### Browser Version

1.19.92

### Current Behavior

If  you start up embassyd and there's already a container running with the same name as one associated with a package that is desired to be running, rather than recognizing it as already running and pulling that state in, it gets into an error loop where it complains that there is a container conflict

### Expected Behavior

No error loop describing container conflict

### Steps to Reproduce

1. Install a service
2. Start the service
3. Restart embassyd
4. Observe error loop in logs

### Anything else?

```
Dec 06 01:05:19 embassy-99c0dff6 embassyd[227900]: Dec 06 01:05:19.894 ERROR embassy::manager: service crashed: 125: docker: Error response from daemon: Conflict. The container name "/bitcoind.embassy" is already in use by container "8e2f88d2c3551105feb4cb0d50f901f5888829fefd906946b7cd316202705b3e". You have to remove (or rename) that container to be able to reuse that name.
Dec 06 01:05:19 embassy-99c0dff6 embassyd[227900]: See 'docker run --help'.
```

**Comment by ProofOfKeags** [comment]
Clicking Stop and then Start on the service does cure this

**Comment by lvlouro** [comment]
I have this issue without having restarted the embassy (I checked bitcoin core logs to see if a random restart had occured and there is no sign of the service stopping) 
Running a fresh install with just bitcoin core going through IBD for the last 2.5 days.
Nor sure if this info changes anything.

**Comment by chrisguida** [comment]
@lvlouro are you sure you're not referring to the health check message, not the service itself?

https://github.com/Start9Labs/embassy-os/issues/899

**Comment by lvlouro** [comment]
Yes, health check, like #899 
Sorry for the confusion

**Comment by ProofOfKeags** [comment]
Yeah then @lvlouro 's observation is separate but related. I'm not sure if we want to or can do container conflict resolutoin in a purely general way but I think it should be possible to restart embassyd and not have conflicts in the main containers for sure.

**Comment by dr-bonez** [comment]
containers are cleared on reboot anyway, not sure of the value of doing it on restart of embassyd, since that will only happen on its own in development

**Comment by chrisguida** [comment]
Still seems worth a fix, but maybe as a P2?

**Comment by ProofOfKeags** [comment]
Will embassyd ever restart on its own (OOM, kernel kills it etc?)

**Comment by chrisguida** [comment]
Certainly seems conceivable, unless it never crashes for any reason
