### ISSUE TITLE
Tor becomes unresponsive on network interface changes (adding or changing WiFi)

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#91]
Currently the standard flow of adding WiFi and then dropping the Ethernet connection causes all Tor hidden services to be unreachable for an indeterminate period of time.

The dirty solution is to just restart tor when network interfaces change, but this may be overly aggressive. It would be better if we understood why Tor was becoming unresponsive during interface changes.

**Comment by elvece** [comment]
Irrelevant
