### ISSUE TITLE
[bug]: Firefox password manager offering to save Bitcoin Core RPC pass when changing values in config

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#918]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

Password manager pops up, offering to save RPC pass when dbcache (for example) is given a new value.

### Expected Behavior

No pop up.

### Steps to Reproduce

(Make sure firefox password manager is on)
Open bitcoin core config
Change dbcache
Save

**Comment by chrisguida** [comment]
Have you tested this without your embassy password stored in FF?

**Comment by ProofOfKeags** [comment]
Proposed solution: convert config password inputs into text inputs with masking pipe
