### ISSUE TITLE
Fresh install results in a system that cannot be logged in to due to DB error

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#919]
On Tor: 
![image](https://user-images.githubusercontent.com/39687477/145252777-9b04181e-6c68-4036-882f-83f297bc30ca.png)

On LAN:
![image](https://user-images.githubusercontent.com/39687477/145252979-e3771bdf-7613-4c26-8d7a-e2532d3070ff.png)

Reported by: @kn0wmad

**Comment by chrisguida** [comment]
What commit is this from?

**Comment by kn0wmad** [comment]
Cannot repro on today's build, closing for now
