### ISSUE TITLE
Remove severity from health check key of all services

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#920]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

This ticket is tracking the progress of removing the severity key from all service health checks, as it is being dropped until its necessity further understood. 

- [x] synapse
- [x] mastodon
- [x] bitcoind
- [x] ride-the-lightning
- [x] thunderhub
- [x] c-lightning
- [x] filebrowser
- [x] pages
- [x] lnd
- [x] btcpay
- [x] photoview
- [x] proxy
- [x] spark
- [x] bar
- [x] cups
- [x] sphinx
- [x] vaultwarden
- [x] bwt
- [x] hello-world

**Comment by chrisguida** [comment]
Downgrading to P2, definitely not blocking release
