### ISSUE TITLE
[feat]: Add local IP to Embassy -> About

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#923]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Add local IP address below Tor/LAN

### Describe the Use Case

Informational / SSH users

### Anything else?

There may be reasons (such as simplicity) to not do this

**Comment by ProofOfKeags** [comment]
Which interface? Ethernet or WiFi? both?

**Comment by kn0wmad** [comment]
I suppose both

**Comment by chrisguida** [comment]
Can it do both at the same time?

**Comment by kn0wmad** [comment]
Either show both, or show only when an IP is assigned.  Not sure what the logic looks like for that.  I assume just pull either all or active dev interfaces

**Comment by ProofOfKeags** [comment]
We can just have two entries: one for Ethernet, one for WiFi, and null out whichever one isn't being used.

**Comment by chrisguida** [comment]
I think that's fine for now
