### ISSUE TITLE
[bug]: EOS fails to grab both external SD card + SSD on first boot up when attempting to migrate. 

### ISSUE THREAD

**Issue by BitcoinMechanic** [Start9Labs/embassy-os#925]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

MacOS

### Device OS Version

10.14.6

### Browser

Firefox

### Browser Version

94.0.2

### Current Behavior

Reloading from `embassy.local` means it can then find the SD card. Then selecting an external drive - it won't find the SSD unless I reload yet again from `embassy.local` - then all is well.

### Expected Behavior

Should find both times on first boot up.

### Steps to Reproduce

Normal migration process with 0.2.x SD card plugged in using adapter.

**Comment by chrisguida** [comment]
I saw similar behavior when I did an 02x migration. I checked `lsblk` and the sd card wasn't showing, so I moved it to a different port and then it showed in `lsblk`. I had to refresh the page for it to show on the frontend.

**Comment by ProofOfKeags** [comment]
@BitcoinMechanic what commit? and can you describe more about what you mean with "reloading from .local", do you just mean a browser refresh?

**Comment by BitcoinMechanic** [comment]
>What commit

Don't know sorry. This was the latest code about 15 hours ago.

Basically a refresh, but back a few steps, as at the point where you need the drive you're at `embassy.local/#/recover`

I haven't tried a simple refresh yet.

**Comment by BitcoinMechanic** [comment]
Update: I can now no longer get Embassy to find the external SSD at all.

**Comment by chrisguida** [comment]
@BitcoinMechanic : `embassy-cli git-info` for future reference

**Comment by dr-bonez** [comment]
extended the sleep on usb reconnect. might help.

**Comment by BitcoinMechanic** [comment]
SD card was not found initially. Had to refresh just once.

SSD could not be found until unplugged/plugged and refreshed.

**Comment by chrisguida** [comment]
Tested this with an 030 recovery and it worked the first time :+1:

**Comment by BitcoinMechanic** [comment]
This isn't to do with recovery, this is solely about attempting to migrate from 0.2.x

**Comment by chrisguida** [comment]
I believe they're the same API call, `setup.disk.list`

**Comment by dr-bonez** [comment]
this seems to be specific to the hard drive that @BitcoinMechanic is using. still looking into why it's happening

**Comment by BitcoinMechanic** [comment]
Fwiw my SSD is a Samsung T5.

**Comment by chrisguida** [comment]
@BitcoinMechanic interesting, mine too
