### ISSUE TITLE
[spike]: determine if `dtoverlay=dwc2` should be kept

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#929]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

The base ubuntu server image uses `dtoverlay=dwc2` by default in `config.txt`. Currently, we remove this. We should look into what this option does and if it's good for our setup.

**Comment by k0gen** [comment]
I think we are safe as long as we don't want to use USB-C as host for serial connection etc.

https://github.com/raspberrypi/linux/tree/rpi-5.10.y/drivers/usb/host/dwc_otg

But in case of USB devices errors or problems (like hubs or drives) this might be the first thing to enable for troubleshooting.

**Comment by ProofOfKeags** [comment]
> I think we are safe as long as we don't want to use USB-C as host for serial connection etc.

safe to remove it or safe to keep it?

**Comment by k0gen** [comment]
> > I think we are safe as long as we don't want to use USB-C as host for serial connection etc.
> 
> 
> 
> safe to remove it or safe to keep it?

Keep it for now and when first bigger wave of people start using 0.3.0 with their drive setup revisit this issue and test against bigger audience.

**Comment by Blu-J** [comment]
From what the research that I have found so far, the default is dwc-otc
![image](https://user-images.githubusercontent.com/2364004/146810584-8c90f33e-fd05-4c54-a89f-30dff00d4c78.png)

 [Raspberry Pi Readme](https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README) 

Which is the faster and more performant + less buggy mode, unless we wanted to run our Raspberry Pi in the Gadget Mode. I believe that the gadget mode is not even being a feature we want yet. As for debugging via the gadget mode I think we have been able to debug easily with the Ethernet + wifi

![image](https://user-images.githubusercontent.com/2364004/146810348-70010117-d8a7-4e85-8aea-48b1b2b54f33.png)
[Picture Source](https://forums.raspberrypi.com/viewtopic.php?t=179259)

**Comment by dr-bonez** [comment]
Sounds like the best option is to leave it disabled. Thanks.
