### ISSUE TITLE
[feat]: Configurable TERM->KILL delay

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#937]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

We want services to be able to alter the default delay time between when EmbassyOS sends the SIGTERM to the container and when it sends a SIGKILL. This should be an optional key in the manifest and a global system default if the key is ommitted.

### Describe the Use Case

bitcoind can take longer than 60s to gracefully shutdown following a SIGTERM with undesirable consequences if it is killed before then. However, globally cranking the delay value will cause other undesirable consequences like services that are misbehaving might block further action until the Kill is submitted.

### Describe Preferred Solution

Optional key in manifest

### Describe Alternatives

No alternatives.

**Comment by chrisguida** [comment]
We should probably add something on the UI as well to alert the user in case the timeout is half an hour or so? @ProofOfKeags mentioned a countdown clock

**Comment by ProofOfKeags** [comment]
Captured in #949

**Comment by chrisguida** [comment]
https://github.com/Start9Labs/embassy-os/pull/951 fixes this

**Comment by dr-bonez** [comment]
to test: start bitcoind with a high dbcache. Click stop - make sure it takes more than 30s to shut down, and make sure the frontend messages that it will take a while

**Comment by chrisguida** [comment]
It's very unlikely that bitcoind will take shorter than 30s to shut down, even with the default dbcache. However, not that you will need to run IBD for a while in order for the cache to fill up. You can see how big it is in the logs. My recommendation is to set dbcache to something totally nuts like 4096, then stop IBD when the cache reaches around 1000MB. Should take at least a minute to stop

**Comment by ProofOfKeags** [comment]
This has been in UAT for a week. Test it and move it @DrewAns
