### ISSUE TITLE
Cannot restore previous 030 hard drive

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#945]
Steps to reproduce:
1. Set up 030
2. Reflash
3. Try to setup 030 on the same hard drive

Drive was visible in `lsusb` but not `lsblk`. I refreshed the page and it still did not show up. I replugged the drive and it showed up in `lsblk`. I then refreshed the page and it showed up on the frontend. But then:

<img width="1097" alt="Screen Shot 2021-12-10 at 5 30 52 PM" src="https://user-images.githubusercontent.com/7445670/145654755-223e65c6-f370-403f-b570-28f958df0af1.png">
<img width="1266" alt="Screen Shot 2021-12-10 at 5 33 53 PM" src="https://user-images.githubusercontent.com/7445670/145654757-6141ae91-e26f-47bc-8e42-dfcac89b0321.png">

I rebooted and it worked on the next try.

Git commit hash: b35f866c18dab292d86965f16e5200f431b83691

**Comment by dr-bonez** [comment]
@chrisguida some changes have been made that may affect this - please retry

**Comment by chrisguida** [comment]
Do you mean when you bumped sleep from 1 to 2? I've tried with that code a couple of times now and it seems fixed. Or, I may have just gotten lucky.

We can close if you want.

**Comment by dr-bonez** [comment]
>Do you mean when you bumped sleep from 1 to 2?

Yes
