### ISSUE TITLE
[feat]: apt install packages is not up to date

### ISSUE THREAD

**Issue by dme1sc** [Start9Labs/embassy-os#946]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

I installed the integration/0.3.0 from source on a new raspiberry pi 4-8gb using ubuntu 20.04 as dev build system.  Through the build process, I noted that I received numerous messages about packages needing updates - 126 total and 12 with security vulnerabilities.  I did not manually update these for concern of breaking something embassy required.

Git Hash '4a101b070e144c6073a8acfe16a44a0e36c94b88'

I do not have the logs.  My pi is still at this update status.  I was asked by chrisguida to document this need for the build to have updates.

### Describe the Use Case

0.3.0 build needs basic apt updates/upgrades.

### Describe Preferred Solution

verify updates for current embassy version and upgrade as needed

**Comment by ProofOfKeags** [comment]
This can be partially addressed by #865, further we can update apt packages in the initialization script. We should definitely not be dynamically updating packages while the system is running though.
