### ISSUE TITLE
[feat]: include snmp and snmpd with Embassy base build for monitoring purposes

### ISSUE THREAD

**Issue by tinysound464** [Start9Labs/embassy-os#948]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

i would like `snmp` and `snmpd` packages included with the Embassy build for monitoring purposes. 

### Describe the Use Case

icinga, nagios, observium, etc. 

### Describe Preferred Solution

into the initial build requirements

**Comment by dr-bonez** [comment]
@tinysound464 can you expand on how this is useful?
