### ISSUE TITLE
[feat]: Stopping countdown clock

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/embassy-os#949]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Some packages take a long time to shutdown and we are adding configurable timeouts in #937. We should add a countdown on the front end to signify the time when the Kill will fire.

### Describe the Use Case

Bitcoind may take many minutes to shutdown all the way.

**Comment by MattDHill** [comment]
This sounds a little terrifying. What is the purpose of showing a countdown over messaging like "this could take a few minutes"? Is it to provide the user an estimate such that they can plan accordingly. What if the countdown expires? What happens and should be concerned? What if the shutdown completes before the countdown, is that normal? This raises a lot of questions in my mind. I think providing a simple estimation of time in the form of "this could take up to [n] minutes" or similar would be more effective.

**Comment by chrisguida** [comment]
We should add a KILL button, too. Just realized "roll forward" will always take the sigterm max grace period

**Comment by dr-bonez** [comment]
it will be rare for things to take the full timeout period to complete. do we really want a countdown, when it will rarely reach 0?

**Comment by chrisguida** [comment]
I agree, in 0.2.x everything was killed after 30 seconds, so services taking 5m to shut down will feel like a downgrade

**Comment by DrewAns** [comment]
The way its implements, we warn the user that it may take a while if over 30 seconds
