### ISSUE TITLE
Add ability to change Registry

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#950]
At minimum, it needs to be possible to change registry for alpha/beta testing, but it's also a big thesis of the company that the ability of someone else to host a Marketplace at least be available

Reported by: @kn0wmad

**Comment by ProofOfKeags** [comment]
The broader story here is captured in #435. I'm closing this as a duplicate since the hackable version is already available in embassyd today.

**Comment by dr-bonez** [comment]
there is no easy way to change this rn. It is not done with config, but requires editing patch-db. reopening to add an rpc command to change it.

**Comment by ProofOfKeags** [comment]
Is there any reason we can't just seed patch-db with a config override if it exists?

**Comment by dr-bonez** [comment]
yeah but I don't see why that would be any easier

**Comment by MattDHill** [comment]
I think it's important to support changing the marketplace URL, similar to how we do it in 0.2.x. Right now, this is less about supporting alternative marketplaces as a means of reducing dependency on Start9 (which we all agree is important) and more about being able to use our *own* alternative marketplaces (alpha, beta). I personally have needed to make this switch every time we release anything new.

**Comment by ProofOfKeags** [comment]
Yeah, to be clear the facilities exist already, we just don't have any effective way to do it from the CLI or UI. Should be a very easy change to make.
