### ISSUE TITLE
[feat]: Initialization.sh should play a "bep" noise

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#952]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Initialization.sh should play a "bep" noise

### Describe the Use Case

When the user first plugs in their embassy, they have to wait 5 minutes for the initialization.sh script to run. Then once it's done, there's a bep immediately followed by a chime, so the bep does not serve much purpose here.

**Comment by ProofOfKeags** [comment]
This is too hard to be worth it.

**Comment by chrisguida** [comment]
Well, I guess as long as we're communicating some other way that the embassy will take a few minutes after you plug it in for it to do anything, then that's fine

**Comment by dr-bonez** [comment]
this only applies to build-from-source. embassy images that we ship will have initialization.sh already run

**Comment by MattDHill** [comment]
Should this be closed? Anyone building from source will be following a guide. We could include messaging in the guide setting expectations. Also, we have the "Embassy is initializing page" that will show during this time, correct?

**Comment by chrisguida** [comment]
I'd say this is solved handily by ["nc <raspi ip> 8080"](https://github.com/Start9Labs/embassy-os/pull/1675#issue-1312339947)
