### ISSUE TITLE
Update all Instructions.md files

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#955]
Update all Instructions within service packages and include applicable guides.  Also link to repositories for latest updates

- [x] Bitcoin Core
- [x] BTC Proxy
- [x] Synapse
- [x] Sphinx
- [x] LND
- [x] C-Lightning
- [x] RTL
- [x] Thunderhub
- [x] File Browser
- [x] Photoview
- [x] BAR
- [x] Hello-World
- [x] Vaultwarden
- [x] Spark
- [x] Mastodon
- [x] Pages
- [x] Cups
- [x] BTCPay
- [x] Double check that no services were missed

**Comment by elvece** [comment]
Note: need to change references to Bitwarden in other service instructions to Vaultwarden

**Comment by kn0wmad** [comment]
I've been making guides where needed for services with lots of external integrations (i.e. bitcoin/lightning), but I'm a bit torn on something like Vaultwarden.  I wrote up a guide and it's quite lengthy, but looking at the instructions.md, it could possibly just drop-in replace them.  My initial idea is to have the instructions.md be a bit simpler and usage focused and link to the guides (which will not require a service update to edit).  Thoughts?

**Comment by kn0wmad** [comment]
No, I'm asking what is the cutoff for guides being included in the instructions.  Currently vaultwarden has instructions for 3rd party integrations, but Bitcoin for example, segregates them.

**Comment by ProofOfKeags** [comment]
> No, I'm asking what is the cutoff for guides being included in the instructions. Currently vaultwarden has instructions for 3rd party integrations, but Bitcoin for example, segregates them.

CC @MattDHill

**Comment by elvece** [comment]
Verified this list includes all the services

**Comment by kn0wmad** [comment]
Closing for now, will start a new ticket to refactor after 0.3
