### ISSUE TITLE
[feat]: Put back the "View in Markeplace" button from 0.2 on the package details page

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#957]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Put back the "View in Markeplace" button from 0.2 on the package details page

### Describe the Use Case

This button makes it much easier to check for updates, downgrade, look at release notes, links, etc. There's no reason I should have to go all the way out to the marketplace and search for the marketplace listing for the app I was just in.

Look at all this stuff I'm missing out on:

![Screenshot from 2021-12-15 18-29-47](https://user-images.githubusercontent.com/7445670/146286064-23ada2f4-2c51-416e-a05b-487b379b8767.png)

### Describe Preferred Solution

Put back the "View in Markeplace" button from 0.2 on the package details page

### Describe Alternatives

Put all this functionality directly *on* the details page? Seems easier just to add a link though.

**Comment by ProofOfKeags** [comment]
What PR fixed this?

**Comment by dr-bonez** [comment]
@DrewAns

**Comment by DrewAns** [comment]
Might be hard to find because it was merged in with alexes massive pr

**Comment by ProofOfKeags** [comment]
https://github.com/Start9Labs/embassy-os/commits/drew-water-edits ?
