### ISSUE TITLE
[bug]: LAN address shows https://embassy.local/ in About

### ISSUE THREAD

**Issue by bbqchef** [Start9Labs/embassy-os#960]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

0.3.0

### Device

Laptop/Desktop

### Device OS

Windows

### Device OS Version

Windows 10

### Browser

Firefox

### Browser Version

95.0

### Current Behavior

The LAN address in the About page is not updated and remains https://embassy.local/.
![EOS3 Lan](https://user-images.githubusercontent.com/96219817/146306936-e930ece1-6ab2-4c67-842c-d86be256c17e.PNG)

### Expected Behavior

Show updated LAN address https://embassy-[XYZ].local/

### Steps to Reproduce

Embassy -> About -> LAN Address

**Comment by ProofOfKeags** [comment]
Does this behavior persist across hard refreshes in the UI? (Ctrl + Shift + R)

**Comment by bbqchef** [comment]
> Does this behavior persist across hard refreshes in the UI? (Ctrl + Shift + R)

Yes, and also after a restart of the embassy.
