### ISSUE TITLE
WiFi does not connect, then disappears

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#976]
To repro: Add wifi network, attempt to connect.

Behavior: Wifi network disappears

![image](https://user-images.githubusercontent.com/39687477/146630815-19d9923b-4e28-4ec2-b3ff-428ff729d479.png)

Reported by: @kn0wmad

**Comment by Blu-J** [comment]
I couldn't get this recreated yet

**Comment by kn0wmad** [comment]
Could not recreate the disappearance, but still have not successfully connected.  There's also no indication of connection status.  Will test further after reflashing current code

**Comment by Blu-J** [comment]
Can connect to one of my wifi's
The other it doesn't then it recreates the above. 
And no errors show in the frontend, but error logs in backend

**Comment by Blu-J** [comment]
Here I can't recreate it, also notice that I have connected

https://user-images.githubusercontent.com/2364004/147598475-d394cb12-c2a3-4ae3-8d55-935d30ec4549.mp4

Below is the recreation


https://user-images.githubusercontent.com/2364004/147598448-e59e0646-be4d-47c8-9c1f-0395aa864430.mp4

**Comment by Blu-J** [comment]
Best guess from my end is that it has issues connecting to 2.4 ghz

![image](https://user-images.githubusercontent.com/2364004/147598618-e87a8071-f0bc-4f62-a018-1e5ccaff3211.png)
