### ISSUE TITLE
Memory leak in UI

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#977]
First noticed on Monitor page
Edit: Seemingly ONLY the Monitor page

Reported by: @kn0wmad

**Comment by DrewAns** [comment]
@kn0wmad how long was this window open before out of memory was thrown

**Comment by kn0wmad** [comment]
Don't remember, maybe a half day.  Every other page would load

**Comment by DrewAns** [comment]
Have not witnessed memory leak behavior since pr.  The behavior was non deterministic, so if it shows up again we can just reopen the pr.

**Comment by kn0wmad** [comment]
Can still reproduce that the Memory page will occupy 1G+ of RAM within a short time, although it doesn't seem to runaway like it did before, this still seems high

**Comment by ProofOfKeags** [comment]
In my view if @kn0wmad can still repro after this commit we should reopen the issue. However, if it is limited strictly to the metrics page and someone can hang out on that page for ~10min we can kick this to P2 and not spend anymore time on it for 0.3.0

**Comment by kn0wmad** [comment]
> In my view if @kn0wmad can still repro after this commit we should reopen the issue. However, if it is limited strictly to the metrics page and someone can hang out on that page for ~10min we can kick this to P2 and not spend anymore time on it for 0.3.0

This is certainly the case, and I agree it's a low priority.  Feel free to punt, I just want to make sure it is in the record and not lost.  

I left the tab open for the last 2 hours to test and it ran up approx. 2.5-3G RAM and the page ceased to function, so definitely a real leak.

**Comment by kn0wmad** [comment]
It appears this was solved in #1008 - is that correct?  Can close if so

**Comment by ProofOfKeags** [comment]
Let's close until we encounter it in the wild again.
