### ISSUE TITLE
Marketplace OS Update bugs

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#978]
EDIT: see this comment for the bugs: https://github.com/Start9Labs/embassy-os/issues/978#issuecomment-998083853

**Comment by chrisguida** [comment]
Deleted this from db:

`2|2021-10-08 20:44:44.230338+00|2021-10-08 20:44:44.230338+00|0.3.1|EmbassyOS v0.3.1|Second release boiiii`

Can probably added to the alpha registry once we have one:

https://github.com/Start9Labs/registry/issues/51

**Comment by chrisguida** [comment]
This has uncovered 2 bugs:

This modal is showing up even though I already have 0.3.0
<img width="812" alt="Screen Shot 2021-12-20 at 10 25 47 AM" src="https://user-images.githubusercontent.com/7445670/146800350-4e732546-204a-4eb5-988b-63f9d5631d5e.png">

And I can't press the cancel button:
<img width="1440" alt="Screen Shot 2021-12-20 at 10 26 20 AM" src="https://user-images.githubusercontent.com/7445670/146800388-73a31443-0a4c-4c24-829e-734edc403db9.png">

**Comment by ProofOfKeags** [comment]
What are the actual bugs?

**Comment by chrisguida** [comment]
@ProofOfKeags https://github.com/Start9Labs/embassy-os/issues/978#issuecomment-998083853

**Comment by ProofOfKeags** [comment]
got it. For some reason I thought that was separate from the original ticket scope.

**Comment by chrisguida** [comment]
It is, I sort of hijacked this issue since fixing the original issue uncovered it. It's all there in the history, so I figured creating a new issue wasn't worth it. Let me know if you want a new issue.
