### ISSUE TITLE
[feat]: Support x86_64 Architecture for Embassy Pro

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#981]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

Self-explanitory

### Describe the Use Case

Expand hardware options

### Describe Preferred Solution

Soon

**Comment by ProofOfKeags** [comment]
So in theory we already support x86. What inspired this ticket?

**Comment by kn0wmad** [comment]
In theory?  This is prerequisite for a test device for potential next hardware

**Comment by ProofOfKeags** [comment]
My point is that we haven't tested on an actual x86 device, but theres no reason I can think of that it won't work. However, testing on new hardware carries more requirements than just making it run on a new architecture, it also requires that things like the sound API works similarly/the same on the new hardware or a relaxing of the requirement that that particular feature works. If this is for testing a device on x86_64 we are already at a place where it can be tested.

**Comment by chrisguida** [comment]
Perhaps we should turn this into 2 tickets: "test building embassy-os on x86", "make a build guide for x86"?

**Comment by kn0wmad** [comment]
This is purely needed internally at the moment, and when I spoke with @dr-bonez about it, he insinuated it was trivial to 'add support for.'  I'm not sure what is entailed here, but the device is now specifically known

**Comment by k0gen** [comment]
How about services? Will they include multi platform binaries or there will be a separate marketplace for x86_64 architecture?

**Comment by ProofOfKeags** [comment]
> How about services? Will they include multi platform binaries or there will be a separate marketplace for x86_64 architecture?

We already have support in the marketplace protocol for architecture specification. Packages will need to provide s9pks for the architectures they want to support.

**Comment by chrisguida** [comment]
I'm guessing embassy-os will know which architecture to request based on where it's running
