### ISSUE TITLE
determine if swap space is causing cpu and i/o problems

### ISSUE THREAD

**Issue by dr-bonez** [Start9Labs/embassy-os#982]
cut a branch that disables swap space by removing relevant code in [appmgr/src/disk/main.rs](https://github.com/Start9Labs/embassy-os/blob/integration/0.3.0/appmgr/src/disk/main.rs) and work with @kn0wmad and @BitcoinMechanic to determine if this resolves problems with processes getting stuck taking a high percentage of the cpu. Also look into whether this is related to IBD rolling back.

related: #901

**Comment by Blu-J** [comment]
So, with the changes in https://github.com/Start9Labs/embassy-os/pull/996 we get a full restart of the node instead of the system slowing down from what I could tell

![image](https://user-images.githubusercontent.com/2364004/147170459-4faea7cb-58fe-4cf5-aadc-a06b70d62cf3.png)
