### ISSUE TITLE
Fix build scripts

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#988]
The build scripts in the appmgr/ directory need to be updated to build `embassy-sdk` rather than appmgr portable

Pretty sure this is the correct command: `cargo install --bin=embassy-sdk --path=. --no-default-features`: https://github.com/Start9Labs/embassy-os/blob/integration/0.3.0/appmgr/build-portable.sh

Not sure what these are for: 
https://github.com/Start9Labs/embassy-os/blob/integration/0.3.0/appmgr/build-portable-dev.sh
https://github.com/Start9Labs/embassy-os/blob/integration/0.3.0/appmgr/build-dev.sh

**Comment by dr-bonez** [comment]
@chrisguida I think you are looking for `install-sdk.sh`. `build-portable.sh` is for building the sdk that runs on the registry and it works fine!

**Comment by chrisguida** [comment]
@both of you, this ticket is from a while ago. Things were updated since this ticket was created :)
