### ISSUE TITLE
Properties migration failing in some cases

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#992]
After migration, filebrowser properties will not render. These errors were thrown in the console, omitting massive stack traces.
There seems to be an incompatibility between the FE types expected for these values. When filebrowser is installed regularly (not from a migrated version), the missing values are populated correctly. See screenshots for comparison. 

```
Error: unknown properties version 1, attempting to parse as v2
Error: /data/0: should NOT have additional properties
Error: /data/0: should have required property 'type'
Error: /data/0: should have required property 'masked'
Error: /data/0: should have required property 'value'
Error: /data/0: should NOT have additional properties
Error: /data/0/value: should be object
Error: /data/0: should match some schema in anyOf
```

Migrated version properties response:
<img width="1673" alt="Screen Shot 2021-12-21 at 11 15 39 PM" src="https://user-images.githubusercontent.com/12953208/147045654-c24ded7d-0f0c-4140-a668-3c9bbff8cbce.png">

Fresh install properties response:
<img width="1674" alt="Screen Shot 2021-12-21 at 11 15 29 PM" src="https://user-images.githubusercontent.com/12953208/147045716-d3a91f2f-60a7-40f5-8374-fbe60c284453.png">

We could make the FE types more lenient, but these values are probably expected for UI renderings, so the solution is probably to write a migration for Filebrowser `stats.yaml`. Please confirm @dr-bonez.

**Comment by dr-bonez** [comment]
I didn't realize we removed support for v1 properties. @MattDHill, any objections to adding it back?

**Comment by MattDHill** [comment]
No issue from me. I'm not super familiar with that code since you wrote it originally. We could also migrate File Browser to V2 if it's the only one.

**Comment by dr-bonez** [comment]
I'm happy to do it, just wanted to make sure there wasn't an intentional reason to remove it.

**Comment by elvece** [comment]
Tested and confirmed working with #1070 !
