### ISSUE TITLE
[bug:] Health checks that timeout do not return an error message to the frontend

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#997]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.

### EmbassyOS Version

b6429beb945d21b519bc207701b5841ce0b37582

### Current Behavior

![Screenshot from 2021-12-23 08-41-46](https://user-images.githubusercontent.com/7445670/147255677-ea3bfb6f-985d-4bc0-bc76-d993a3cff6dc.png)

### Expected Behavior

The frontend is expecting an error message to accompany health check failures

### Steps to Reproduce

1. IBD bitcoin, make sure RPC takes longer than timeout to return
2. View healthchecks in UI

**Comment by dr-bonez** [comment]
What error message would you want?

**Comment by chrisguida** [comment]
Not sure, perhaps "health check timed out"? @MattDHill should probably weigh in here

**Comment by MattDHill** [comment]
"Health check timed out" is ok, but it leaves me wondering, "So what? What now?" To whatever extent we can, we should make health check error messages actionable, or make it clear that no action should be taken. Anything else is likely to result in a support inquiry.

In this case, what will happen next? Will the health check automatically re-run on some interval? If so, we could say something like "...Retrying soon." If not, then maybe "...restart service to try again." Or if it's fine and expected, "no action required."

**Comment by chrisguida** [comment]
In bitcoin's case is just means the rpc isn't responding, which actually happens quite regularly during IBD. Eventually it starts responding again.

One option would be to simply not return anything, and allow the frontend to sustain the previous status. But, if there actually *is* a problem, then the user should know. Maybe the "..retrying soon" option is best, to avoid those cases.

**Comment by dr-bonez** [comment]
Ok, so `"Timed out. Retrying soon..."`?
